### ISSUE TITLE
Remove tests from distribution

### ISSUE THREAD

**Issue by GMTA** [php-mime-mail-parser/php-mime-mail-parser#104]
At the moment, the "tests" folder weighs in at 9MB of data that is pulled in and stored within the "vendor" folder when using php-mime-mail-parser as a dependency. It would be nice if these tests could be left out.

For a way to do this, please see:
https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production/

**Comment by eXorus** [comment]
So easy and done.

Thanks.
