### ISSUE TITLE
Decoded subject does not match original subject.

### ISSUE THREAD

**Issue by odknt** [php-mime-mail-parser/php-mime-mail-parser#107]
`decodeSingleHeader` is not be removed white space in the below case.

```sh
=?ISO-2022-JP?B?GyRCIU4lRiU5JUghTyVPJW0hPCVPJW0hPCEqISo6I0Z8JGI4NTUkGyhC?=
 =?ISO-2022-JP?B?GyRCJEskLCRzJFAkayQ+JCQhKiEqISohKiEqISohKiFOJUYlOSVIGyhC?=
 =?ISO-2022-JP?B?GyRCIU8bKEI=?=
```

```sh
# expected
［テスト］ハローハロー！！今日も元気にがんばるぞい！！！！！！！［テスト］
# actual
［テスト］ハローハロー！！今日も元気にがんばるぞい！！！！！！！［テスト ］
```

The same is true of `m0021` in `ParserTest.php`.

```sh
# not `Пут ін` but `Путін` 
occurs when divided into an array, and the last e of the array! Пут ін хуйло!!!!!!
```

**Comment by eXorus** [comment]
Why the space need to be remove ? sorry for the stupid question  :)

**Comment by odknt** [comment]
This test should be failed.
That's because not contain a space in subject of [m0021](https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/master/tests/mails/m0021).


```sh
Subject: =?windows-1251?Q?occurs_when_divided_into_an_array?=
 =?windows-1251?Q?=2C_and_the_last_e_of_the_array!_=CF=F3=F2?=
 =?windows-1251?Q?=B3=ED_=F5=F3=E9=EB=EE!!!!!!?=

# occurs when divided into an array, and the last e of the array! Путін хуйло!!!!!!
```

Must be remove a space or insert a underscore to encoded subject.

```diff
-occurs when divided into an array, and the last e of the array! Пут ін хуйло!!!!!!
+occurs when divided into an array, and the last e of the array! Путін хуйло!!!!!!
```

or

```diff
 Subject: =?windows-1251?Q?occurs_when_divided_into_an_array?=
  =?windows-1251?Q?=2C_and_the_last_e_of_the_array!_=CF=F3=F2?=
- =?windows-1251?Q?=B3=ED_=F5=F3=E9=EB=EE!!!!!!?=
+ =?windows-1251?Q?_=B3=ED_=F5=F3=E9=EB=EE!!!!!!?=
```

**Comment by eXorus** [comment]
My question was more about why "Пут ін хуйло" is not true according to "Путін хуйло"

But Google said:

Пут ін : 109 000 results
Путін : 2 600 000 results

And wikipedia write "Путін" https://uk.wikipedia.org/wiki/%D0%9F%D1%83%D1%82%D1%96%D0%BD_%E2%80%94_%D1%85%D1%83%D0%B9%D0%BB%D0%BE!

So I trust you :)
