### ISSUE TITLE
howto use this in a shared hosting environment

### ISSUE THREAD

**Issue by markjansennl** [php-mime-mail-parser/php-mime-mail-parser#109]
Hi all, 

This may sound as a very silly question to you experts, but can you tell me how to use this class in a shared hosting environment? I can't install Composor obviously.

Thanks.

**Comment by eXorus** [comment]
Hi,

You can copy the files from your local computer it's enough if you want.

But you need to have mailparse extension activated in your shared hosting environment ... and I'm not sure it will be.
