### ISSUE TITLE
Email Pipe

### ISSUE THREAD

**Issue by Kr3m** [php-mime-mail-parser/php-mime-mail-parser#110]
Is there a way this can be used with piped email (e.g I have a postfix alias set to run a php script which works just fine)?

**Comment by Kr3m** [comment]
maybe something along the lines of
`$path = fopen("php://stdin", "r");`

**Comment by eXorus** [comment]
Of course I'm using it like this :

### /etc/postfix/master.cf

Add this line at the end of the file
```
myhook unix - n n - - pipe
  				flags=F user=www-data argv=php -c /etc/php5/apache2/php.ini -f /var/www/test.php ${sender} ${size} ${recipient}
```

Edit this line
```
smtp      inet  n       -       -       -       -       smtpd
        			-o content_filter=myhook:dummy
```

### /var/www/test.php

```php
require_once __DIR__.'/vendor/autoload.php';

//read from stdin
$Parser = new PhpMimeMailParser\Parser();
$Parser->setStream(fopen("php://stdin", "r"));

```

**Comment by Quix0r** [comment]
All mails are not reaching when I do this. I think the whole message needs to be printed out as it is a pipeline?

**Comment by eXorus** [comment]
No, it's working well for me for several years.

Maybe you have another rule in your pipeline that is override what you want ?

**Comment by Quix0r** [comment]
Okay, I upload my file. I'm not so really good into it. :-/
