### ISSUE TITLE
No releases available for package "pecl.php.net/mailparse" / install failed

### ISSUE THREAD

**Issue by DrLightman** [php-mime-mail-parser/php-mime-mail-parser#111]
Hello, trying to install php-mime-mail-parser via composer, following your guide.

Proceeding to install mailparse-2.1.6 extension on my Windows 10 xampp PHP 5.6.11, getting this response:

> C:\> pecl install mailparse-2.1.6
> No releases available for package "pecl.php.net/mailparse"
> install failed

Could be viable the option to download the DLL manually from here?

http://pecl.php.net/package/mailparse

I see there are 3 DLLs available for versions 2.1.6, 3.0.0 and 3.0.1

**Comment by eXorus** [comment]
Never use on Windows but I think it's working well with 2.1.6 if you have PHP5 and 3.0.1 if you have PHP7

**Comment by DrLightman** [comment]
FYI, it worked like a charm using the appropriate (ts/nts, x86/x64) DLL from the link above and adding the line "extension=php_mailparse.dll" to php.ini accordingly.

**Comment by eXorus** [comment]
Nice I keep this issue to update the readme with the installation on windows :)
