### ISSUE TITLE
Text and html part as attachment

### ISSUE THREAD

**Issue by gharlan** [php-mime-mail-parser/php-mime-mail-parser#112]
Why do you expect to get noname attachments for text and html part of [m0015](https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/8015cfb76b8bcd0c38c658231235863656dc43e8/tests/mails/m0015)?
[expected attachments](https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/8015cfb76b8bcd0c38c658231235863656dc43e8/tests/ParserTest.php#L558-L578)

I would expect an empty array for `getAttachments()`..

**Comment by eXorus** [comment]
Good question it's strange and maybe you are right in this case you don"t want to have attachment

Sometimes it's good to have the choice like here:
https://github.com/php-mime-mail-parser/php-mime-mail-parser/issues/43

I found also this
https://github.com/php-mime-mail-parser/php-mime-mail-parser/pull/16

**Comment by gharlan** [comment]
I agree to #43, I also need inline images etc in `getAttachments`.

But I think that `getAttachments` should not contain the parts that are treated as main text or html part.
So a part should be either a main text/html part or an attachment, never both.

**Comment by gharlan** [comment]
I also agree to #16 (`getMessageBody`), but I would change `getAttachments`.
