### ISSUE TITLE
[Question] What does it parse ?

### ISSUE THREAD

**Issue by johndodev** [php-mime-mail-parser/php-mime-mail-parser#113]
Hey,

I may have not understand well what does this library parse.

I installed it and try to parse the source of an e-mail, "view source" on gmail (I guess, I have it in french, "afficher l'original)", like

```
MIME-Version: 1.0
Received: by 10.202.171.204 with HTTP; Tue, 27 Sep 2016 06:14:19 -0700 (PDT)
Date: Tue, 27 Sep 2016 15:14:19 +0200
Delivered-To: [...]
[...]
```

And parsing that isn't working. I can try another library but I woul'd like to be sure this one is not the good one. If I configure postfix to pipe emails to a script, isn't this format I will get ?

**Comment by johndodev** [comment]
Hm, nevermind, it's okay :p

**Comment by eXorus** [comment]
It's okay because you used another library or it's okay because you found the solution ? if it's not clear in the readme maybe we can improve it.

**Comment by johndodev** [comment]
I found the solution, I was doing shit with postman, it was line break issue. It's working !
