### ISSUE TITLE
Protect Parser.getEmbeddedData() from non-unique content-id's

### ISSUE THREAD

**Issue by MonkeyMaster** [php-mime-mail-parser/php-mime-mail-parser#115]
Could you please add break in foreach? I know such emails are invalid but it happens sometimes

**Comment by eXorus** [comment]
Could you explain where I need to put a break ? and do you have an example of file that not working to added to the test ?

**Comment by MonkeyMaster** [comment]
When email has attachments with the same content-id, for example:
```
Content-Type: image/gif; name="oneworld.gif"
Content-Disposition: inline; filename="oneworld.gif"
Content-ID: <oneworld>
```
```
Content-Type: image/gif; name="oneworld.gif"
Content-Disposition: inline; filename="oneworld.gif"
Content-ID: <oneworld>
```
$parser->getMessageBody('htmlEmbedded') outputs broken images:
```
<img src="data:image/gif;base64,R0lGODl ... YegUEAA7
image/gif;base64,R0lGODl ...YegUEAA7">
```

**Comment by eXorus** [comment]
Ok I understand good point.

You can send a PR or I will do it some day.

Thanks
