### ISSUE TITLE
Need to supress iconv() warnings

### ISSUE THREAD

**Issue by MonkeyMaster** [php-mime-mail-parser/php-mime-mail-parser#116]
Having PHP in strict mode sometimes we get whole application fault due to iconv() warning:
"iconv(): Detected an illegal character in input string" in Charset.php:321
The workaround is to add //IGNORE option:
```php
iconv($this->getCharsetAlias($charset), 'UTF-8//TRANSLIT//IGNORE', $encodedString);

**Comment by eXorus** [comment]
Could you send an email that failed ?

**Comment by MonkeyMaster** [comment]
Mail is commercial I can't share it

**Comment by eXorus** [comment]
you can change some personal information but keep the structure

**Comment by MonkeyMaster** [comment]
I removed attachment but still can only send it directly to you

**Comment by eXorus** [comment]
I don't understand why ?

**Comment by MonkeyMaster** [comment]
Email still contains personal information and it's encoded - I can't edit it easily

**Comment by MonkeyMaster** [comment]
I was able to remove all personal data still keeping iconv() warning
[test.zip](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/505417/test.zip)

**Comment by eXorus** [comment]
Thanks it's reproduced. 

The issue is in the subject field.

**Comment by eXorus** [comment]
Sorry your solution doesn't work the IGNORE work sometimes but not always

https://travis-ci.org/php-mime-mail-parser/php-mime-mail-parser/builds/165840242

https://travis-ci.org/php-mime-mail-parser/php-mime-mail-parser/builds/165853192

**Comment by MonkeyMaster** [comment]
We use this fix in production for 2 weeks and there was no iconv warnings since then.
php 5.6

**Comment by eXorus** [comment]
Same for me on 5.6.11 but not working for example on 5.6.5 like travis has

**Comment by eXorus** [comment]
Anyway I fixed it in 2.5.0 and I test it only in PHP7

**Comment by MonkeyMaster** [comment]
I got another warning: "iconv(): Detected an incomplete multibyte character in input string".
//IGNORE doesn't help in this case. I prepended iconv() with @, looks like it's the only way.
```
Subject:
 =?GB2312?B?zeLDs8jL1LG1xMD7xvejrMO/zOyw79b6xPrL0cv3xPqy+sa30NDStbXEyc/N?=
 =?GB2312?B?8snP087Ev7Hqv827p9fK1LSjoQ==?=
```

**Comment by eXorus** [comment]
I don't like this @
Could you open another issue ?

I would like to add mb_convert_encoding() #49 
to replace iconv
