### ISSUE TITLE
ErrorException in Parser.php line 398: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by vtreanor** [php-mime-mail-parser/php-mime-mail-parser#118]
The offending line is
foreach ($this->parts as $part) 
**$this->parts is null and foreach won't accept this.**

everything works well until I add the line:
$Parser->saveAttachments($attachmentPath);
$attachmentPath is a perfectly valid and tested path with correct permissions.

The email is any email even plain text.

**Comment by eXorus** [comment]
Hello,

Could you send an example of the email parsed because if there is no parts it's impossible to have emails.

Maybe it's email without body and only subject ?

**Comment by vtreanor** [comment]
Hi Vincent,
here are some emails attached, take your pick.

And just in case I'm doing something stupid, here is the full function. The
saeAttachments line is commented out to prevent crashes

    public function download(){
        $s3 = new Aws\S3\S3Client([
            'profile' => 'default',
            'version' => 'latest',
            'region'  => 'us-east-1',
        ]);

        $result = $s3->listObjectsV2([
           'Bucket' => 'email.eir-web.com',
        ]);

        $mailPath = config('mySettings.mailStore');
        $attachmentPath = config('mySettings.attachmentStore');

        $Parser = new Parser();
        foreach ($result['Contents'] as $file){
            $fileName = $file['Key'];
            $rawEmail = $s3->getObject([
               'Key' =>  $fileName,
                'Bucket' => 'email.eir-web.com',
            ]);
            $h = fopen($mailPath.$fileName,'w');

            fwrite($h,$rawEmail['Body']);
            fclose($h);

            $attachmentList = null;
//          $Parser->saveAttachments($attachmentPath);

            $Parser->setText($rawEmail['Body']);

            $dt = date_parse($Parser->getHeaders()['date']);

            $theDate =
getMonthByName($dt['month']).'-'.$dt['day'].'-'. $dt['year'];
            $email= [
                'fileName' => $fileName,
                'date' => $theDate,
                'to' => $Parser->getHeader('to'),
                'addressTo' => $Parser->getAddresses('to'),
                'from' => $Parser->getAddresses('from')[0]['address'],
                'addressFrom' => $Parser->getAddresses('from'),
                'subject' => $Parser->getHeader('subject'),
                'body' => str_replace("\r\n","<br>", $Parser->getMessageBody()),
//              'attachments' => $attachmentList,
                ];
            $emailList[] = $email;
    }
    return view('mail.mail',['emailList' => $emailList]);
    }
}

**Comment by vtreanor** [comment]
Vincent,

prototype email app here:

http://eir-web.com/mail/download

regards,

Vincent Treanor

**Comment by eXorus** [comment]
Ok I understand you can't use, it will never work:
```
$Parser = new Parser();
$Parser->saveAttachments($attachmentPath);
```

According to the doc, you need to use with $path the path of you raw email:
```
$Parser = new Parser();
$Parser->setPath($path);
$Parser->saveAttachments($attachmentPath);
```

It's necessary to use one of the 3 methods setPath, setStream and setText before to use the saveAttachments or any other methods.

**Comment by vtreanor** [comment]
Ok,
you have given me the needed clue.
I had


$Parser->saveAttachments($attachmentPath);
$Parser->setText($rawEmail['Body']);

instead of


$Parser->setText($rawEmail['Body']);
$Parser->saveAttachments($attachmentPath);


Blindingly obvious really!

Thanks for your help and apologies for the distraction.

Regards

**Comment by eXorus** [comment]
You're welcome
