### ISSUE TITLE
Filename collision with attachments

### ISSUE THREAD

**Issue by daFool** [php-mime-mail-parser/php-mime-mail-parser#119]
I have an email that has two attachments. Those two attachments are emails with attachments. Those attachments are identically named. 

saveAttachments will only save one copy of the file (or perhaps it saves them twice but overwrites the first one) but getAttachments will return each original attachment and getFilename will point twice to the same physical file on the disk.  Tested with 2.5.1

**Comment by eXorus** [comment]
Hello,

Could you send an example email to reproduce this bug ?

Thanks

**Comment by daFool** [comment]
I can't give you the original email as it contains data that is private but I will try to construct a matching email. It will take a bit of time but I expect to have it tomorrow.

**Comment by daFool** [comment]
Took me a moment to figure out what the users must have done (https://www.bettercloud.com/monitor/the-academy/how-to-attach-an-email-to-another-email-in-outlook/) to generate the email. That Academy video also warns that results might get messy if the recipient doesn't have Outlook but users always ignore these warnings. Hers and his Outlooks are older ones than what I have access to but attached samples are close enough to emit the same behaviour. I also attached sample script.  

This is the output I get (and it was first tested with 2.4.1 not 2.5.1 which was later upgraded to 2.5.0):
$ php mailParseDemo.php 
Original email: examples/20161011_1.txt
There are 8 attachments
Filename : noname1 Filetype : message/rfc822
Filename : sample.jpg Filetype : image/jpeg
Filename : Tallentamaton asiakirja 1.pdf Filetype : application/pdf
Filename : Tallentamaton asiakirja 2.pdf Filetype : application/pdf
Filename : noname2 Filetype : message/rfc822
Filename : sample.jpg Filetype : image/jpeg
Filename : Tallentamaton asiakirja 1.pdf Filetype : application/pdf
Filename : Tallentamaton asiakirja 2.pdf Filetype : application/pdf
There are 5 saved files
noname1
noname2
sample.jpg
Tallentamaton asiakirja 1.pdf
Tallentamaton asiakirja 2.pdf
Sample one: [20161011_1.txt](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/521100/20161011_1.txt)
Sample two: [20161011_2.txt](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/521099/20161011_2.txt)
Code:
`
$basepath=__DIR__;
define("TMP", "/data/tmp/demo/");
require("$basepath/vendor/autoload.php");

$path="examples/20161011_1.txt";
$Parser = new PhpMimeMailParser\Parser();
$Parser->setText(file_get_contents($path));
$Parser->saveAttachments(TMP);

$attachments = $Parser->getAttachments();
$lkm = count($attachments);
echo "Original email: $path\n";
if ($lkm > 0) {
    echo "There are {$lkm} attachments\n";
    foreach ($attachments as $attachment) {
        echo 'Filename : '.$attachment->getFilename().' '; // logo.jpg
        echo 'Filetype : '.$attachment->getContentType()."\n"; // image/jpeg
    }
    $c = "ls ".TMP;
    $flkm = `$c |wc -l`;
    $flkm = trim($flkm);
    echo "There are {$flkm} saved files\n";
    echo `$c`;
}
?>
`

**Comment by eXorus** [comment]
Release 2.8.0 will fix this issue.
