### ISSUE TITLE
iconv with UTF-8//TRANSLIT//IGNORE still produces "illegal character" error

### ISSUE THREAD

**Issue by MonkeyMaster** [php-mime-mail-parser/php-mime-mail-parser#120]
Example:

```
Subject:
 =?GB2312?B?zeLDs8jL1LG1xMD7xvejrMO/zOyw79b6xPrL0cv3xPqy+sa30NDStbXEyc/N?=
 =?GB2312?B?8snP087Ev7Hqv827p9fK1LSjoQ==?=
```

The only solution I found is to prepend iconv() with "@".
http://stackoverflow.com/questions/9375909/iconv-utf-8-ignore-still-produces-illegal-character-error

Maybe mb_convert_encoding() is better, I didn't test it.

**Comment by eXorus** [comment]
#137

**Comment by arduanov** [comment]
Content in GBK encoding,  you can modify EmailCharset for this

        'gb2312' => 'GBK',

it's worked for me

**Comment by eXorus** [comment]
@arduanov Thanks but the test failed with GBK also :(
#152

**Comment by eXorus** [comment]
@arduanov are you sure about this solution because it's not working for me on #152

**Comment by odknt** [comment]
It's wrong that subject has been separated after base64 encoding.
Non-ASCII characters must be encoded after split according to [RFC 2047](https://tools.ietf.org/html/rfc2047#section-5).

```php
// base64 encoded:
// zeLDs8jL1LG1xMD7xvejrMO/zOyw79b6xPrL0cv3xPqy+sa30NDStbXEyc/N8snP087Ev7Hqv827p9fK1LSjoQ==
$subject = '外贸人员的利器，每天帮助您搜索您产品行业的上万上游目标客户资源！';

// get the correctly encoded subject
echo iconv_mime_encode('Subject', $input, ['output-charset' => 'gb2312']) . PHP_EOL;

//Subject: =?gb2312?B?zeLDs8jL1LG1xMD7xvejrMO/zOyw79b6xPrL0cv3xPqy+g==?=
// =?gb2312?B?xrfQ0NK1tcTJz83yyc/TzsS/seq/zbun18rUtKOh?=
```

**Comment by eXorus** [comment]
@odknt Sorry I didn't understand what is wrong in the subject.

For you, the subject of @MonkeyMaster is wrong encoded ? We can try to be more compliance with RFC but the reality in the email is that RFC is not always respected by the client.

**Comment by odknt** [comment]
It may be can not be well explained due to not speak English well.

Example was split `zeLDs8jL1LG1xMD7xvejrMO/zOyw79b6xPrL0cv3xPqy+sa30NDStbXEyc/N` and `8snP087Ev7Hqv827p9fK1LSjoQ==` from base64-encoded string. That's dividing multibyte string in the middle. (the error of #152 mean it) 

If you want to be decode, join second MIME-encoded string trimmed `=?gb2312?B?`.
