### ISSUE TITLE
getting the 'for' email address of a forwarded email

### ISSUE THREAD

**Issue by iateadonut** [php-mime-mail-parser/php-mime-mail-parser#121]
I'm using mime-parser to parse an email.

The email is **forwarded** to test@domain.com.
from = 'me@mydomain.com'  (getHeaders('from'))
to = 'thiswillforward@test.com'  (getHeaders('to'))

The entire line within the email itself that shows the recipient is:
for test@domain.com; Tue, 11 Oct 2016 21:12:29 -0400

How can i get the string 'test@domain.com'?

**Comment by eXorus** [comment]
Hello,

Sorry I don't know. Did you try getHeaders('for') or getHeaders() and find what you want in the array ?

**Comment by iateadonut** [comment]
I have now.  It did not work.

The problem is the way outlook auto-forwards emails.  I don't know if this occurs with any other program.

I wrote a simple method to find it:
```
class Parser2 extends PhpMimeMailParser\Parser
{

    public function getFor() {

        preg_match("/\tfor\s(.*)\;/", $this->data, $for );
        if ( isset( $for[1] ) ) {
            return $for[1];
        }
        return $this->getAddresses('to');

    }

}
```

I'm going to use this for now and will update you on errors/edits as it gets used in live production.

**Comment by eXorus** [comment]
If it's like this email: https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/master/tests/mails/m0001

```
Received: by mail-ie0-f173.google.com with SMTP id k13so5038157iea.32
for <name@company2.com>; Sun, 16 Jun 2013 08:50:12 -0700 (PDT)
```

You can get "Received" and after use your regex

**Comment by heffneil** [comment]
I added the <for and > in the regular expression and then from that result I pulled the email address out.  That way I know I am getting the For address.  I don't know if this helps. 

$v_For = "";

preg_match("/for <[\._a-zA-Z0-9-]+@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,})$/i", $stringHeaders, $matches);
if(!empty($matches)){
	preg_match("/[\._a-zA-Z0-9-]+@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,})$/i", $matches[0], $v_For);
}
