### ISSUE TITLE
detect thread

### ISSUE THREAD

**Issue by iateadonut** [php-mime-mail-parser/php-mime-mail-parser#122]
How can we detect if two or more emails are part of a single thread?

And then grabbing only the pertinent section that is new would be good.

New messages within a thread seem to start with:
-------- Original message --------
or
On Oct 15, 2016, at 11:40 AM, emailfrom <email@gmail.com> wrote:

Some emails have a line immediately following subject, "Thread-Topic":
Subject: Re: Some subject
Thread-Topic: Some subject

**Comment by eXorus** [comment]
There is no specification for thread.
All depends of the client so you can try to parse the body but it will be different for each provider.
