### ISSUE TITLE
method to free resources

### ISSUE THREAD

**Issue by MonkeyMaster** [php-mime-mail-parser/php-mime-mail-parser#123]
After setPath() file becomes locked and it's not possible to rename or unlink it before Parser destructor is called. However in php it's not possible to destroy any object immediately, even with unset(). So now the only way to unlock the file is to call destructor explicitly, it's not recommended though.
It would be good to have a method similar to destructor to manually free resources when needed.

**Comment by eXorus** [comment]
I understand something like $Parser->destruct() ? destruct() will call __destrut() I'm not sure it a good design.

Why do you want to call destruct method, PHP did it at the end of the script.

**Comment by MonkeyMaster** [comment]
It just like fopen/fclose. Now you have only the first part.
I described why I need it - to move or unlink the file after parsing. Now it's not possible since file is locked.

**Comment by eXorus** [comment]
I was not able to reproduce the issue anymore, both unlink or rename works after setPath.

  ```php
  public function testFreeResources()
    {
        $file = __DIR__ . '/mails/m0025';
        $Parser = new Parser();
        $Parser->setPath($file);

        //unlink($file);
        //rename($file, __DIR__ . '/mails/m0025_new');

        $attachments = $Parser->getAttachments();
        $this->assertCount(3, $attachments);

    }
```
