### ISSUE TITLE
mailparse_rfc822_parse_addresses() warning

### ISSUE THREAD

**Issue by MonkeyMaster** [php-mime-mail-parser/php-mime-mail-parser#124]
The following header `From: =?UTF-8?B?QW51c2NoID0p?=` produces warning
`input is not rfc822 compliant: token not valid in ground state ( ... /vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php:384)`
in `Parser.getAddresses('from')` and kills application in php strict mode.
Quick solution is @

**Comment by eXorus** [comment]
I don't like @ 
and how do you receive "Anusch =)" there is no email adress in.

**Comment by MonkeyMaster** [comment]
I removed the email - the warning is caused by the name and email doesn't matter.

**Comment by MonkeyMaster** [comment]
Email addresses with double quotes in name are also parsed incorrectly.
I found the solution: to feed mailparse_rfc822_parse_addresses() with raw headers and then decode names
```php
    public function getAddresses($name)
    {
        $value = $this->getRawHeader($name);
		$addresses = mailparse_rfc822_parse_addresses($value);
		foreach ($addresses as $i => $item)
			$addresses[$i]['display'] = $this->decodeHeader($item['display']);
		return $addresses;
	}
```

**Comment by ChaudEf** [comment]
@MonkeyMaster 
Thank you, it's ecxellent!!

**Comment by eXorus** [comment]
@MonkeyMaster could you do a PR for that ?

**Comment by eXorus** [comment]
Do you reproduce this bug because in the last version 2.9.5 I can't reproduce it.


For 
`From: =?UTF-8?B?0KTQk9Cj0J8gItCh0LjQsdCd0JjQkCDQuNC8LtChLtCQLtCn0LDQv9C70Ys=?= =?UTF-8?B?0LPQuNC90LAiIg==?= <user@domain.ru>`

the $Parser->getHeader('from'); 

return the good value
`ФГУП "СибНИА им.С.А.Чаплыгина"" <user@domain.ru>`

The exact same value that your method.

I tested my method:
```php
    public function getAddresses($name)
    {
        $value = $this->getHeader($name);

        return mailparse_rfc822_parse_addresses($value);
    }
```

and yours:
```php
    public function getAddresses($name)
    {
        $value = $this->getRawHeader($name);
        $value = (is_array($value)) ? $value[0] : $value;
        $addresses = mailparse_rfc822_parse_addresses($value);
        foreach ($addresses as $i => $item)
            $addresses[$i]['display'] = $this->decodeHeader($item['display']);
        return $addresses;
    }
```

**Comment by MonkeyMaster** [comment]
You should check `$parser->getAddresses('from')` insteadof `$parser->getHeader('from')` !
Your method returns wrong address field:
```php
[
	[
		'display' => 'ФГУП СибНИА им.С.А.Чаплыгина "',
		'address' => 'ФГУП "СибНИА им.С.А.Чаплыгина" """',
		'is_group' => false,
	],
]
```
and mine is fine:
```php
[
	[
		'display' => 'ФГУП "СибНИА им.С.А.Чаплыгина""',
		'address' => 'user@domain.ru',
		'is_group' => false,
	],
]
```

**Comment by eXorus** [comment]
You're right. I will fix it.

**Comment by eXorus** [comment]
Thanks @MonkeyMaster 
2.9.6 fix this issue.
