### ISSUE TITLE
Cannot retrieve message body

### ISSUE THREAD

**Issue by bilrousseau** [php-mime-mail-parser/php-mime-mail-parser#130]
I have a mail server on an Ubuntu VM and I'm trying to use your parser to retrieve mail headers info.

What I'm struggling with is that none of the `getMessageBody` functions seem to work. `'html'`, `'text'` or `'htmlEmbedded'` return `false`.

I've tried to modify `getMessageBody() `code to add `'multipart' `type, but that retrieves me the whole mail content. And I don't want to re-parse the lot again.

My mail content looks like this :
`From bill.rousseau@xxx.fr  Thu Nov 24 11:00:35 2016
Return-Path: <bill.rousseau@xxx.fr>
X-Original-To: xxx@xxx.fr
Delivered-To: phpmailtomysql@xxx.fr
Received: from mail-wj0-f181.google.com (mail-wj0-f181.google.com [209.85.210.181])
	by xxx.fr (Postfix) with ESMTPS id 5999C467EE
	for <test.postfix@xxx.fr>; Thu, 24 Nov 2016 11:00:35 +0100 (CET)
Received: by mail-wj0-f181.google.com with SMTP id xy5so29453380wjc.0
        for <test.postfix@xxx.fr>; Thu, 24 Nov 2016 02:00:35 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=xxx.fr; s=google;
        h=from:subject:message-id:date:to:mime-version;
        bh=4kDbNWhPjenM60PPAGdFRXGkDWyvxiN+joJBfzIW1c0=;
        b=G9LDv96ZeangRhbWVV8d/LKyTpSLVVsKllygS4R/skGJVbZ8UkY1MvReELGrYHcZtF
         I3fsqiGiZBKSiImSd897w7yu51eoUekLTigUd6XyH1k0mxjFHMFv1T0FlABla5J8sn7J
         6pFyOeL0O8JiX7g9l9RFiLxwQAJ8MR/PG0D6g=
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20130820;
        h=x-gm-message-state:from:subject:message-id:date:to:mime-version;
        bh=4kDbNWhPjenM60PPAGdFRXGkDWyvxiN+joJBfzIW1c0=;
        b=CvL/KbXMDsF7OkT70PUo1pqeBlXojcfu8sb5aUTmDVzN3t7V7dMa+VjQntltaOiJ/O
         KH7w3l0zsgun2Zb0vtx1o6rKLLA9dci1Mjxkq+WDsQjD2bgT+WFbtapuN9rvWIplV4xw
         FvC3Q9kD8nR2n56Kq/v/we3+jSMEAEQ5esPEwsnY75YezPxxLMtwlo7EyjPTQ1m290+H
         v+9JRdd/ajxOeT/7sXkZRbu2kxrFrVJWm0rsLXkE+Hejx8zOYP8In3h36aJX5h/nfcSN
         4YkuYOs5drucNCo8dHj0TBjXqeVeMlXdIw/8gnZ0VLVwGhsy0NRhasMNgWlaJ5tkYq2Q
         U+zA==
X-Gm-Message-State: AKaTC00T5YMK4REuSFyxLOsNFuMIqwtwUOSbzEwkqluRiNXpX/EQS0yD4AccqCkp/xdUog==
X-Received: by 10.194.127.104 with SMTP id nf8mr1440169wjb.39.1479981634802;
        Thu, 24 Nov 2016 02:00:34 -0800 (PST)
Received: from [192.168.1.4] (gch75-8-88-190-242-130.fbxo.proxad.net. [88.190.242.130])
        by smtp.gmail.com with ESMTPSA id f67sm7350639wmd.13.2016.11.24.02.00.33
        for <test.postfix@xxx.fr>
        (version=TLS1 cipher=ECDHE-RSA-AES128-SHA bits=128/128);
        Thu, 24 Nov 2016 02:00:34 -0800 (PST)
From: Bill Rousseau <bill.rousseau@xxx.fr>
Content-Type: multipart/alternative; boundary=_Apple-Mail=_F6DF7926-5472-4D55-BE7D-711D66DE33F6_
Subject: Premier test
Message-Id: <682C3CE4-D26E-4DE8-B401-52B3DE53A94E@xxx.fr>
Date: Thu, 24 Nov 2016 11:00:34 +0100
To: test.postfix@xxx.fr
Mime-Version: 1.0 (Mac OS X Mail 9.3 \(3124\))
X-Mailer: Apple Mail (2.3124)

--Apple-Mail=_F6DF7926-5472-4D55-BE7D-711D66DE33F6
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain;
	charset=utf-8

Body du premier test.

--Apple-Mail=_F6DF7926-5472-4D55-BE7D-711D66DE33F6
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html;
	charset=utf-8

<html><head><meta http-equiv=3D_Content-Type_ content=3D_text/html =
charset=3Dutf-8_></head><body style=3D_word-wrap: break-word; =
-webkit-nbsp-mode: space; -webkit-line-break: after-white-space;_ =
class=3D__>Body du premier test.<div class=3D__><br class=3D__><div =
class=3D__>
<div style=3D_color: rgb(0, 0, 0); letter-spacing: normal; orphans: =
auto; text-align: start; text-indent: 0px; text-transform: none; =
white-space: normal; widows: auto; word-spacing: 0px; =
-webkit-text-stroke-width: 0px; word-wrap: break-word; =
-webkit-nbsp-mode: space; -webkit-line-break: after-white-space;_ =
class=3D__><div style=3D_color: rgb(0, 0, 0); letter-spacing: normal; =
orphans: auto; text-align: start; text-indent: 0px; text-transform: =
none; white-space: normal; widows: auto; word-spacing: 0px; =
-webkit-text-stroke-width: 0px; word-wrap: break-word; =
-webkit-nbsp-mode: space; -webkit-line-break: after-white-space;_ =
class=3D__><div style=3D_color: rgb(0, 0, 0); letter-spacing: normal; =
orphans: auto; text-align: start; text-indent: 0px; text-transform: =
none; white-space: normal; widows: auto; word-spacing: 0px; =
-webkit-text-stroke-width: 0px; word-wrap: break-word; =
-webkit-nbsp-mode: space; -webkit-line-break: after-white-space;_ =
class=3D__><div class=3D__><span =
id=3D_docs-internal-guid-e7dc772c-508a-a874-fd53-772a2cbf4409_ =
class=3D__><div style=3D_line-height: 1.2; margin-top: 0pt; =
margin-bottom: 0pt;_ class=3D__><span =
id=3D_docs-internal-guid-e7dc772c-54dd-9d5c-b0d2-2ff3eb89420c_ =
class=3D__><div style=3D_line-height: 1.2; margin-top: 0pt; =
margin-bottom: 0pt;_ class=3D__><a href=3D_http://xxx.fr_ =
style=3D_text-decoration: none;_ class=3D__><span style=3D_font-size: =
9.333333333333332px; font-family: 'Times New Roman'; color: rgb(17, 85, =
204); font-variant-ligatures: normal; font-variant-position: normal; =
font-variant-numeric: normal; font-variant-alternates: normal; =
font-variant-east-asian: normal; text-decoration: underline; =
vertical-align: baseline; white-space: pre-wrap;_ class=3D__><img =
src=3D_https://lh3.googleusercontent.com/IoT7Yw6gY6PYNcYYOOHh3L55ct5GJyCts=
vfqAXwTuAdcB32YT95Owwok4hKfMXXnGenMuJklXqH8R_NHuEbJL_-jS200fxDL7tn-UhQy_1i=
1-j-IRVDsU3qXR_GeWfW4U6Ah2CN0_ width=3D_128_ height=3D_58_ alt=3D_xxx.fr_ =
style=3D_border: none; transform: rotate(0rad);_ =
class=3D__></span></a></div><div style=3D_line-height: 1.32; margin-top: =
0pt; margin-bottom: 0pt;_ class=3D__><span style=3D_font-size: =
10.666666666666666px; font-family: 'Times New Roman'; color: rgb(10, 61, =
151); font-weight: 700; font-variant-ligatures: normal; =
font-variant-position: normal; font-variant-numeric: normal; =
font-variant-alternates: normal; font-variant-east-asian: normal; =
vertical-align: baseline; white-space: pre-wrap;_ class=3D__>Bill =
Rousseau</span></div><div style=3D_line-height: 1.32; margin-top: 0pt; =
margin-bottom: 0pt;_ class=3D__><span style=3D_font-size: =
9.333333333333332px; font-family: 'Times New Roman'; color: rgb(10, 61, =
151); font-variant-ligatures: normal; font-variant-position: normal; =
font-variant-numeric: normal; font-variant-alternates: normal; =
font-variant-east-asian: normal; vertical-align: baseline; white-space: =
pre-wrap;_ class=3D__>11 rue de T=C3=A9h=C3=A9ran - 75008 =
Paris</span></div><div style=3D_line-height: 1.32; margin-top: 0pt; =
margin-bottom: 0pt;_ class=3D__><span style=3D_font-size: =
9.333333333333332px; font-family: 'Times New Roman'; color: rgb(10, 61, =
151); font-variant-ligatures: normal; font-variant-position: normal; =
font-variant-numeric: normal; font-variant-alternates: normal; =
font-variant-east-asian: normal; vertical-align: baseline; white-space: =
pre-wrap;_ class=3D__>T=C3=A9l: 01.85.092.092</span></div><div =
style=3D_line-height: 1.32; margin-top: 0pt; margin-bottom: 0pt;_ =
class=3D__><span style=3D_font-size: 9.333333333333332px; font-family: =
'Times New Roman'; color: rgb(10, 61, 151); font-variant-ligatures: =
normal; font-variant-position: normal; font-variant-numeric: normal; =
font-variant-alternates: normal; font-variant-east-asian: normal; =
vertical-align: baseline; white-space: pre-wrap;_ =
class=3D__>bill.rousseau</span><span style=3D_text-decoration: none; =
font-size: 9.333333333333332px; font-family: 'Times New Roman'; color: =
rgb(10, 61, 151); font-variant-ligatures: normal; font-variant-position: =
normal; font-variant-numeric: normal; font-variant-alternates: normal; =
font-variant-east-asian: normal; vertical-align: baseline; white-space: =
pre-wrap;_ class=3D__><a href=3D_mailto:bill.rousseau@xxx.fr_ =
style=3D_text-decoration: none;_ class=3D__></a></span></div><div =
class=3D__><br class=3D__></div></span></div></span></div></div><br =
class=3D_Apple-interchange-newline_></div><br =
class=3D_Apple-interchange-newline_></div><br =
class=3D_Apple-interchange-newline_><br =
class=3D_Apple-interchange-newline_>
</div>
<br class=3D__></div></body></html>=

--Apple-Mail=_F6DF7926-5472-4D55-BE7D-711D66DE33F6--
`

Am I missing something?

**Comment by eXorus** [comment]
Hello,

There is no issue the mail is not correct so mailparse doesn't understand it.

In the header the boundary is "_Apple-Mail=_F6DF7926-5472-4D55-BE7D-711D66DE33F6_" and in anothers parts the boundary is "Apple-Mail=_F6DF7926-5472-4D55-BE7D-711D66DE33F6".

If you change the boundary it will  work with this mail:
```

From bill.rousseau@xxx.fr  Thu Nov 24 11:00:35 2016
Return-Path: <bill.rousseau@xxx.fr>
X-Original-To: xxx@xxx.fr
Delivered-To: phpmailtomysql@xxx.fr
Received: from mail-wj0-f181.google.com (mail-wj0-f181.google.com [209.85.210.181])
    by xxx.fr (Postfix) with ESMTPS id 5999C467EE
    for <test.postfix@xxx.fr>; Thu, 24 Nov 2016 11:00:35 +0100 (CET)
Received: by mail-wj0-f181.google.com with SMTP id xy5so29453380wjc.0
        for <test.postfix@xxx.fr>; Thu, 24 Nov 2016 02:00:35 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=xxx.fr; s=google;
        h=from:subject:message-id:date:to:mime-version;
        bh=4kDbNWhPjenM60PPAGdFRXGkDWyvxiN+joJBfzIW1c0=;
        b=G9LDv96ZeangRhbWVV8d/LKyTpSLVVsKllygS4R/skGJVbZ8UkY1MvReELGrYHcZtF
         I3fsqiGiZBKSiImSd897w7yu51eoUekLTigUd6XyH1k0mxjFHMFv1T0FlABla5J8sn7J
         6pFyOeL0O8JiX7g9l9RFiLxwQAJ8MR/PG0D6g=
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20130820;
        h=x-gm-message-state:from:subject:message-id:date:to:mime-version;
        bh=4kDbNWhPjenM60PPAGdFRXGkDWyvxiN+joJBfzIW1c0=;
        b=CvL/KbXMDsF7OkT70PUo1pqeBlXojcfu8sb5aUTmDVzN3t7V7dMa+VjQntltaOiJ/O
         KH7w3l0zsgun2Zb0vtx1o6rKLLA9dci1Mjxkq+WDsQjD2bgT+WFbtapuN9rvWIplV4xw
         FvC3Q9kD8nR2n56Kq/v/we3+jSMEAEQ5esPEwsnY75YezPxxLMtwlo7EyjPTQ1m290+H
         v+9JRdd/ajxOeT/7sXkZRbu2kxrFrVJWm0rsLXkE+Hejx8zOYP8In3h36aJX5h/nfcSN
         4YkuYOs5drucNCo8dHj0TBjXqeVeMlXdIw/8gnZ0VLVwGhsy0NRhasMNgWlaJ5tkYq2Q
         U+zA==
X-Gm-Message-State: AKaTC00T5YMK4REuSFyxLOsNFuMIqwtwUOSbzEwkqluRiNXpX/EQS0yD4AccqCkp/xdUog==
X-Received: by 10.194.127.104 with SMTP id nf8mr1440169wjb.39.1479981634802;
        Thu, 24 Nov 2016 02:00:34 -0800 (PST)
Received: from [192.168.1.4] (gch75-8-88-190-242-130.fbxo.proxad.net. [88.190.242.130])
        by smtp.gmail.com with ESMTPSA id f67sm7350639wmd.13.2016.11.24.02.00.33
        for <test.postfix@xxx.fr>
        (version=TLS1 cipher=ECDHE-RSA-AES128-SHA bits=128/128);
        Thu, 24 Nov 2016 02:00:34 -0800 (PST)
From: Bill Rousseau <bill.rousseau@xxx.fr>
Content-Type: multipart/alternative; boundary=Apple-Mail=_F6DF7926-5472-4D55-BE7D-711D66DE33F6
Subject: Premier test
Message-Id: <682C3CE4-D26E-4DE8-B401-52B3DE53A94E@xxx.fr>
Date: Thu, 24 Nov 2016 11:00:34 +0100
To: test.postfix@xxx.fr
Mime-Version: 1.0 (Mac OS X Mail 9.3 \(3124\))
X-Mailer: Apple Mail (2.3124)


--Apple-Mail=_F6DF7926-5472-4D55-BE7D-711D66DE33F6
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain;
    charset=utf-8

Body du premier test.


--Apple-Mail=_F6DF7926-5472-4D55-BE7D-711D66DE33F6
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html;
    charset=utf-8

<html><head><meta http-equiv=3D_Content-Type_ content=3D_text/html =
charset=3Dutf-8_></head><body style=3D_word-wrap: break-word; =
-webkit-nbsp-mode: space; -webkit-line-break: after-white-space;_ =
class=3D__>Body du premier test.<div class=3D__><br class=3D__><div =
class=3D__>
<div style=3D_color: rgb(0, 0, 0); letter-spacing: normal; orphans: =
auto; text-align: start; text-indent: 0px; text-transform: none; =
white-space: normal; widows: auto; word-spacing: 0px; =
-webkit-text-stroke-width: 0px; word-wrap: break-word; =
-webkit-nbsp-mode: space; -webkit-line-break: after-white-space;_ =
class=3D__><div style=3D_color: rgb(0, 0, 0); letter-spacing: normal; =
orphans: auto; text-align: start; text-indent: 0px; text-transform: =
none; white-space: normal; widows: auto; word-spacing: 0px; =
-webkit-text-stroke-width: 0px; word-wrap: break-word; =
-webkit-nbsp-mode: space; -webkit-line-break: after-white-space;_ =
class=3D__><div style=3D_color: rgb(0, 0, 0); letter-spacing: normal; =
orphans: auto; text-align: start; text-indent: 0px; text-transform: =
none; white-space: normal; widows: auto; word-spacing: 0px; =
-webkit-text-stroke-width: 0px; word-wrap: break-word; =
-webkit-nbsp-mode: space; -webkit-line-break: after-white-space;_ =
class=3D__><div class=3D__><span =
id=3D_docs-internal-guid-e7dc772c-508a-a874-fd53-772a2cbf4409_ =
class=3D__><div style=3D_line-height: 1.2; margin-top: 0pt; =
margin-bottom: 0pt;_ class=3D__><span =
id=3D_docs-internal-guid-e7dc772c-54dd-9d5c-b0d2-2ff3eb89420c_ =
class=3D__><div style=3D_line-height: 1.2; margin-top: 0pt; =
margin-bottom: 0pt;_ class=3D__><a href=3D_http://xxx.fr_ =
style=3D_text-decoration: none;_ class=3D__><span style=3D_font-size: =
9.333333333333332px; font-family: 'Times New Roman'; color: rgb(17, 85, =
204); font-variant-ligatures: normal; font-variant-position: normal; =
font-variant-numeric: normal; font-variant-alternates: normal; =
font-variant-east-asian: normal; text-decoration: underline; =
vertical-align: baseline; white-space: pre-wrap;_ class=3D__><img =
src=3D_https://lh3.googleusercontent.com/IoT7Yw6gY6PYNcYYOOHh3L55ct5GJyCts=
vfqAXwTuAdcB32YT95Owwok4hKfMXXnGenMuJklXqH8R_NHuEbJL_-jS200fxDL7tn-UhQy_1i=
1-j-IRVDsU3qXR_GeWfW4U6Ah2CN0_ width=3D_128_ height=3D_58_ alt=3D_xxx.fr_ =
style=3D_border: none; transform: rotate(0rad);_ =
class=3D__></span></a></div><div style=3D_line-height: 1.32; margin-top: =
0pt; margin-bottom: 0pt;_ class=3D__><span style=3D_font-size: =
10.666666666666666px; font-family: 'Times New Roman'; color: rgb(10, 61, =
151); font-weight: 700; font-variant-ligatures: normal; =
font-variant-position: normal; font-variant-numeric: normal; =
font-variant-alternates: normal; font-variant-east-asian: normal; =
vertical-align: baseline; white-space: pre-wrap;_ class=3D__>Bill =
Rousseau</span></div><div style=3D_line-height: 1.32; margin-top: 0pt; =
margin-bottom: 0pt;_ class=3D__><span style=3D_font-size: =
9.333333333333332px; font-family: 'Times New Roman'; color: rgb(10, 61, =
151); font-variant-ligatures: normal; font-variant-position: normal; =
font-variant-numeric: normal; font-variant-alternates: normal; =
font-variant-east-asian: normal; vertical-align: baseline; white-space: =
pre-wrap;_ class=3D__>11 rue de T=C3=A9h=C3=A9ran - 75008 =
Paris</span></div><div style=3D_line-height: 1.32; margin-top: 0pt; =
margin-bottom: 0pt;_ class=3D__><span style=3D_font-size: =
9.333333333333332px; font-family: 'Times New Roman'; color: rgb(10, 61, =
151); font-variant-ligatures: normal; font-variant-position: normal; =
font-variant-numeric: normal; font-variant-alternates: normal; =
font-variant-east-asian: normal; vertical-align: baseline; white-space: =
pre-wrap;_ class=3D__>T=C3=A9l: 01.85.092.092</span></div><div =
style=3D_line-height: 1.32; margin-top: 0pt; margin-bottom: 0pt;_ =
class=3D__><span style=3D_font-size: 9.333333333333332px; font-family: =
'Times New Roman'; color: rgb(10, 61, 151); font-variant-ligatures: =
normal; font-variant-position: normal; font-variant-numeric: normal; =
font-variant-alternates: normal; font-variant-east-asian: normal; =
vertical-align: baseline; white-space: pre-wrap;_ =
class=3D__>bill.rousseau</span><span style=3D_text-decoration: none; =
font-size: 9.333333333333332px; font-family: 'Times New Roman'; color: =
rgb(10, 61, 151); font-variant-ligatures: normal; font-variant-position: =
normal; font-variant-numeric: normal; font-variant-alternates: normal; =
font-variant-east-asian: normal; vertical-align: baseline; white-space: =
pre-wrap;_ class=3D__><a href=3D_mailto:bill.rousseau@xxx.fr_ =
style=3D_text-decoration: none;_ class=3D__></a></span></div><div =
class=3D__><br class=3D__></div></span></div></span></div></div><br =
class=3D_Apple-interchange-newline_></div><br =
class=3D_Apple-interchange-newline_></div><br =
class=3D_Apple-interchange-newline_><br =
class=3D_Apple-interchange-newline_>
</div>
<br class=3D__></div></body></html>=

--Apple-Mail=_F6DF7926-5472-4D55-BE7D-711D66DE33F6--

```

**Comment by bilrousseau** [comment]
Thing is that boundary issue is not happening in all mail clients. These spare underscores do not occur on Gmail for example.
(Please note that I have a Postfix server installed on Ubuntu 16.04)

**Comment by eXorus** [comment]
This is a client issue, we need to ask Mail.app for that. The boundary need to be the same in the header and in the body else nobody can parse your email.
