### ISSUE TITLE
Can i read mail from thunderbird indbox file using this library?

### ISSUE THREAD

**Issue by 05bca054** [php-mime-mail-parser/php-mime-mail-parser#132]
Hello,

Awesome raw email parsing library. But my scenario is bit different i have server and on the one pop client is there called Thunderbird now i can able to find location of folder(On server localhost) where his all inbox folder mails were saved. I think it's in raw format.

I am also getting error while reading text file on php 7.0.14 like this

**Warning: fread(): Length parameter must be greater than 0 in /var/www/html/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php on line 286**

So can i read those pop mail using your library?

-Naitik

**Comment by eXorus** [comment]
I don't know, could you post an example to see the format ?
