### ISSUE TITLE
Error when saving attachments with slashes in the name (as a date)

### ISSUE THREAD

**Issue by dlopezlo** [php-mime-mail-parser/php-mime-mail-parser#133]
Hi, 

the following error occurs when trying to save and read attachments with / in the name.

Error:

Command output: PHP Warning:  fopen(/var/spool/filter/attachments/A File with slashes in the name - 01/01/2017.pdf): failed to open stream: No such file or directory in /opt/filter/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php on line 473 PHP Fatal error:  Uncaught exception 'PhpMimeMailParser\Exception' with message 'Could not write attachments. Your directory may be unwritable by PHP.' in /opt/filter/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php:480 Stack trace: #0 /opt/filter/script.php(118): PhpMimeMailParser\Parser->saveAttachments('/var/spool/filt...', Array) #1 {main}   thrown in /opt/filter/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php on line 480)

**Comment by pkwien93** [comment]
because / isn't allowed in Filenames, / is the separator for directories, this is a limitation on your operating system (and currently I don't know any operation system which allows to use / in filenames) ... so you will need to use another character instead of /.

**Comment by xqus** [comment]
This is a problem with php-mime-mail-parser. It should filter the filename before saving. This could in theory allow an attacker to write to any file on the system (depending on the setup).

**Comment by dlopezlo** [comment]
Well, imho,  even if "/" is no not allowed in filenames in some os, the filename is an input controlled by the user and should be filtered somehow because it breakes the flow of the program (we use it in a mail filter). In our filter we did a preg_replace to avoid problems.
