### ISSUE TITLE
I have list of .eml files this plugin fails to parse body text.

### ISSUE THREAD

**Issue by maku220** [php-mime-mail-parser/php-mime-mail-parser#140]
I use this library for my pretty big project where about 30 e-mails a day goes through and use it to parse .eml e-mail file info (subject, from address, body etc), however it fails to parse correctly about 1/5 of e-mail bodies. Are you interested in these emails? If so where can I send them?

**Comment by eXorus** [comment]
Hello,

Of course I'm very interesting about this email.

You can send it here ( delete personal information before)

**Comment by eXorus** [comment]
@maku220 I didn't receive anything so I'm closing this issue feel free to open another one with this emails. I will love to see that
