### ISSUE TITLE
Re-inject email to postfix after filtered.

### ISSUE THREAD

**Issue by hifall** [php-mime-mail-parser/php-mime-mail-parser#143]
From PHP MIME mail parser's readme.md, it seems that an email filtered by the mail parser is not re-injected back to postfix, and it won't be stored in mail server's DB. While we need to parse the email ourselves, we definitely would like to store it in DB as well.

Could you please provide an example on how to re-inject the email to postfix after filtered by PHP MIME mail parser?

Thanks!

**Comment by eXorus** [comment]
Sorry I don't know a lot postfix, but I would love to know how to do that.

So feel free to contribute to this readme if you found the solution.

**Comment by eXorus** [comment]
Hello @hifall do you find a solution to do that ?

**Comment by conrad10781** [comment]
I'm pretty sure with the way the Postfix configuration is being used you'll need to reinject the mail with something like sendmail ( http://www.postfix.org/FILTER_README.html#simple_filter )
