### ISSUE TITLE
Problem installing via Composer.

### ISSUE THREAD

**Issue by Okdesk** [php-mime-mail-parser/php-mime-mail-parser#144]
On Ubuntu 16.04 LTS/PHP 7.0, by following the instructions on the project's page, I get:

ubuntu@VM-229-ubuntu:/var/parser$ sudo composer require php-mime-mail-parser/php-mime-mail-parser

                                                            
  [ErrorException]                                          
  proc_get_status() has been disabled for security reasons  
                                                            

require [--dev] [--prefer-source] [--prefer-dist] [--no-plugins] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

PHP Fatal error:  Uncaught ErrorException: proc_get_status() has been disabled for security reasons in /usr/share/php/Symfony/Component/Process/Process.php:1297
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'proc_get_status...', '/usr/share/php/...', 1297, Array)
#1 /usr/share/php/Symfony/Component/Process/Process.php(1297): proc_get_status(Resource id #146)
#2 /usr/share/php/Symfony/Component/Process/Process.php(726): Symfony\Component\Process\Process->updateStatus(false)
#3 /usr/share/php/Symfony/Component/Process/Process.php(778): Symfony\Component\Process\Process->isRunning()
#4 /usr/share/php/Symfony/Component/Process/Process.php(172): Symfony\Component\Process\Process->stop(0)
#5 [internal function]: Symfony\Component\Process\Process->__destruct()
#6 {main}
  thrown in /usr/share/php/Symfony/Component/Process/Process.php on line 1297

Fatal error: Uncaught ErrorException: proc_get_status() has been disabled for security reasons in /usr/share/php/Symfony/Component/Process/Process.php:1297
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'proc_get_status...', '/usr/share/php/...', 1297, Array)
#1 /usr/share/php/Symfony/Component/Process/Process.php(1297): proc_get_status(Resource id #146)
#2 /usr/share/php/Symfony/Component/Process/Process.php(726): Symfony\Component\Process\Process->updateStatus(false)
#3 /usr/share/php/Symfony/Component/Process/Process.php(778): Symfony\Component\Process\Process->isRunning()
#4 /usr/share/php/Symfony/Component/Process/Process.php(172): Symfony\Component\Process\Process->stop(0)
#5 [internal function]: Symfony\Component\Process\Process->__destruct()
#6 {main}
  thrown in /usr/share/php/Symfony/Component/Process/Process.php on line 1297

How can I get around this?

**Comment by Okdesk** [comment]
BTW, proc_get_status is not in php.ini's disable_function list.

**Comment by Okdesk** [comment]
As a side note, can I install the lib manually by copy and drop into my source tree?

Frankly speaking, I've run into various issue dealing with Composer. People say it's easiest to use a library with Composer, but it's not the case for me.

**Comment by eXorus** [comment]
Yes it's more easy to use composer and you will have the update automatically.

But you can copy manually the file and use it like this, no problem.

**Comment by Okdesk** [comment]
But how do I fix the exception "proc_get_status() has been disabled for security reasons" mentioned above? I am still stuck in this issue. Help would be appreciated.
