### ISSUE TITLE
How do I get content type of email?

### ISSUE THREAD

**Issue by hifall** [php-mime-mail-parser/php-mime-mail-parser#148]
Parser's getMessageBody takes a $type and returns the message body. However, one has to supply the correct $type explicitly, otherwise he might get empty message body. For example, if it's an html email, getMessageBody("text") returns empty.

How can I determine the correct content type of an email? I am not able to find a method in php-mime-mail-parser.

**Comment by eXorus** [comment]
```php
if ( !empty($parser->getMessageBody('text')) )
 return $parser->getMessageBody('text');
else 
return $parser->getMessageBody('html');
```
