### ISSUE TITLE
iconv(): Wrong charset

### ISSUE THREAD

**Issue by Kuzuto** [php-mime-mail-parser/php-mime-mail-parser#149]
Getting a Parse error on the Subject:

iconv(): Wrong charset, conversion from `ISO-8859-8-I' to `UTF-8//TRANSLIT//IGNORE' is not allowed

- Using PHP5

The Header of the e-mail looks like this :

from: Some Person <xxx@xxxx.xxx>
to: Receiver Person <xxx@xxxx.xxx>
subject: =?iso-8859-8-i?B?7vLw5CAn4PDpIOzgIPDu9uAnOiBJbnZvaWNlIDAyNzIyMDI3?=
thread-topic: Invoice 02722027
thread-index: AdK6Y/ytHyVjWxTGTfq/seEmVoSRoAAAFs9g
date: Fri, 21 Apr 2017 05:58:48 +0000
message-id: <6f10709867fc4912b006284e2e09a2e7@EX2010.DOMAIN.local>
references: <2344BCA60784A64393FEC19097C234F9F3E28AEB@xxxx.xxx>
in-reply-to: <2344BCA60784A64393FEC19097C234F9F3E28AEB@xxxx.xxx>
x-ms-has-attach:
x-auto-response-suppress: All
x-ms-exchange-inbox-rules-loop: xxx@xxx.xxx
x-ms-tnef-correlator:
content-type: text/html; charset="iso-8859-8-i"
content-transfer-encoding: quoted-printable
mime-version: 1.0

**Comment by Kuzuto** [comment]
If charset is set to x-user-defined, iconv() is throwing exception.
`$string = "Subject: =?x-user-defined?Q?VS:_kalender=E5ret_2017?=";
iconv("x-user-defined", 'UTF-8//TRANSLIT//IGNORE', $string);`
Parser is using 'x-user-defined' as in_charset for iconv() and failes.

**Comment by eXorus** [comment]
Sorry for my late reply.

I can't do anything if it's a bug from iconv, the only solution is to finish #137

**Comment by Kuzuto** [comment]
I don't know if it's a bug in iconv(). I can't see it supports 'x-user-defined' as the in_charset value. I might be wrong?
In Charset.php "public function getCharsetAlias($charset)", it returns 'x-user-defined' from the $charsetAlias array.

**Comment by eXorus** [comment]
I don't understand your bug, first comment you talk about "ISO-8859-8-I" and after you talk about "x-user-defined".

I don't know all the charset but I think that #137 can fix your bug. There is no release date yet for this PR.

**Comment by grigoriy-aga-parts** [comment]
Got an error where converting emails "wrong.... ISO-8859-8-I to UTF-8//TRANSLIT//IGNORE
Regarding this,
https://stackoverflow.com/questions/11889262/how-do-i-convert-iso-8859-8-i-to-utf-8
i've added this fix for myself:
`
            $ch = $this->getCharsetAlias($charset);

            // fix
            if ($ch = 'ISO-8859-8-I') $ch = 'ISO-8859-8';

            return iconv($ch, 'UTF-8//TRANSLIT//IGNORE', $encodedString);
`

**Comment by eXorus** [comment]
Big thanks @grigoriy-aga-parts
