### ISSUE TITLE
waiting after $Parser->setStream(fopen("php://stdin", "r"));

### ISSUE THREAD

**Issue by YairHadari** [php-mime-mail-parser/php-mime-mail-parser#155]
Hi,

I would like to thank you for contributing the library to the community.

I"m trying to run the test file without success.
I defined the path to the file correctly.
The path includes the filename.

It seems that the application is waiting for something on the   $Parser->setStream(fopen("php://stdin", "r"));
statement.

Can you please assist?

Thanks,
Yair

**Comment by eXorus** [comment]
Hello,

To init the lib, if you already have the file on a disk you only need to use 
$Parser->setPath($path);

if you have a mail server and receive a flux you need to 
$Parser->setStream(fopen("php://stdin", "r"));

Are you trying to run phpunit on my lib or using it ?
