### ISSUE TITLE
mailparse-installation failed.

### ISSUE THREAD

**Issue by rahulrockers** [php-mime-mail-parser/php-mime-mail-parser#156]
> pecl install mailparse-2.1.6

`/bin/bash /tmp/pear/temp/pear-build-rootga8fru/mailparse-2.1.6/libtool --mode=compile cc  -I. -I/tmp/pear/temp/mailparse -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootga8fru/mailparse-2.1.6/include -I/tmp/pear/temp/pear-build-rootga8fru/mailparse-2.1.6/main -I/tmp/pear/temp/mailparse -I/usr/include/php/20131226 -I/usr/include/php/20131226/main -I/usr/include/php/20131226/TSRM -I/usr/include/php/20131226/Zend -I/usr/include/php/20131226/ext -I/usr/include/php/20131226/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/mailparse/mailparse.c -o mailparse.lo
libtool: compile:  cc -I. -I/tmp/pear/temp/mailparse -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootga8fru/mailparse-2.1.6/include -I/tmp/pear/temp/pear-build-rootga8fru/mailparse-2.1.6/main -I/tmp/pear/temp/mailparse -I/usr/include/php/20131226 -I/usr/include/php/20131226/main -I/usr/include/php/20131226/TSRM -I/usr/include/php/20131226/Zend -I/usr/include/php/20131226/ext -I/usr/include/php/20131226/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/mailparse/mailparse.c  -fPIC -DPIC -o .libs/mailparse.o
/tmp/pear/temp/mailparse/mailparse.c:34:2: error: #error The mailparse extension requires the mbstring extension!
 #error The mailparse extension requires the mbstring extension!
  ^
/tmp/pear/temp/mailparse/mailparse.c: In function ‘extract_part’:
/tmp/pear/temp/mailparse/mailparse.c:1256:26: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 4 has type ‘off_t {aka long int}’ [-Wformat=]
    zend_error(E_WARNING, "%s(): error reading from file at offset %lld", get_active_function_name(TSRMLS_C), start_pos);
                          ^
/tmp/pear/temp/mailparse/mailparse.c: In function ‘add_attr_header_to_zval’:
/tmp/pear/temp/mailparse/mailparse.c:1394:28: warning: format ‘%d’ expects argument of type ‘int’, but argument 5 has type ‘long int’ [-Wformat=]
       spprintf(&newkey, 0, "%s%d", attrprefix, num_index);
                            ^
Makefile:187: recipe for target 'mailparse.lo' failed
make: *** [mailparse.lo] Error 1
ERROR: `make' failed
`

Also I followed steps from [this](http://wiki.cerbweb.com/Installing_PHP_Mailparse_Ubuntu).
still same error.

**Comment by mstaack** [comment]
this is my default installation on ubuntu for php7:
```
pecl install mailparse
sed -i '1s/^/#undef HAVE_MBSTRING\n#define HAVE_MBSTRING 1\n\n/' /usr/include/php/20160303/ext/mbstring/libmbfl/mbfl/mbfilter.h
pecl install mailparse

echo "extension=mailparse.so" >> /etc/php/7.1/fpm/php.ini
echo "extension=mailparse.so" >> /etc/php/7.1/cli/php.ini
```

works perfectly for me..give it a try

**Comment by rahulrockers** [comment]
I'm running on php 5.6. 
I also tried this.

> sudo pear install pecl/mailparse-2.1.6

same error again.

**Comment by eXorus** [comment]
Sorry to read that but I don't know how to help you

Did you try this thread:
https://github.com/php-mime-mail-parser/php-mime-mail-parser/issues/70

PHP 5.6 has no active support from 19 Jan 2017 and will have no security support in Dec 2018 maybe it's time to change to PHP7 :)
