### ISSUE TITLE
"Make sure you have the mailparse extension (http://php.net/manual/en/book.mailparse.php) properly installed"

### ISSUE THREAD

**Issue by Dingo64** [php-mime-mail-parser/php-mime-mail-parser#157]
The project seems solid but this sentence:

"Make sure you have the mailparse extension (http://php.net/manual/en/book.mailparse.php) properly installed"

basically means it's useless. Nobody installs PECL extensions. No servers come with PECL preinstalled and about 90% PHP websites run under shared hostings where it's not possible to install PECL.

**Comment by eXorus** [comment]
php-mime-mail-parser is a wrapper of mailparse so I don't know how to do without mailparse :)

But I understand your point.

You have other library to parse email without mailparse. I have the idea to be able to detect if mailparse is installed to use it (it will be faster) else use another lib but this is not for now.

How do you get the incoming email ? because my setup is to install postfix to have a mail server that is able to forward the email to my php script. If you can install postfix you can install PECL.

**Comment by Dingo64** [comment]
Thanks a lot for a reply and sorry for whining.
Well, I get emails by connecting to a POP3 (my own email server) or IMAP (eg. gmail) servers using imap_open() and imap_open() is pretty much always available, no matter what server. It also offers a bit of parsing (imap_fetchbody) but that parsing is just not enough for complicated emails.

**Comment by eXorus** [comment]
:open_mouth: That surprises me because I was thinking that all imap_* function are better than others library.

And I'm not sure you can do that, is there an imap function that return all the email not parsed ?

**Comment by Dingo64** [comment]
These 3 can return some details of an email:
```
$overview = imap_fetch_overview($box, $id, 0);
$message = imap_fetchbody($box, $id, '');
$struct = imap_fetchstructure($box, $id);
```
However they only parse some headers and plaintext. Getting attachments or embedded images is not possible here.

**Comment by eXorus** [comment]
php-mime-mail-parser need the all raw email to be able to work.

Did you try this with imap function ? 
https://stackoverflow.com/questions/2649579/downloading-attachments-to-directory-with-imap-in-php-randomly-works#34593248

**Comment by OnlyHardOfficial** [comment]
Can someone help me with how to install the "mailparse" extension in Ubuntu, can you give me a help with the links directly from the mailserver developer "file.so", I can not find anywhere ... Thank you if you can help with something...Thaks

**Comment by eXorus** [comment]
Everything is explain in the readme, in the section requirements.
