### ISSUE TITLE
getMessageBody() and rfc822 attachments

### ISSUE THREAD

**Issue by DHaswell** [php-mime-mail-parser/php-mime-mail-parser#158]
We are migrating away from `mimeDecode` and finding the library great so far, but we have come across one problem with how rfc822 attachments are parsed:

We have a unit test case for rfc822 forwarded emails, where an original message was sent with only a `text/plain` part, and a rfc822 reply/forward of that message had only a `text/html` part.

`getMessageBody('text')` goes through all parts in the message, and collects up just the `text/plain` parts and returns them.
It ignores parts with a `content-disposition` of `attachment`, however it _does_ then process sub-parts of an rfc822 attached message because these are at the top level of `$this->parts`. This means that for a html-only reply/forward to a text-only message, `getMessageBody('text')` will return just the text body of the original message, even though it is a sub-part of an attachment.

In our current code, we parse the raw parts from `mimeDecode` ourselves, and this also has the sub-parts of rfc822 attachments at the top level of its parts list. This is roughly how we work around the problem in our parser:

1. Collect up main text parts from the message, just like you do
1. Parse rfc822 attachments, finding their sub-parts and collecting text parts of them up in a _separate_ variable
1. Record hashes of the contents of sub-parts from rfc822 attachments, and then ignore these when we come across them in the main loop over all parts
1. If there was no main text body at the end, we actually use `Html2Text` to turn any html parts found into a plain text substitute
1. Join the rfc822 attached body to the bottom of the main body

Now we could (and probably will) write our own class extending `PhpMimeMailParser\Parser`, unless you feel that having the option to use `HTML2Text` if no `text/plain` parts are found would be beneficial to everyone?

It might be helpful to others though if `getMessageBody()` did not return rfc822 attached parts at all (either text or html), and we would be happy to contribute a fix for that in the same way our current implementation works.

**Comment by eXorus** [comment]
Nice I love to see this comment !!!

I don't understand your issue, could you give an example of forward email ?

**Comment by DHaswell** [comment]
[mixed_plain_html.txt](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/1302807/mixed_plain_html.txt)

**Comment by eXorus** [comment]
I think it's beneficial to everyone, I will not have time to do the fix but I will review your PR for sure.

Feel free to contribute. ;)

**Comment by luiz-brandao** [comment]
I think using `Html2Text` should be optional and probably better in a new method. Some HTML won't necessarily translate well to text. So my suggestion is to have a method exclusively for that, something like `getMessageAsText`

**Comment by eXorus** [comment]
getMessageAsText will return the text body or if there is no text body the html body parsed by Html2Text ?

**Comment by howardcox** [comment]
Daniel and I have looked at this and got a patch together.

In the end we decided against adding HTML2Text, as with this patch our application can decide for itself whether `getMessageBody('text')` returns anything (without it being polluted by RFC822 attachment parts) and if not, can fall back to `getMessageBody('html)` and our application can then use HTML2Text itself (any anyone else could handle this however they want)
