### ISSUE TITLE
getMessageBody() and  inline attachments

### ISSUE THREAD

**Issue by DHaswell** [php-mime-mail-parser/php-mime-mail-parser#160]
Hello, 

We have come across a problem when we attempt to get the text of an email with inline attachments. Running `getMessageBody('text')` only returns the text of the first `text/plain` it comes across however if there are multiple `text/plain` parts with `inline` attachments between them then we lose that content. We have attempted `getMessageBody('htmlEmbedded')` but that returns false and we don't want the content of the attachments just the content around them. Is there a way of achieving this?

The structure of the email is: 
```
###Email headers###

--Apple-Mail-015D4692-6118-492F-99E7-E720E8195D7B
Content-Type: text/plain;
	charset=us-ascii
Content-Transfer-Encoding: 7bit

Testing inline text

image attachment after me


--Apple-Mail-015D4692-6118-492F-99E7-E720E8195D7B
Content-Type: image/png;
	name=image1.png;
	x-apple-part-url=59386443-48E6-418A-A6CC-6284BB4C035F
Content-Disposition: inline;
	filename=image1.png
Content-Transfer-Encoding: base64

###image content###

--Apple-Mail-015D4692-6118-492F-99E7-E720E8195D7B
Content-Type: text/plain;
	charset=us-ascii
Content-Transfer-Encoding: 7bit

Here should be another image


--Apple-Mail-015D4692-6118-492F-99E7-E720E8195D7B
Content-Type: image/jpeg;
	name=image2.jpeg;
	x-apple-part-url=DEC7D8CB-E520-4B85-95D6-D50C57A6986A
Content-Disposition: inline;
	filename=image2.jpeg
Content-Transfer-Encoding: base64

###image contnent###

--Apple-Mail-015D4692-6118-492F-99E7-E720E8195D7B
Content-Type: text/plain;
	charset=us-ascii
Content-Transfer-Encoding: 7bit

Sent from my iPhone
--Apple-Mail-015D4692-6118-492F-99E7-E720E8195D7B--
```

When running our unit test against this email we receive 
```
Testing inline text

image attachment after me
```

when we are expecting

```
Testing inline text

image attachment after me

Here should be another image

Sent from my iPhone
```

**Comment by eXorus** [comment]
Hello,

There is no method for that and I didn't know it was possible to have more than one text/plain.

I tried to look in the RFC but I didn't find anything about restriction.

So maybe we can do that.

**Comment by DHaswell** [comment]
I have been attempting to recreate the email but honestly, I can't seem to. Every other email I receive does only have one `text/plain` or `text/html` even with inline attachments.

Our unit test could be flawed and this could be an email which is actually impossible to receive or it was sent from an old email client.

**Comment by eXorus** [comment]
So I'm closing this issue.

Feel free to reopen it if you find a solution to reproduce it.
