### ISSUE TITLE
HTML / attachment problem with Apple Mail

### ISSUE THREAD

**Issue by launtony** [php-mime-mail-parser/php-mime-mail-parser#164]
I have a problem with Apple Mail. When the attachment is before the signature, the HTML after was not parsed into getMessageBody('html') :/ 

An idea please ? :) 

Thanks a lot :p

**Comment by eXorus** [comment]
Could you send the raw email to investigate ?

**Comment by launtony** [comment]
Thanks for your reply :) 

[mail-mime.txt](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/1390412/mail-mime.txt)

**Comment by eXorus** [comment]
Thanks I understand the issue now, it's always the same problem with Apple Mail I don't know if this email is compliant to RFC.

**What you have:**

- Headers
- Part text
- Multipart Mixed
  - Part Html (<html>...</html>)
  - Part Inline Attachment (pdf)
  - Part Html (<html>...</html>)
 

**What this lib give you:**
- Headers
- Part Text
- Part Html (the first one)
- Part Attachment

So there is no way  to retrieve the second part Html but how I can do that this is 2 distinct Html part I can't construct one part with 2 html tag ???

I know and it worked in php-mime-mail-parser to inline attachment with content-id but I didn't know this way to do inline attachment. Could you find the RFC that said that ?

**Comment by launtony** [comment]
I understand :/ I will find the RFC if her exists :) But how to parse some emails in the same with the parser (some HTML replies) ?

**Comment by eXorus** [comment]
I think in this case we have a multipart/message that can be an attachment and you can pass again to the parser to retrieve the information.
But it's a good question, I need to investigate this also.

There is always some improvements to do :)

**Comment by launtony** [comment]
Do you have any news? :) I haven't found the Apple Mail RFC :/

**Comment by eXorus** [comment]
Could you send this email to gmail and see what is going on ? how google print this email ?

**Comment by launtony** [comment]
It's work with two HTML parts. 

I have uploaded the raw (from gmail). 

[original_msg.txt](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/1401891/original_msg.txt)

**Comment by eXorus** [comment]
how google render this ?

we see the email with the 2 html part with the PDF between them or in attachment ?

**Comment by launtony** [comment]
I have all HTML parts and the PDF in the attachment section

**Comment by launtony** [comment]
You have original_msg.txt on the previous messages. This is the gmail raw sources.

**Comment by eXorus** [comment]
I don't want the raw source, I want to see how the html is render in gmail. So the source code of the email.
Go to gmail
Select the body of your email
Right click and show source code.

**Comment by launtony** [comment]
Sorry, I didn't understand :/ you can find the body <div> from Gmail source code.

[email.html.txt](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/1402435/email.html.txt)

**Comment by eXorus** [comment]
Are you sure of your selection ?

because I don't see "Ceci est un test" that is a sentence of the first html part
and I only see "easylia-130.png" that is in the second html part.

So gmail don't merge the 2 html parts it only show the second part.

**Comment by launtony** [comment]
It not the same email :/ I' so sorry. In the attachment, it's the right source code. 
[email.html.txt](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/1402507/email.html.txt)

**Comment by launtony** [comment]
Do you have an idea? How gmail manage this case ?

**Comment by eXorus** [comment]
So I saw in the raw source is the 2 html parts merged together in one body.

Could you give me the screenshot of the email in gmail ? because you said earlier that gmail give you also the 2 html part in attachments.

**Comment by launtony** [comment]
You can found the screenshot here :) 

<img width="1420" alt="screen shot 2017-10-24 at 17 27 52" src="https://user-images.githubusercontent.com/6367604/31952364-b53b3232-b8e0-11e7-8c09-2c6e85dacbe8.png">

**Comment by launtony** [comment]
The original email contains an attachments between "Ceci est un test" and the signature. Gmail put all attachments in the attachments area. This is a good job. But your lib get only "Ceci est un test" and the attachment not the signature. On the raw source you can you 2 HTML tag. One for "Ceci est un test" and the signature.

**Comment by dorianfm** [comment]
This seems to be somewhat related to #163 which I've posted.

**Comment by launtony** [comment]
Yes I saw :/

**Comment by eXorus** [comment]
So you can use getInlineParts() to merge the 2 html now in the 2.9.3
