### ISSUE TITLE
mailparse_rfc822_parse_addresses() does not parse Quotes (") correctly

### ISSUE THREAD

**Issue by Schnoffel** [php-mime-mail-parser/php-mime-mail-parser#165]
Example:

`"Alan \"Crane\" Woke"`

It should be parsed to

`Alan "Crane" Woke`

but it is being parsed to:

`Alan \ Crane\  Woke`

See RFC2822 for further information: https://www.ietf.org/rfc/rfc2822.txt (Page 41)

**Comment by eXorus** [comment]
Nice bug I will try to reproduce and fix it.

**Comment by eXorus** [comment]
This is a bug from mailparse pecl extension.

Issue is created here: https://github.com/php/pecl-mail-mailparse/pull/3

I'm closing this one.

**Comment by Schnoffel** [comment]
Thank you very much for creating the bug report on  php/pecl-mail-mailparse!

**Comment by eXorus** [comment]
if you find a good regex that is working better than mailparse_rfc822_parse_addresses() I can use it ;)
