### ISSUE TITLE
mailparse_rfc822_parse_addresses() isn't able to correctly parse grouped addresses

### ISSUE THREAD

**Issue by ghost** [php-mime-mail-parser/php-mime-mail-parser#168]
There is another isse when using a Reply-To seen in RFC 822, A.2.4., Page 36, https://tools.ietf.org/html/rfc822:

```
Reply-To: The Committee: Jones@Host.Net,
          Smith@Other.Org,
          Doe@Somewhere-Else;
```

It will parse to:

```
(
            [display] => The Committee
            [address] => :Jones@Host.Net,Smith@Other.Org,Doe@Somewhere-Else;
            [is_group] => 1
)
```
As there is no answer yet on the last PR https://github.com/php/pecl-mail-mailparse/pull/3 may I ask if you know if development is still running there? Last commit were on 7th December 2016 so maybe one should look for an alternative solution than the PECL plugin.

**Comment by eXorus** [comment]
I sent a mail to the last creator of the last commit but mailparse is the best solution I know.

If you know another lib that is working I can try to evaluate it.

**Comment by mstaack** [comment]
@eXorus maybe give https://github.com/mmucklo/email-parse a try?

**Comment by eXorus** [comment]
I have also a lot of bug with this lib like (21 according to my unit test):

Keld Jørn Simonsen <keld@dkuug.dk>
+        'display' => 'Keld'
+        'address' => ''

sendeär <sender@test.com>
+        'display' => ''
+        'address' => ''

"name@company2.com" <name@com...2.com>
+        'display' => '"name@company2.com"'

**Comment by eXorus** [comment]
There is no issue here, it's a Address Lists.
https://www.w3.org/Protocols/rfc822/#z10

> A.1.5. Address Lists
> 
> Gourmets:  Pompous Person <WhoZiWhatZit@Cordon-Bleu>,
>            Childs@WGBH.Boston, Galloping Gourmet@
>            ANT.Down-Under (Australian National Television),
>            Cheapie@Discount-Liquors;,
>   Cruisers:  Port@Portugal, Jones@SEA;,
>     Another@Somewhere.SomeOrg
> 
> 
> 
>    This group list example points out the use of comments and the
>    mixing of addresses and groups.
