### ISSUE TITLE
input is not rfc822 compliant: already in < bracket

### ISSUE THREAD

**Issue by piernik** [php-mime-mail-parser/php-mime-mail-parser#174]
I've got problem with one email.
It returns `input is not rfc822 compliant: already
in <
bracket`

I have that email, but it's my customers email so I cannot publish it here. Can I somehow send it to You for tests?

**Comment by eXorus** [comment]
I think you can send me this email here but anonimize it.

exorus@mydomain.com => fake@fakedomain.com (keep only the structure)

**Comment by piernik** [comment]
Here is zipped file. Thanks.

[email.zip](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/1659782/email.zip)

**Comment by eXorus** [comment]
After my investigation, I found the issue. It's related to the header of your attachments (value of content-id).

What you have 
```
--_EFCD9C7B-E8A3-40DB-9289-6DFE606EA17E_
Content-Type: image/png; name="image001.png"
Content-ID: <<image001.png@01D37006.B013AAF0>>
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="image001.png"

iVBORw0KGgoAAAANSUhEUgAAAGsAAAAyCAIAAADUXLJkAAAAB3RJTUUH3wsGCiwNNxD4UgAAIABJ
```

What we expect:
```
--_EFCD9C7B-E8A3-40DB-9289-6DFE606EA17E_
Content-Type: image/png; name="image001.png"
Content-ID: <image001.png@01D37006.B013AAF0>
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="image001.png"

iVBORw0KGgoAAAANSUhEUgAAAGsAAAAyCAIAAADUXLJkAAAAB3RJTUUH3wsGCiwNNxD4UgAAIABJ
```

I think it's not compliant with the RFC http://www.faqs.org/rfcs/rfc2111.html

**Comment by piernik** [comment]
Thank for analyse.
Is it something I should fix with regexp?

**Comment by eXorus** [comment]
Yes I think.

Is it a real email ?

**Comment by piernik** [comment]
Sure it is. It's email fetched with this library: https://github.com/ddeboer/imap

**Comment by c1am** [comment]
@piernik Hello, just wondering if you ever fixed this issue and how?

**Comment by eXorus** [comment]
You can use middleware to clean the field: change "<<" by "<", and ">>" by ">".

**Comment by momala454** [comment]
it doesn't work, it crashes just before sending to the middleware
```php
   protected function parse()
    {
        $structure = mailparse_msg_get_structure($this->resource);
        $this->parts = [];
        foreach ($structure as $part_id) {
            $part = mailparse_msg_get_part($this->resource, $part_id);
            $part_data = mailparse_msg_get_part_data($part); // it crashes here
            $mimePart = new MimePart($part_id, $part_data);
            // let each middleware parse the part before saving
            $this->parts[$part_id] = $this->middlewareStack->parse($mimePart)->getPart();
        }
    }
```

**Comment by eXorus** [comment]
I don't understand your code, where is the regex in the middleware to replace the bracket ?

**Comment by momala454** [comment]
that's not my code, but that's php mile parser code, and it is calling the middleware after I receive the error "input is not rfc822 compliant: already in < bracket"
because the error is thrown at the line ```            $part_data = mailparse_msg_get_part_data($part); // it crashes here```

**Comment by eXorus** [comment]
OK, I get it, you're saying we can't use a middleware because the code will crash before the middleware executes. In that case, we need to clean the email before passing it to the parser.
