### ISSUE TITLE
is it possible to get server ip and server hostname?

### ISSUE THREAD

**Issue by lolchaps** [php-mime-mail-parser/php-mime-mail-parser#175]
I have an email address that all email received is piped to a php script which then stores the headers message subject etc in a database. This works fine, but what I need to do is also get the senders server IP and server hostname, is that possible?

**Comment by eXorus** [comment]
I'm not sure you can find this information in the email headers.

Paybe you can find this information from the communication between mail server.
http://www.postfix.org/pipe.8.html
with ${client_hostname}

But I think this is the ip or domain of google not the client.
