### ISSUE TITLE
Reverse of what this library does

### ISSUE THREAD

**Issue by ashitvora** [php-mime-mail-parser/php-mime-mail-parser#178]
I am trying to use Gmail API to send emails but it requires BASE64 URL ENCODED data.
Is there any library that does the reverse of this?

I want to pass Subject, Body, To, CC, BCC, Attachments etc and get Base64URLEncoded String from it.

Thanks!

**Comment by eXorus** [comment]
There are so many email library that are capable of sending email.

For example https://github.com/PHPMailer/PHPMailer

But it's better to use imap protocol to send email with gmail.
I'm closing this issue because it's not related to my library ;)
