### ISSUE TITLE
strtolower() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by Kuzuto** [php-mime-mail-parser/php-mime-mail-parser#181]
Sometimes I'm getting e-mails that produce this error.
The e-mail has a smime.p7m file attached, and when getAttachments() it produces the error.
I can track it down to : 
Parser.php line 653 , $encodingType = strtolower($encodingType);
It's getting ["raw","base64"] , and then fails.

I don't know how to fix this or prevent the Parser to fail. I'm guessing it's because it has 2 Content-Transfer-Encoding in the header.
Maybe I could remove one of the content header first before Parsing, but this could happen in other cases, and maybe Parser should take this into account before getting the attachments.

An example e-mail that failed, is here :

#######
Received: from xxxxxxx (unknown [])
	by xxxxxx() with ESMTP
	id 04fd3a85-14d7-11e8-97f5-005056a84308;
	Sun, 18 Feb 2018 18:10:37 +0000 (UTC)
Received: from [127.0.0.1] (localhost [127.0.0.1])
	by xxxxxxx (Postfix) with ESMTP id 84F557C0924
	for <rcpt@domain.com>; Sun, 18 Feb 2018 19:10:35 +0100 (CET)
Sender: sender@domain.com
Message-ID: <0b5f76b66e428a3d87eaa712567e6b30@some.domain.com>
Date: Sun, 18 Feb 2018 19:10:35 +0100
Subject: Testing subject
From: sender@domain.com
Reply-to: sender@domain.com
To: rcpt@domain.com
MIME-Version: 1.0
Content-Type: application/x-pkcs7-mime; smime-type=enveloped-data;
 name="smime.p7m"; charset=UTF-8
Content-Transfer-Encoding: raw
Content-Transfer-Encoding: base64
X-Mailer: Drupal
Content-Disposition: attachment; filename="smime.p7m"

123
#######

**Comment by eXorus** [comment]
Hello,

This email is not compliant to RFC. How a content can be raw AND base64 ?

If I choose one (the first or the last) the result could be very strange.

**Comment by Kuzuto** [comment]
Ok, yes. Then I will remove the 'raw' before parsing to make it RFC. That must be the correct solution.

**Comment by eXorus** [comment]
This can also be done with the new middleware #180
