### ISSUE TITLE
Attachment not displayed if contentDisposition header value is other than "attachment" or "inline"

### ISSUE THREAD

**Issue by nettunodev** [php-mime-mail-parser/php-mime-mail-parser#182]
I came across this issue when parsing an email having an attachment with contentDisposition "*" instead of "attachment" or "inline".

Dumping $Parser->getAttachments(true); i get:

`object(PhpMimeMailParser\Attachment)[5]`
`      protected 'filename' => string '318001229259.pdf' (length=16)`
`      protected 'contentType' => string 'application/pdf' (length=15)`
`      protected 'content' => null`
`      protected 'contentDisposition' => string '*' (length=1)`
`      protected 'contentId' => boolean false`
`      protected 'headers' => `
`        array (size=3)`
`          'content-type' => string 'application/pdf; name=318001229259.pdf' (length=38)`
`          'content-transfer-encoding' => string 'base64' (length=6)`
`          'content-disposition' => string '*;filename=318001229259.pdf' (length=27)`
`      protected 'stream' => resource(22, stream)`
`      protected 'mimePartStr' => string 'Content-Type: application/pdf; name=318001229259.pdf`
`Content-Transfer-Encoding: base64`
`content-disposition: *;filename=318001229259.pdf`

`JVBERi0xLjQNCiXi48/TDQolRE9DMSBSZXNvdXJjZUdVSUQ9MUFFNEE5NTZFMUI2NDlDMjg4NzlG`
`MUYwOEIzMTZCQTkNCjEgMCBvYmoNCjw8IC9UeXBlIC9QYWdlDQovUGFyZW50IDMgMCBSDQovUmVz`
`b3VyY2VzIDQgMCBSDQovQ29udGVudHMgMiAwIFINCi9NZWRpYUJveCBbMCAwIDU5NS4yOTUgODQx`
`Ljg5NV0NCj4+DQplbmRvYmoNCjIgMCBvYmoNCjw8L0xlbmd0aCAyNTMxIC9GaWx0ZXIgL0ZsYXRl`
`RGVjb2RlPj4NCnN0cmVhbQ0KeJytWd1u2zgWvi/Qd+BdO0CGEUlRlOZmoaZ'... (length=426345)`

I changed the line 480 in Parser.php from
 
`$dispositions = $include_inline ? ['attachment', 'inline'] : ['attachment'];`

to

`$dispositions = $include_inline ? ['attachment', 'inline', '*'] : ['attachment'];`

and it works. 
I was wondering if there's maybe a way to fix this for every _contentDisposition_ header that may presents, maybe checking if there's a _filename_ header. I don't know the whole logic behind the function, therefore I didn't try other fix because I didn't want to break something.

**Comment by eXorus** [comment]
Thanks, according to this:
https://tools.ietf.org/html/rfc6266#section-4.2
https://tools.ietf.org/html/rfc2183#section-2.8

> Unknown or unhandled disposition types SHOULD be handled by recipients the same way as "attachment"

We don't need to add `*` in the array on line 480 but we need to manage the unknown disposition types.

**Comment by nettunodev** [comment]
Thank you, yes, that's what I meant by 

> I was wondering if there's maybe a way to fix this for every contentDisposition header that may presents
