### ISSUE TITLE
Cannot get the body for parts other than standard text and html parts

### ISSUE THREAD

**Issue by winternet-studio** [php-mime-mail-parser/php-mime-mail-parser#183]
I have a bounced email I'm trying to parse and I need to get the body of the part with the content-type `message/delivery-status` but there is no public method to get that. There is the method `getPartBody()` and it works as needed, but it's protected so I can't use it!

**Comment by eXorus** [comment]
Could you provide an example ? is it not working with getAttachments ?

**Comment by winternet-studio** [comment]
Okay, it was possible using `getAttachments()` and then loop through and use `getMimePartStr()`. It just wasn't very obvious that I need to do that. When I read attachments I thought file attachments...
