### ISSUE TITLE
Messages with large attachments exceeding PHP memory limit

### ISSUE THREAD

**Issue by fko2221** [php-mime-mail-parser/php-mime-mail-parser#185]
If I try to parse a message that has a large attachment, I'm getting this error:

> PHP Fatal error: Allowed memory size of 134217728 bytes exhausted

Of course one solution is to increase the PHP memory limit. However, eventually an even larger message could cause this issue to come back. I found that a message of only 42MB can exceed the default memory limit of 128MB because the data is stored in memory multiple times.

I traced the problem to this line in getAttachments():

```php
$mimePartStr = $this->getPartComplete($part);
```

This copies and stores the entire MIME part (and encoded attachment) in memory a second time. I wish this line wasn't there because it never gets used. We can access the content of the attachment through $attachment->getContent(). (FWIW, this line did not exist in the original version by fijiwebdesign).

I suppose that removing this line is out of the question for backward compatibility reasons. So I came up with a work around. The call to getAttachmentStream() also uses a lot of memory in order to decode the attachment but then it writes the data to a temp file and releases the memory. If we place this call before the call to getPartComplete(), the code has a much smaller memory footprint. Like this:

```php
		$attachmentStream = $this->getAttachmentStream($part);
                $mimePartStr = $this->getPartComplete($part);

                $attachments[] = new Attachment(
                    $filename,
                    $this->getPart('content-type', $part),
                    $attachmentStream,
                    $disposition,
                    $contentidAttachments,
                    $headersAttachments,
                    $mimePartStr
                );
```

This allows parsing much larger messages without increasing the PHP memory limit. I will submit a PR if this sounds ok.

**Comment by fko2221** [comment]
I think we can also save some overhead by not storing $mimePartStr in a local variable. 

```php
                $attachmentStream = $this->getAttachmentStream($part);

                $attachments[] = new Attachment(
                    $filename,
                    $this->getPart('content-type', $part),
                    $attachmentStream,
                    $disposition,
                    $contentidAttachments,
                    $headersAttachments,
                    $this->getPartComplete($part)
                );
```

**Comment by eXorus** [comment]
Nice catch but your PR doesn't work, the build failed

**Comment by fko2221** [comment]
Yeah I see that but I don't know why. It's giving me this error 

> Illegal string offset 'starting-pos'
>
>/home/travis/build/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php:843

**Comment by fko2221** [comment]
Looks like I discovered another issue. The $part array gets clobbered by getAttachmentStream() because it is passed by reference and then a string is assigned to it.

```php
    protected function getAttachmentStream(&$part)
    {
            ......
            $part = fread($this->stream, $write);
            fwrite($temp_fp, $this->decodeContentTransfer($part, $encodingType));
            ......
    }
```

So if you try to use $part as an array after calling getAttachmentStream it bombs out. I fixed it by changing the variable name in getAttachmentStream() and the tests are passing now.

**Comment by eXorus** [comment]
Thanks a lot for your contribution.
