### ISSUE TITLE
Attachment conversion from `x-user-defined' to `UTF-8//TRANSLIT//IGNORE' is not allowed

### ISSUE THREAD

**Issue by Kuzuto** [php-mime-mail-parser/php-mime-mail-parser#187]
Hi,
I have received some e-mails where Attachment filename is written with 'x-user-defined'. Like this:
Content-Transfer-Encoding: base64
Content-Type: application/octet-stream; name="=?x-user-defined?Q?PO.pdf?="
Content-Disposition: attachment; filename="=?x-user-defined?Q?PO.pdf?="

When getAttachments, it's throwing : iconv(): Wrong charset, conversion from `x-user-defined' to `UTF-8//TRANSLIT//IGNORE' is not allowed

Do I need to convert/remove 'x-user-defined' before setText, or do parser needs to support 'x-user-defined'.. I'm not sure how to prevent the exception?

thx.

**Comment by eXorus** [comment]
Hi,

I didn't know this value x-user-defined so I don't know if it's a correct value and I don't know how to decode it.

Do you have more information about x-user-defined ?

**Comment by Kuzuto** [comment]
I don't see any pointers in the header either. So maybe I just need to preg_replace ..

MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="4D_==================240350217=="
Date: Mon, 19 Mar 2018 09:30:53 -0500
To: <xxxx@xxxx.xx>
From: <xxxx@xxxx.xx>
Subject: =?utf-8?Q?PO_Email_20448?=
Message-ID: <c141e1d98e7a461fac37051ea6eff088@S12-MBX11-14.S12.local>
X-Originating-IP: [10.40.130.245]
X-ClientProxiedBy: S12-CAS103.S12.local (10.40.128.92) To
 S12-MBX11-14.S12.local (10.40.128.43)
X-RoutingAgent: Treated
X-CrossPremisesHeadersFilteredBySendConnector: S15-MBX101.S15.local
X-OrganizationHeadersPreserved: S15-MBX101.S15.local
X-FM-White: dnswl - s15-gw104.mycloudmailbox.com [207.126.101.41]
X-FM-OS: Linux 2.2.x-3.x
X-FM-GeoIP: US
X-Proto: esmtps
X-Revdns: s15-gw104.mycloudmailbox.com
X-HELO: S15-GW104.mycloudmailbox.com
X-TLS: TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256

--4D_==================240350217==
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable

Thanks

--4D_==================240350217==
Content-Transfer-Encoding: base64
Content-Type: application/octet-stream; name="=?x-user-defined?Q?PO.pdf?="
Content-Disposition: attachment; filename="=?x-user-defined?Q?PO.pdf?="

**Comment by eXorus** [comment]
I found this 2 urls that say this is not a good encoding 
https://www.w3.org/International/questions/qa-choosing-encodings
https://encoding.spec.whatwg.org/#x-user-defined

I try to reproduce your error but I cannot, I have never an error when I call getAttachments

**Comment by Kuzuto** [comment]
Closing this issue
