### ISSUE TITLE
thunderbird

### ISSUE THREAD

**Issue by a7med-hussien** [php-mime-mail-parser/php-mime-mail-parser#190]
when send email using thunderbird

$text       = $Parser->getMessageBody('text');
$html      = $Parser->getMessageBody('html');
$htmlEm = $Parser->getMessageBody('htmlEmbedded');

returns empty string "",

put when using any mailing service [yahoo, gmail, outlook] it works fine

how to fix this Bug ?

**Comment by eXorus** [comment]
Hello,

I need the content of the mail to be able to investigate.

But I think it's because there is a missing line at the end of the file.

**Comment by eXorus** [comment]
Feel free to reopen if you have more information
