### ISSUE TITLE
Attachment with MSG extension with internal attachments comes unnamed

### ISSUE THREAD

**Issue by ThePokyWizard** [php-mime-mail-parser/php-mime-mail-parser#194]
When a file with an .msg extension is sent, and it has internal attachments, it does not recognize the original file name, and the contents of the .msg attachment have encoding problems.

This happens when the email is sent through Outlook 2016.

**Comment by eXorus** [comment]
Could you give an example with the actual result and the expected result ?

**Comment by ThePokyWizard** [comment]
Steps to reproduce the problem.

1. Send a e-mail with HTML from Outlook 2016 to another Outlook 2016;
2. On recipient save message with the format _Outlook Message Format - Unicode_;
3. With Outlook 2016, send the saved message and send to PHP MMP.

This is the result, the left message is the original, the right is the message after PHP MMP receive the message.

Original filename: Original.msg
Filename generated by PHP MMP: noname

Something curious is that even Gmail can not get the correct file name, maybe this is a problem with the header sent by Outlook.

![problem](https://user-images.githubusercontent.com/2734391/38840456-1d944630-41b6-11e8-9ac9-5fc1d0aa1966.png)

The code below is the source code from the original message:

```
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:m="http://schemas.microsoft.com/office/2004/12/omml" xmlns="http://www.w3.org/TR/REC-html40"><head>

<meta name="Generator" content="Microsoft Word 15 (filtered medium)">
<!--[if !mso]><style>v\:* {behavior:url(#default#VML);}
o\:* {behavior:url(#default#VML);}
w\:* {behavior:url(#default#VML);}
.shape {behavior:url(#default#VML);}
</style><![endif]--><style><!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	margin-bottom:.0001pt;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;
	mso-fareast-language:EN-US;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:#0563C1;
	text-decoration:underline;}
a:visited, span.MsoHyperlinkFollowed
	{mso-style-priority:99;
	color:#954F72;
	text-decoration:underline;}
p.msonormal0, li.msonormal0, div.msonormal0
	{mso-style-name:msonormal;
	mso-margin-top-alt:auto;
	margin-right:0cm;
	mso-margin-bottom-alt:auto;
	margin-left:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
span.EstiloDeEmail18
	{mso-style-type:personal-compose;
	font-family:"Calibri",sans-serif;
	color:windowtext;}
.MsoChpDefault
	{mso-style-type:export-only;
	font-size:10.0pt;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:70.85pt 3.0cm 70.85pt 3.0cm;}
div.WordSection1
	{page:WordSection1;}
--></style><!--[if gte mso 9]><xml>
<o:shapedefaults v:ext="edit" spidmax="1026" />
</xml><![endif]--><!--[if gte mso 9]><xml>
<o:shapelayout v:ext="edit">
<o:idmap v:ext="edit" data="1" />
</o:shapelayout></xml><![endif]-->
</head>
<body lang="PT-BR" link="#0563C1" vlink="#954F72">
<div class="WordSection1">
<p class="MsoNormal"><span style="color:#1F497D">Hello,<o:p></o:p></span></p>
<p><span style="color:#4472C4">Word with special chars<o:p></o:p></span></p>
<p class="MsoNormal"><span style="color:#4472C4;mso-fareast-language:PT-BR">Test</span><span style="color:black;mso-fareast-language:PT-BR"><o:p></o:p></span></p>
<p class="MsoNormal"><span style="color:#4472C4;mso-fareast-language:PT-BR">Operatiron: Não Programado<br>
Central: </span><span style="color:#1F497D;mso-fareast-language:PT-BR">TEST<o:p></o:p></span></p>
<p class="MsoNormal"><span style="color:#4472C4;mso-fareast-language:PT-BR"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><img width="653" height="399" style="width:6.802in;height:4.1562in" id="Imagem_x0020_1" src="cid:image001.png@01D3D5C0.98CA0590" alt="cid:image001.png@01D3D5C0.98CA0590"><span style="color:#4472C4;mso-fareast-language:PT-BR"><o:p></o:p></span></p>
</div>
</body>
</html>
```

**Comment by eXorus** [comment]
Ok thanks for this report.
For me the result is good expect for the encoding issue. but I need the raw content of the email to understand the issue.

How do you open in Outlook the message of Php MMP ? my library is used to show a message in the browser not in outlook.

**Comment by karstennilsen** [comment]
I have exactly the same issue.
Attached a legit EML sent out by Exchange/Outlook with an attached e-mail message with Content-Type message/rfc822 and no filename (Outlook uses the subject as name)
![outlook](https://user-images.githubusercontent.com/8917480/43717528-2837d686-9988-11e8-9577-13d3bd22ba80.JPG)

When you do
`foreach ($Parser->getAttachments(false) as $attachment) {
    print_r($attachment->getFilename());
}`

You now get:
`noname1
Afbeelding1.png
belangrijk.jpg`

You should get:
`estate
Afbeelding1.png`

Now the php-mime-mail-parser even shows the attachment of the attached message, this of course shouldn't happen.

[example-eml.zip](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/2262552/example-eml.zip)

**Comment by eXorus** [comment]
There is no rule in the RFC about an attachment without filename, so the rule of outlook to use the subject as name is not the best way to do it.
How it will work if you have 2 attachments with no filename in the same email ?

**Comment by karstennilsen** [comment]
2 attachment example:
[2msgs.zip](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/2269376/2msgs.zip)
![image](https://user-images.githubusercontent.com/8917480/43823735-562b93ca-9af0-11e8-8668-461f7a102bb8.png)

RFC: https://tools.ietf.org/html/rfc2049
Search for `message/rfc822` to see the exact specification.
Additional find: https://blogs.msdn.microsoft.com/vikas/2008/09/09/how-it-works-why-my-msg-files-are-getting-converted-to-inline-attachments/

6% of mails being send is done using Outlook (https://litmus.com/blog/the-2017-email-client-market-share-infographic). Being able to support these messages would be nice.

**Comment by eXorus** [comment]
I don't understand exactly what you want. I already manage the attachment message/rfc822 like an attachment but not recursively so you need to give the body of the message/rfc822 to the parser again to parse this new email.

In your example-eml.zip I saw 3 parts:

```
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable
```
Parsed to "Test now..." OK

```
Content-Type: image/jpeg; name="belangrijk.jpg"
Content-Description: belangrijk.jpg
Content-Disposition: attachment; filename="belangrijk.jpg"; size=83463;
```
Parsed to an image attachment. OK

```
Content-Type: message/rfc822
Content-Disposition: attachment;
```
so according to RFC it should be show like an attachment

Afbeelding1.png should not be parsed in the first email.

Can be difficult to manager but I will try

**Comment by karstennilsen** [comment]
I believe it indeed should not work recursively.

MAIN
  - text/plain (alternative)
  - text/html (alternative)
 - image1.jpg (attachment)
 - MESSAGE1 (message/rfc822)
     - text/plain (alternative)
     - text/html (alternative)
     - image2.jpg (attachment of MESSAGE1)
- MESSAGE2 (message/rfc822)
    - image3.jpg (attachment of MESSAGE2)

In this case I think you should only get the following mime parts:
- text-plain
- text-html
- image1.jpg
- MESSAGE1 (message/rfc822)
- MESSAGE2 (message/rfc822)

**Comment by eXorus** [comment]
First of all, php-mime-mail-parser is only a wrapper of mailparse, so this is the part extracted by mailparse:

**example.eml**
```php
    public function testOutlook()
    {
        $file = __DIR__ . '/mails/example.eml';
        $Parser = new Parser();
        $Parser->setPath($file);
        var_dump($Parser->getParts());
    }
```

```
_008_19ca2d97e4f64d30b2b980b5c3207620WPOEX8werkplekoveralnl_
    1.1.1.1 text-plain
    1.1.1.2 text-html
    1.1.2 image001.png
    1.1.3 image002.png
_008_19ca2d97e4f64d30b2b980b5c3207620WPOEX8werkplekoveralnl_
    1.2 MESSAGE1 (message/rfc822)
_008_19ca2d97e4f64d30b2b980b5c3207620WPOEX8werkplekoveralnl_
    1.3 belangrijk.jpg
_008_19ca2d97e4f64d30b2b980b5c3207620WPOEX8werkplekoveralnl_
```

**2msgs.eml:**
```php
    public function testOutlook2()
    {
        $file = __DIR__ . '/mails/2msgs.eml';
        $Parser = new Parser();
        $Parser->setPath($file);
        var_dump($Parser->getParts());
    }
```

```
_009_20c74a05fea3408fb86a70df81944605WPOEX8werkplekoveralnl_
    1.1.1.1 text-plain
    1.1.1.2 text-html
    1.1.2 image001.png
    1.1.3 image002.png
_009_20c74a05fea3408fb86a70df81944605WPOEX8werkplekoveralnl_
    1.2 belangrijk.jpg
_009_20c74a05fea3408fb86a70df81944605WPOEX8werkplekoveralnl_
    1.3 MESSAGE1 (message/rfc822)
_009_20c74a05fea3408fb86a70df81944605WPOEX8werkplekoveralnl_
    1.4 MESSAGE2 (message/rfc822)
_009_20c74a05fea3408fb86a70df81944605WPOEX8werkplekoveralnl_
```


According to your last post for this email:

    text-plain [OK]
    text-html [OK]
    image001.png [OK]
    belangrijk.jpg [You are missing this image]
    MESSAGE1 (message/rfc822) [OK]
    MESSAGE2 (message/rfc822) [OK]


So for me there are no issue on mailparse but on php-mime-mail-parser because this test passed:

 ```php
   public function testOutlook2()
    {
        $file = __DIR__ . '/mails/2msgs.eml';
        $Parser = new Parser();
        $Parser->setPath($file);
        $this->assertContains("Met vriendelijke groet,", $Parser->getMessageBody('text'));
        $this->assertContains("www.w3.org/TR/REC-html40", $Parser->getMessageBody('html'));
        $attachments = $Parser->getAttachments();
        $this->assertEquals("image001.png", $attachments[0]->getFilename());
        $this->assertEquals("image002.png", $attachments[1]->getFilename());
        $this->assertEquals("belangrijk.jpg", $attachments[2]->getFilename());
        $this->assertEquals("noname1", $attachments[3]->getFilename());
        $this->assertEquals("image001.png", $attachments[4]->getFilename());
        $this->assertEquals("belangrijk.jpg", $attachments[5]->getFilename());
        $this->assertEquals("noname2", $attachments[6]->getFilename());
        $this->assertEquals("image001.png", $attachments[7]->getFilename());
        $this->assertEquals("belangrijk.jpg", $attachments[8]->getFilename());
    }
```
and shoudn't. It should passed like this

  ```php
  public function testOutlook2()
    {
        $file = __DIR__ . '/mails/2msgs.eml';
        $Parser = new Parser();
        $Parser->setPath($file);
        $this->assertContains("Met vriendelijke groet,", $Parser->getMessageBody('text'));
        $this->assertContains("www.w3.org/TR/REC-html40", $Parser->getMessageBody('html'));
        $attachments = $Parser->getAttachments();
        $this->assertEquals("image001.png", $attachments[0]->getFilename());
        $this->assertEquals("belangrijk.jpg", $attachments[1]->getFilename());
        $this->assertEquals("noname1", $attachments[2]->getFilename());
        $this->assertEquals("noname2", $attachments[3]->getFilename());
    }
```

How will be the api to get image002.png or the belangrijk.jpg inside the noname2 ?

**Comment by karstennilsen** [comment]
I think you should just give the nonames back as raw attachment. 
If a developer want to parse this attachment it can just:
```
if ($attachment->getContentType() == 'message/rfc822') {
  $ParserAttachedMessage = new Parser();
  $ParserAttachedMessage->setText($attachments->getContent());
}
```

**Comment by eXorus** [comment]
This issue is already fixed on master or at least you can get only the main attachments with:

`$Parser->getAttachments(Parser::GA_TOPLEVEL)`

I'm working on a the next major version and it will be the default.
