### ISSUE TITLE
Issues with &quot; and quotes

### ISSUE THREAD

**Issue by jonathanroy** [php-mime-mail-parser/php-mime-mail-parser#197]
For some reason, this:
```
<span style=3D"font-size:11.0pt; font-family:&quot;C=
alibri&quot;,sans-serif; color:#1F497D" lang=3D"FR-CA">Bonjour,
</span>
```

Gets parsed into this:
```
<span style="font-size:11.0pt; font-family:"Calibri",sans-serif; color:#1F497D" lang="FR-CA">Bonjour,
</span>
```

Because of quotes within quotes (around the Calibri font name), this HTML is obviously not valid.

Is there a workaround or is this a bug on the sending part?

**Comment by eXorus** [comment]
Hello

Yes it's an issue on the sending part.
https://stackoverflow.com/questions/25916943/uses-for-the-quot-entity-in-html

It should be 
```
<span style=3D"font-size:11.0pt; font-family:'C=
alibri',sans-serif; color:#1F497D" lang=3D"FR-CA">Bonjour,
</span>
```

**Comment by jonathanroy** [comment]
Thank you @eXorus for the answer.
If you don't mind, could you point me towards a solution to fix this problem?

**Comment by eXorus** [comment]
I think you can find a solution on the web with regex.

Replace all &quot; inside a style="..." by &apos;
