### ISSUE TITLE
Undefined variable error using Postfix

### ISSUE THREAD

**Issue by ralph-de-neuton** [php-mime-mail-parser/php-mime-mail-parser#200]
Using option 4, taking input from php://stdin gives me this error: Any idea what might cause it?
 Command died with status 255: "php". Command output: PHP
    Notice:  Undefined variable: Parser in /var/www/email-postfix.php on line
    30  Notice: Undefined variable: Parser in /var/www/email-postfix.php on
    line 30 PHP Fatal error:  Uncaught Error: Call to a member function
    setStream() on null in /var/www/email-postfix.php:30 Stack trace: #0 {main}
    thrown in /var/www/email-postfix.php on line 30  Fatal error: Uncaught
    Error: Call to a member function setStream() on null in
    /var/www/email-postfix.php:30 Stack trace: #0 {main}   thrown in
    /var/www/email-postfix.php on line 30

**Comment by eXorus** [comment]
I think you didn't import correctly the lib, it's a pure PHP error.

```php
$Parser->setStream(fopen("php://stdin", "r"));
```
Call to a member function setStream() on null

so you need to initialize $Parser.

Maybe you forgot this 2 lines before ?
```php
require_once __DIR__.'/vendor/autoload.php';
$Parser = new PhpMimeMailParser\Parser();
```
