### ISSUE TITLE
"Call to undefined function PhpMimeMailParser\\mailparse_msg_parse_file()" when mailparse extension is installed

### ISSUE THREAD

**Issue by Lefel95** [php-mime-mail-parser/php-mime-mail-parser#202]
Hi, I'm trying to use your class in a ubuntu16.04 with php7+ installed, but always returns:
`"Call to undefined function PhpMimeMailParser\\mailparse_msg_parse_file()"`
I'm Using Laravel 5.5 Framework with apache, I installed your package with composer and here's
My Code:
`
public function saveEmailFromFile($filePath)
    {
        $mime = new \PhpMimeMailParser\Parser();
        $mime->setPath($filePath);
        dd("hey", $mime, "hey");
    }
`

I followed your documentation and for sake, I used: `php -m | grep mailparse ` and returned : `mailparse` in bold and red

can somebody give me a light?

PS: Sorry but I Don't know how to code style properly in this editor

**Comment by eXorus** [comment]
Hello,

I'm using Laravel also and I don't have any issue.

You could check https://mailcare.io or https://github.com/mailcare/mailcare it's open-source.

```php
...
use \PhpMimeMailParser\Parser;

class ReceiveEmail extends Command
{
   public function saveEmailFromFile($filePath) {
      $mime = new Parser;
      $mime->setPath($filePath);
      dd("hey", $mime, "hey");
   }
}
...
```

I take an example from here: https://github.com/mailcare/mailcare/blob/master/app/Console/Commands/ReceiveEmail.php
