### ISSUE TITLE
sending plain text email via gmail.  Not getting content type.  

### ISSUE THREAD

**Issue by heffneil** [php-mime-mail-parser/php-mime-mail-parser#204]
So if I just use $text = $Parser->getMessageBody('text'); I get the body content properly but if I email a txt message.  But if I do something like this:

$text = $Parser->getMessageBody('text');
if ($text = "") {
	$text = $Parser->getMessageBody('html');
}
my $text becomes blank.   The problem is I know it isn't blank but the check of "" returns false. and then it sets it the variable to the HTML value.  Is there some encoding variable?  I am trying to build something that gets the body of the email anyway the email is encoded.  Perhaps I am missing something? Thanks.

**Comment by eXorus** [comment]
It's normal, if you did $text="" it's different of $text=="".
The first one will affect empty to the variable text.
The second will compare the variable text with empty and return true or false.
