### ISSUE TITLE
Question regarding reading .MSG files

### ISSUE THREAD

**Issue by Unholny** [php-mime-mail-parser/php-mime-mail-parser#211]
Hey guys.

First of all - thank you for the great work so far!

I am using Laravel for my small play-around project. I am trying to read an Outlook .msg file.
Does PHP-MIME-MAIL-PARSER do that?

This is part of the code, where I am trying to get the subject of the mail. Is everything correct?

`$path = $request->file('email')->getPathName();`
`$Parser = new \PhpMimeMailParser\Parser();`
`$Parser->setPath($path);`
`$subject = $Parser->getHeader('subject');`
`dd($subject);`

**Comment by eXorus** [comment]
Thanks
Nice choice for Laravel <3

Yes it should work

**Comment by Unholny** [comment]
Thanks!

It's giving me "false"..

**Comment by Unholny** [comment]
P.S.

None of the functions from the documentation are working for my .msg file:
`$to = $Parser->getHeader('to');`
`$addressesTo = $Parser->getAddresses('to');`
`$from = $Parser->getHeader('from');`
`$addressesFrom = $Parser->getAddresses('from');`
`$subject = $Parser->getHeader('subject');`
`$text = $Parser->getMessageBody('text');`
`$html = $Parser->getMessageBody('html');`
`$htmlEmbedded = $Parser->getMessageBody('htmlEmbedded');`
`$stringHeaders = $Parser->getHeadersRaw();`
`$arrayHeaders = $Parser->getHeaders();`

**Comment by eXorus** [comment]
Hello,

Could you provide the content of the .msg file to investigate the issue ?

**Comment by farooq-tj** [comment]
For me
Also no any function is working for me for .msg files has there been any improvement please let me know
here is my .msg test file within =====

==================================
Date: Tue, 24 Dec 2019 18:04:27 -0800 (PST)
From: s <user1@example.com>
To: admin <admin@example.com>
Message-ID: <1731327302.21.1577239467674.JavaMail.root@example.com>
Subject: hi
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit
X-Originating-IP: [192.168.241.1]
X-Mailer: Zimbra 8.0.3_GA_5664 (ZimbraWebClient - GC79 (Win)/8.0.3_GA_5664)
Thread-Topic: hi
Thread-Index: p1arj8p79L/83bZ8hDMMDBqn5IlM2Q==

hi
=======================================================

**Comment by eXorus** [comment]
Hello @farooq-tj 

I don't have any issue to parse your example with this code:
```php

        $file = __DIR__ . '/mails/issue211';
        $Parser = new Parser();
        $Parser->setText(file_get_contents($file));
        $body = $Parser->getMessageBody('text');
        $subject = $Parser->getHeader('subject');

        $this->assertEquals('hi', $subject);
        $this->assertContains('hi', $body);
```

**Comment by farooq-tj** [comment]
Hi Thanks for your reply 

Yes its working for me :) Thanks for this awesome library..!
