### ISSUE TITLE
WARNING: mb_convert_encoding(): Illegal character encoding specified for Windows-1250 encoded e-mail subject

### ISSUE THREAD

**Issue by pako-pl** [php-mime-mail-parser/php-mime-mail-parser#212]
The following change:

https://github.com/php-mime-mail-parser/php-mime-mail-parser/commit/c6f0ec06035512360404b5a3f3826e31d701ddc4

caused the following error for us:

`WARNING: mb_convert_encoding(): Illegal character encoding specified`

for an e-mail with this Subject header:

```
Subject: =?windows-1250?Q?Automatyczna_odpowied=9F:_Piotrze,_test_z_6_miesi=EAcy_na?=
 =?windows-1250?Q?uki_ci=B9gle_na_Ciebie_czeka?=
```

php-mime-mail-parser calls the function like this:

`mb_convert_encoding('example subject part', 'UTF-8', 'windows-1250');`

The Windows-1250 character encoding is commonly used by Microsoft programs in Poland and several other countries: https://en.wikipedia.org/wiki/Windows-1250. Strangely it's not listed as supported by the Multibyte String PHP extension: https://secure.php.net/manual/en/mbstring.supported-encodings.php (or it is listed under another name I don't recognize).

php-mime-mail-parser version 2.11.0 and earlier worked fine for us, as they used iconv. For example, the following call does the conversion correctly:

`iconv('windows-1250', 'UTF-8', quoted_printable_decode('Automatyczna_odpowied=9F:_Pawle,_test_z_6_miesi=EAcy_na'));`

**Comment by eXorus** [comment]
Hello,

Sorry for that, you could keep the old version and I will work on the fix.

Thanks for the report.

**Comment by pako-pl** [comment]
A possible fix would be to revert back to iconv for Windows-1250.

```
    public function decodeCharset($encodedString, $charset)
    {
        if (strtolower($charset) == 'utf-8' || strtolower($charset) == 'us-ascii') {
            return $encodedString;
        } elseif (function_exists('mb_convert_encoding') && strtolower($charset) == 'iso-2022-jp') {
            return mb_convert_encoding($encodedString, 'UTF-8', 'ISO-2022-JP-MS');
        } elseif (function_exists('mb_convert_encoding') **&& strtolower($charset) != 'windows-1250'**) {
            return mb_convert_encoding($encodedString, 'UTF-8', $this->getCharsetAlias($charset));
        } else {
            return iconv($this->getCharsetAlias($charset), 'UTF-8//TRANSLIT//IGNORE', $encodedString);
        }
    }
```

**Comment by eXorus** [comment]
I don't want to specify a different rule for each charset.
I think I will check do something like that:

```php
public function decodeCharset($encodedString, $charset)
{
    if (strtolower($charset) == 'utf-8' || strtolower($charset) == 'us-ascii') {
        return $encodedString;
    } elseif (function_exists('mb_convert_encoding') && strtolower($charset) == 'iso-2022-jp') {
        return mb_convert_encoding($encodedString, 'UTF-8', 'ISO-2022-JP-MS');
    } elseif (function_exists('mb_convert_encoding') && array_search($charset, mb_list_encodings()) !== false) {
        return mb_convert_encoding($encodedString, 'UTF-8', $this->getCharsetAlias($charset));
    } else {
        return iconv($this->getCharsetAlias($charset), 'UTF-8//TRANSLIT//IGNORE', $encodedString);
    }
}

```

**Comment by pako-pl** [comment]
Searching the result of `mb_list_encodings()` sounds like a good idea.
