### ISSUE TITLE
Attachment Directory 

### ISSUE THREAD

**Issue by AElleray** [php-mime-mail-parser/php-mime-mail-parser#214]
I have my DIR for attachments set as 
`$attach_dir =  '/uploads/'; 	// Be sure to include the trailing slash`
however, it's creating a folder called "u" and adding the files in there
which then causes the following line to error 
`echo 'Filesize : '.filesize($attach_dir.$attachment->getFilename()).'<br />'; // 1000`

why do the files not go in the correct folder?

**Comment by eXorus** [comment]
I don't understand exactly your issue, could you provide the full php script ?
