### ISSUE TITLE
Does it support MSG binary files?

### ISSUE THREAD

**Issue by zenopopovici** [php-mime-mail-parser/php-mime-mail-parser#215]
It seems that the body always comes out as binary content when using `$parser->getMessageBody->text()`

**Comment by zenopopovici** [comment]
@eXorus Yeah, sorry about that.

Here are 2 sample MSG files:
[sample.msg.zip](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/2468893/sample.msg.zip)
![screenshot 2018-10-11 at 15 38 24](https://user-images.githubusercontent.com/767998/46804637-ce3b7d00-cd6b-11e8-946d-de4fb6ffbae5.png)

The library does extract the headers correctly, but the body is all garbled.

**Comment by eXorus** [comment]
Hello,

Where does this file come ? You should not save it with an extension .doc and it seems corrupt because I cannot open it on my system.

The library don't have any issue to open msg file but your file is not valid. Sorry.

**Comment by zenopopovici** [comment]
Hello, I don't know why it saves it as .doc. 

This file comes from Outlook. If you drag an email out of outlook it will save it as a msg. file.
I just did that with a recent email: 
[Hostbuddy 2 0 is Now Available and Ready for macOS Mojave.msg.zip](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/2478281/Hostbuddy.2.0.is.Now.Available.and.Ready.for.macOS.Mojave.msg.zip)

**Comment by eXorus** [comment]
Ok this one is working but I don't know it was possible to have a binary file.

Maybe you could export it to text instead of binary ?

I try something like that (but it's not working):
```php
public function testBinMsg()
    {
        // Init
        $file = __DIR__ . '/mails/hostbuddy.msg';

        $fp = fopen(__DIR__ . '/mails/hostbuddy.msg', 'r');

        $dest = tmpfile();

        mailparse_stream_encode($fp, $dest, "quoted-printable");

        rewind($dest);

        // Affiche le nouveau contenu du fichier
        fpassthru($dest);

        $Parser = new Parser();
        $Parser->setText(fpassthru($dest));

        $Parser->setStream($fp);

        $this->assertEquals(
            'Automatyczna odpowiedź: Piotrze, test z 6 miesięcy nauki ciągle na Ciebie czeka',
            $Parser->getHeader('subject')
        );
    }
```

**Comment by eXorus** [comment]
I think it will be not possible to do it in PHP.
https://stackoverflow.com/questions/18024519/how-to-parse-an-msg-file-in-php

Or maybe with this https://secure.php.net/manual/en/book.com.php
but it's purely a php issue with msg file. 
If you find a solution in PHP or in another language to return a plain text my library will be usable.

**Comment by zenopopovici** [comment]
@eXorus Thanks for your time, for the EML viewer your extension is perfect. Thanks again.
