### ISSUE TITLE
Use of deprecated PHP4 style class constructor in mailparse-stubs.php

### ISSUE THREAD

**Issue by qharnay** [php-mime-mail-parser/php-mime-mail-parser#216]
Hi, 

Im' currently switching my app to PHP7+ , I've updated php-mime-mail-parser to the latest version, but it seems one file remains non PHP7 compliant : mailparse-stubs.php. 

The mimemessage's constructor doesn't comply with PHP7 standards.

TY

Quentin H.

**Comment by eXorus** [comment]
Good remarks.
I don't know this file, are you using it ?

**Comment by qharnay** [comment]
Hi, 

I'm not directly using it. But as part of the library, I guess it could be loaded from within ? 
It was just a remark as I'm sniffing all PHP code in a projet ( with https://github.com/PHPCompatibility/PHPCompatibility )

**Comment by eXorus** [comment]
This file is only for the IDE to understand all methods of mailparse. More information here #91 

It cannot be loaded because it is not in the src directory.

But I keep the issue to test with the new IDE and see if it's still needed.

**Comment by eXorus** [comment]
The file has been remove.

If you need completion for mailparse, just use a more official repository
https://github.com/JetBrains/phpstorm-stubs
