### ISSUE TITLE
Documentation? Can this parse mailbox too?

### ISSUE THREAD

**Issue by jrmgx** [php-mime-mail-parser/php-mime-mail-parser#217]
I found it is not so clear if this lib can parse multiple email in the same file as a mbox file for example,
I'm going to dig in code to check but it could be added to the documentation (and if it is possible indeed an example would be welcome)

Thank you for the good work :)

**Comment by eXorus** [comment]
Hello,

No I don't manage the mbox file. php-mime-mail-parser is only to parse one email.

Sorry for that.

**Comment by JuOliveira93** [comment]
I also needed to parse multiple email from an mbox file and ended up using this [convert_mbox_to_eml_files](https://github.com/uzulla/convert_mbox_to_eml_files)
to parse the mbox file into multiple eml and then used php-mime-mail-parser to do the rest
Hope it helps!

**Comment by eXorus** [comment]
Yes good solution.

**Comment by jrmgx** [comment]
@eXorus don't be sorry :)
Meanwhile I used this small shell command to split the mbox file into individual "email" files

```bash
csplit -f exported/mail -n 8 your.mbox /From\ / {*}
```

note: use gcsplit from coreutils on macosx

it worked like a charm, then I could use your great piece of code on each file (looping over the listing)
