### ISSUE TITLE
getAddresses() gives error: token not valid in ground state

### ISSUE THREAD

**Issue by synio-wesley** [php-mime-mail-parser/php-mime-mail-parser#222]
Hi

This might be related to some of the closed tickets, but I'm using the latest version of the library (3.0.3) and the line: `$parser->getAddresses('to')` returns an error "input is not rfc822 compliant: token not valid in ground state" because of mailparse_rfc822_parse_addresses when the To header has this format: `To: "Testing \" Testing \" Testing" <test@test.com>`

How can I handle this format with your library?

I could prepend the function with @ to make it go through, but then the output will look like this:

```
Array
(
    [0] => Array
        (
            [display] => Testing \ Testing  Testing
            [address] => test@test.com
            [is_group] =>
        )

)
```

As you can see, the quotes are removed. (It's still better than it crashing though..)

Any ideas or help? Thanks!

**Comment by eXorus** [comment]
Hello,

Thanks for your feedback.

I know there are some edge case that are not very well handle by this method but there are many others that are handle correctly.

As discussed here #176 the best way to handle that is to use middleware and add your own regex to format some edge case.
