### ISSUE TITLE
Is this line correct?

### ISSUE THREAD

**Issue by TheCraig** [php-mime-mail-parser/php-mime-mail-parser#223]
Getting an error at this line each time I run:

$Parser->saveAttachments($attach_dir[,$include_inline]);

If I switch out the comma, no error:

$Parser->saveAttachments($attach_dir,[$include_inline]);

The error I get is:

PHP Parse error:  syntax error, unexpected ',', expecting ']'

**Comment by lucasvdh** [comment]
This is probably just a typo in the README example

**Comment by eXorus** [comment]
Thanks but it's correct ;)

It's how we said this second parameter is optional.

For example on the PHP Doc:
https://secure.php.net/manual/fr/function.array-merge.php
` array_merge ( array $array1 [, array $... ] ) : array`
