### ISSUE TITLE
Order of attachments (array)

### ISSUE THREAD

**Issue by fcools** [php-mime-mail-parser/php-mime-mail-parser#225]
Is there any particular order of the attachments in the attachment array which is returned by Parser::getAttachments(), considering an email would have both regular as inline attachments?
E.g. First found = first listed and regular before inline.

**Comment by eXorus** [comment]
Yes the order is the order in the file so no order between inline or regular.

But you can:
$Parser->getAttachments(false) => without inline attachments
$Parser->getAttachments(true) => with inline attachments

**Comment by fcools** [comment]
That's how I currently do it to get inline attachments before regular attachments.
But I thought it could be overhead i.c.o. any of the classes sorts it already.

My actual goal was to get the first inline attachment or if not present, the first regular attachment. But I'm not even sure the order in the file is standardized.

**Comment by eXorus** [comment]
Why do you need to order the attachments ? you can always do that (I didn't test):

```php
function orderByType($a, $b)
{
    if ($a->getContentDisposition() == $b->getContentDisposition()){
        return 0;
    } elseif ($a->getContentDisposition() == 'inline) {
        return -1;
    } else {
        return 1;
    }
}
$attachments = $Parser->getAttachments();
usort($attachments, "orderByType");

```
