### ISSUE TITLE
Opening .msg files

### ISSUE THREAD

**Issue by Caroga** [php-mime-mail-parser/php-mime-mail-parser#226]
I am trying to open a .eml file but without any luck.
I've copied and adapted the code from the following comment provided on a other issue: https://github.com/php-mime-mail-parser/php-mime-mail-parser/issues/194#issuecomment-411636756

```php
<?php

use PhpMimeMailParser\Parser;

require __DIR__.'/../vendor/autoload.php';

$file = __DIR__ . 'test.msg';
$parser = new Parser();
$parser->setPath($file);

var_dump($parser->getHeader('to'));
var_dump($parser->getHeader('from'));
var_dump($parser->getHeader('subject'));
var_dump($parser->getMessageBody('text'));
var_dump($parser->getMessageBody('html'));

```
```bash
# php test.php 
/srv/app/public/test.php:11:
bool(false)
/srv/app/public/test.php:12:
bool(false)
/srv/app/public/test.php:13:
bool(false)
/srv/app/public/test.php:14:
string(0) ""
/srv/app/public/test.php:15:
string(0) ""
```
As you can see this stays empty. I think I might be forgetting something here. Could you assist me ?
I'm also willing to write any documentation to add into this repository in order for future reference regarding how to read .msg files.

Thank you!

-- edit

~~I think it might be something to do with this, cause the .msg files are generated the same way by drag and dropping the mail from within Outlook into the File Explorer. This saves the .eml on disk.
https://github.com/php-mime-mail-parser/php-mime-mail-parser/issues/215~~
Related to https://github.com/php-mime-mail-parser/php-mime-mail-parser/issues/211

**Comment by eXorus** [comment]
Yes I think it's related to binary msg.
You can convert it to eml with https://www.jitbit.com/msg2eml/

Could you provide the file to understand why it's not parsable.

**Comment by Caroga** [comment]
Thank you for responding, sorry for my delayed answer. 
I cannot share the test email I currently have cause they contain addresses from a dutch municipality I currently am working for. I will try to get something as soon as possible.

**Comment by eXorus** [comment]
I'm closing this issue but feel free to reopen it if needed.
You can always share the file with data anonymization.

**Comment by Caroga** [comment]
Hi @eXorus I've got a test msg file from my colleague, it's attached to this post. 

I've noticed that changing the path to the file also makes stuff magically appear on screen. this is my latest addition:

```php
<?php

use PhpMimeMailParser\Parser;

require __DIR__ . '/../vendor/autoload.php';

$file = 'testmail.msg';

$parser = new Parser();
$parser->setPath($file);


print('/////// header TO:' . PHP_EOL);
dump($parser->getHeader('to') . PHP_EOL);

print('/////// header FROM:' . PHP_EOL);
dump($parser->getHeader('from') . PHP_EOL);

print('/////// header SUBJECT:' . PHP_EOL);
dump($parser->getHeader('subject') . PHP_EOL);

print('/////// header TEXT:' . PHP_EOL);
dump(base64_decode($parser->getMessageBody('text')) . PHP_EOL);

print('/////// header HTML:' . PHP_EOL);
dump($parser->getMessageBody('html') . PHP_EOL);
```
dump is from symfony/var-dumper.
Msg file is in .zip. 
[testmail.zip](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/2931188/testmail.zip)

thank you for your time and efforts!

**Comment by Caroga** [comment]
Hi @eXorus I've got a test msg file from my colleague, it's attached to this post. 

I've noticed that changing the path to the file also makes stuff magically appear on screen. this is my latest addition:

```php
<?php

use PhpMimeMailParser\Parser;

require __DIR__ . '/../vendor/autoload.php';

$file = 'testmail.msg';

$parser = new Parser();
$parser->setPath($file);


print('/////// header TO:' . PHP_EOL);
dump($parser->getHeader('to') . PHP_EOL);

print('/////// header FROM:' . PHP_EOL);
dump($parser->getHeader('from') . PHP_EOL);

print('/////// header SUBJECT:' . PHP_EOL);
dump($parser->getHeader('subject') . PHP_EOL);

print('/////// header TEXT:' . PHP_EOL);
dump(base64_decode($parser->getMessageBody('text')) . PHP_EOL);

print('/////// header HTML:' . PHP_EOL);
dump($parser->getMessageBody('html') . PHP_EOL);
```
dump is from symfony/var-dumper.
Msg file is in .zip. 
[testmail.zip](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/2931188/testmail.zip)

thank you for your time and efforts!

**Comment by eXorus** [comment]
But have you still the error ? $parser->getHeader('to') return false.

It's normal the testmail.msg is a binary file and my lib only parse the txt file.
If you convert your testmail.msg to testmail.eml with the link above it works.

**Comment by Caroga** [comment]
So in short, the library cannot decode the binary part of the msg?
Having to convert each .msg to .eml is not an option so I will have to look forward to decoding this in some way. Is this something your library would want to support ?

Thank you for the feedback.

**Comment by eXorus** [comment]
It could be but I didn't find any easy solution in PHP.
https://stackoverflow.com/questions/18024519/how-to-parse-an-msg-file-in-php

How do you get the file ? maybe on your side it's possible to export in another type?
