### ISSUE TITLE
$Parser->getHeader('from') returning only quoted name, not <email address>

### ISSUE THREAD

**Issue by jamminjames** [php-mime-mail-parser/php-mime-mail-parser#228]
`$Parser->getHeader('from');` is returning only quoted name, not the `<email address>` enclosed in brackets, even though both are on one line. The commented example shows that it should.

For example, from this line in the header:
`From: "Joe Guy" <joe@domain.org>`
... the parser only returns "Joe Guy"

The `$Parser->getAddresses('from');` array does include the email address, however.

**Comment by eXorus** [comment]
Could you send the full email, because this is not true.

For example in the test folder, we have this email https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/master/tests/mails/m0001
`From: Name <name@company.com>`

And the results tested are:
```
$this->assertEquals($fromAddressesExpected, $Parser->getAddresses('from'));
```
array(
array(
'display' => 'Name',
'address' => 'name@company.com',
'is_group' => false
)
)

```
$this->assertEquals($fromExpected, $Parser->getHeader('from'));
```
'Name <name@company.com>',

So I think your issue is that getHeader('from') is working but you display it in html so the <...> is escaped.

**Comment by jamminjames** [comment]
How can I send you the email?

**Comment by eXorus** [comment]
Drag and drop in a comment.

**Comment by jamminjames** [comment]
Here you go. 
[Z_email-header.txt](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/2938297/Z_email-header.txt)

**Comment by eXorus** [comment]
Thanks I did a test and it works:

```php
$file = __DIR__ . '/mails/Z_email-header.txt';

$Parser = new Parser();
$Parser->setText(file_get_contents($file));
$Parser->getHeader('from');
$Parser->getAddresses('from');
```
The results are:

> "James Israel, Humor Times" <ht1@dcn.org>

> [[
>     'display' => 'James Israel, Humor Times',
>     'address' => 'ht1@dcn.org',
>     'is_group' => false,
> ]]

So as I said earlier I think your issue is about how you print the email. If you are doing that in a php file:
`echo $email;`
you should do that
`echo htmlspecialchars($email);`

**Comment by jamminjames** [comment]
Well, you're showing the array result. Like I said originally, the `$Parser->getAddresses('from');` array does return the correct result. However, `$Parser->getHeader('from');` is returning only quoted name, not the <email address> enclosed in brackets, even though both are on the same line. The commented example in the instructions shows that it should show both, not as an array, just a single line.

**Comment by eXorus** [comment]
No I show you both getAddresses and getHeader.

And getHeader return:
> "James Israel, Humor Times" <ht1@dcn.org>

And getAddresses return:
> [[
>     'display' => 'James Israel, Humor Times',
>     'address' => 'ht1@dcn.org',
>     'is_group' => false,
> ]]

**Comment by jamminjames** [comment]
Okay, thanks, I'll try using `htmlspecialchars($email);`.
