### ISSUE TITLE
Filtering and altering MIME documents

### ISSUE THREAD

**Issue by jchook** [php-mime-mail-parser/php-mime-mail-parser#235]
Hello,

Do you think this software could be used to (or modified to) alter MIME documents, similar to [`altermime`](https://pldaniels.com/altermime/)?

The requirements would be:

- Edit, add, or remove MIME headers
- Wrap the top-level mime part in a new `multipart/mixed`
- Inject a mime part in the hierarchy
- Print the entire (potentially altered) document with minimal or no formatting and encoding changes to the original (except altered portions).

I have written my own solutions, but concerned about edge cases. I gave a cursory look to the source code, but seeking the opinion of the maintainers, perhaps @eXorus, on the LOE for this functionality.

**Comment by eXorus** [comment]
Hello,

Thanks for your proposition but I don't think that make sense.

php-mime-mail-parser is only to parse email without editing. An email should be immutable.

Why do you need to edit an email? I added "forward email" in https://mailcare.io a few months ago and it was necessary to edit the email to change the receiver. I choose to re-create a new email ...
