### ISSUE TITLE
Does not decode attachment, outputs raw BASE64

### ISSUE THREAD

**Issue by planetchili** [php-mime-mail-parser/php-mime-mail-parser#236]
When calling `saveAttachments` with the following MIME file <fails>, the library outputs a file with the correct name, but whose contents are just the raw BASE64 text from the original MIME file. The attachment can be decoded without issue using a simple desktop utility (Uud32.exe).

Another similar MIME file has its attachment decoded and saved by the library without issue <works>.
[emails.zip](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/3037353/emails.zip)

**Comment by eXorus** [comment]
Sorry for the delay.

I found the issue, the header of the attachment is not good in the failed emails:

**Doesn't work:**
`Content-Transfer-Encoding: base64  ` (2 spaces at the end of the line)

**Works:**
`Content-Transfer-Encoding: base64` (0 space at the end of the line)

**Comment by planetchili** [comment]
Thanks for taking a look at my issue!

For what it is worth, my vote is for a more forgiving, more permissive (less brittle) parser wherever it is viable, regardless of what the standard says.  We can seldom control who or what generates the messages we receive.

For anyone coming here with the same issue, a quick fix for me was simply to call `getContent()` on the attachment and then call `base64_decode()` on the content.

**Comment by eXorus** [comment]
I totally agree with you, I need to trim the value to be able to manage your email.

**Comment by eXorus** [comment]
Fixed in the next version.
Only on master, right now but don't use it, there will be a guide for all the BC.
