### ISSUE TITLE
getHeaders from attachment::getMimePartStr() after bounce transport ?

### ISSUE THREAD

**Issue by Patate79** [php-mime-mail-parser/php-mime-mail-parser#237]
is it possible to get header from attachment::getMimePartStr() ?

because getHeaders is empty where comming from transport_maps 

i use

myhook unix - n n - - pipe
  				flags=F user=www-data argv=/var/www/test.php ${sender} ${size} ${recipient} as in your sample but 

where myhook come from 
transport_maps = regexp:/etc/postfix/redirect.regexp 
that contain /^bounce@example\.com/ myhook:

the way i found to send only bouce thru the test.php script

Thanks

**Comment by eXorus** [comment]
Sorry I didn't get it. Could you show me the content of the file test.php?

From my side I'm able to get the headers from getHeaders().

**Comment by Patate79** [comment]
I attached my test.php (mail sender) and also test2.php the file handling data from myhook in master.cf

master.cf send email data to test2.php using

`
myhook unix - n n - - pipe
flags=F user=www-data argv=/var/www/test2.php ${sender} ${size} ${recipient}
`

where myhook come from
transport_maps = regexp:/etc/postfix/redirect.regexp
and /etc/postfix/redirect.regexp contain /^bounce@example.com/ myhook:

test2.php included contain $email variable who contain the email normally received from myhook using stdin. This way you'll be able to test the result from test2.php directly.

If you run test2.php, you'll get empty getHeaders because all header are received in PhpMimeMailParser\Attachment Object

is there a way to exctract headers from attachment ? Or is it the setup of myhook that is bad ?

Thanks for your time

[test.txt](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/3085274/test.txt)
[test2.txt](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/3085275/test2.txt)

**Comment by eXorus** [comment]
Hi,

Thanks for you last reply it helps me a lot to understand your issue. I don't think I can do something for you.

Your email is composed by:
- Headers
- Part 1 (text/plain)
- Part 2 (message/delivery-status)
- Part 3 (message/rfc822)

PhpMimeMailParser can easily parse the structure of this email and can retrieve the headers, the text and the 2 attachments (Part 2 and Part 3)

You are interesting by 4 params:
- X-mailId inside Part 3 as a header
- Return-Path inside Part 3 as a header
- Status inside Part 2 as a body
- Diagnostic-Code inside Part 2 as a body

This test was successful ($email is your email):
```php

$Parser = new Parser();
$Parser->setText($email);

$this->assertEquals('MAILER-DAEMON@mail.example.com (Mail Delivery System)', $Parser->getHeader('from'));
$this->assertEquals('bounce@example.com', $Parser->getHeader('to'));
$this->assertEquals('Undelivered Mail Returned to Sender', $Parser->getHeader('subject'));
$this->assertEquals('<20190416134805.3746F63A8F@mail.example.com>', $Parser->getHeader('Message-Id'));

$attachments = $Parser->getAttachments();


$part2 = new Parser();
$part2->setText($attachments[0]->getContent());

$this->assertEquals('054E563A88', $part2->getHeader('X-Postfix-Queue-ID'));
$this->assertFalse($part2->getHeader('Status'));

$pattern = '~(?<key>[^:\s]+): (?<value>(?>[^\n]*\R)*?[^\n]*)(?=\R\S+:|$)~';
preg_match_all($pattern, $part2->getMessageBody('text'), $matches, PREG_SET_ORDER);
var_dump($matches);

foreach ($matches as $match){
    if ($match['key'] == 'Status') {
        $status = $match['value'];
    }
    elseif ($match['key'] == 'Diagnostic-Code') {
        $diagCode = $match['value'];
    }
}
$this->assertEquals('5.1.1', $status);
$this->assertEquals('smtp; 550-5.1.1 The email account that you tried to reach does
    not exist. Please try 550-5.1.1 double-checking the recipients email
    address for typos or 550-5.1.1 unnecessary spaces. Learn more at 550 5.1.1
    https://support.google.com/mail/?p=NoSuchUser c5si1141060edi.27 - gsmtp', $diagCode);


$part3 = new Parser();
$part3->setText($attachments[1]->getContent());
$this->assertEquals('1', $part3->getHeader('X-mailId'));
$this->assertEquals('<bounce@example.com>', $part3->getHeader('Return-Path'));


```

**Comment by Patate79** [comment]
This is awesome.

Big thanks
