### ISSUE TITLE
My script is not finding the email

### ISSUE THREAD

**Issue by gsal8** [php-mime-mail-parser/php-mime-mail-parser#241]
I have my email-to-database.php script to parse the email, and when I send a test email to the email address that pipes to the parsing script, I get the following back in the email.  

```
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  pipe to |/home/myusername/public_html/email-to-database.php
    generated by request@mydomain.com
    local delivery failed

The following text was generated during the delivery attempt:

------ pipe to |/home/myusername/public_html/email-to-database.php
       generated by request@mydomain.com ------

PHP Warning:  mailparse_msg_parse_file(path/to/email.eml): failed to open stream: No such file or directory in /home/myusername/public_html/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php on line 123
PHP Warning:  fopen(path/to/email.eml): failed to open stream: No such file or directory in /home/myusername/public_html/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php on line 124
PHP Warning:  mailparse_msg_get_structure() expects parameter 1 to be resource, boolean given in /home/myusername/public_html/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php on line 211
PHP Warning:  Invalid argument supplied for foreach() in /home/myusername/public_html/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php on line 213
PHP Fatal error:  Uncaught PhpMimeMailParser\Exception: setPath() or setText() or setStream() must be called before retrieving email headers. in /home/myusername/public_html/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php:238
Stack trace:
#0 /home/myusername/public_html/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php(253): PhpMimeMailParser\Parser->getRawHeader('to')
#1 /home/myusername/public_html/email-to-database.php(23): PhpMimeMailParser\Parser->getHeader('to')
#2 {main}
  thrown in /home/myusername/public_html/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php on line 238
```

And this is what I have at the top of my parsing script. I assume something has to be wrong here, but not sure what:

```
#!/usr/local/bin/php -q
<?php
require_once("includes/connection.php");
require_once("includes/functions.php");
// If you're using Composer, use Composer's autoload:
require_once __DIR__.'/vendor/autoload.php';
require 'phpmailer/PHPMailerAutoload.php';

$path = 'path/to/email.eml';
$parser = new PhpMimeMailParser\Parser();

```
NOTE:  I omitted the rest of the parsing code since the issue is with the part above, where it isn't even seeing the email.

Anyone see anything that I might be doing wrong?

**Comment by eXorus** [comment]
I don't understand your parsing script.

Why do you have a local variable $path with the value 'path/to/email.eml'?

I think you should change the $path with a correct one.

**Comment by gsal8** [comment]
Sorry, I clearly am not understanding the email path portion of this,  When I send the email, it's definitely triggering my script so to speak, but how exactly does my script "see" the email that came in.  If there is a path pointing to the email, wouldn't that mean the email has to be saved somewhere first?  I was under the impression it did everything on the fly without ever "saving" the email.

Basically, I have no idea what to put as the "correct" path because I don't know where I should be looking for the email :(  Does it maybe automatically go somewhere on my server, so I need to ask my host where that path is?  Or is it a path I can determine myself?

Does any of this make sense?  Probably not haha.

I know newbies are annoying but if anyone could explain the "path" part a little more, I would really appreciate it.

**Comment by eXorus** [comment]
You have to take the email with this:
`$parser->setStream(fopen("php://stdin", "r"));`

**Comment by gsal8** [comment]
Thank you.  I misunderstood the instructions below about loading an email.  I thought you could use ANY of the 4, so I just used #1, but now I realize each one serves a different purpose and the one for reading a piped email "on the fly" so to speak, is #4.  And it now works for me.  Sorry for not realizing and thank you so much making me see the light :)
```

Loading an email

You can load an email with 4 differents ways. You only need to use one of the following four.

require_once __DIR__.'/vendor/autoload.php';

$path = 'path/to/email.eml';
$parser = new PhpMimeMailParser\Parser();

// 1. Specify a file path (string)
$parser->setPath($path); 

// 2. Specify the raw mime mail text (string)
$parser->setText(file_get_contents($path));

// 3. Specify a php file resource (stream)
$parser->setStream(fopen($path, "r"));

// 4.  Specify a stream to work with mail server (stream)
$parser->setStream(fopen("php://stdin", "r"));
```
```
