### ISSUE TITLE
I can't get attachments to save to my folder

### ISSUE THREAD

**Issue by gsal8** [php-mime-mail-parser/php-mime-mail-parser#243]
I have everything working except the attachments part.  Here is the code in my piped email script:

```
// If you're using Composer, use Composer's autoload:
require_once __DIR__.'/vendor/autoload.php';

$parser = new PhpMimeMailParser\Parser();

$parser->setStream(fopen("php://stdin", "r"));

//Get the metadata of the message
//Get the sender and the receiver:

$rawHeaderTo = $parser->getHeader('to');
// return "test" <test@example.com>, "test2" <test2@example.com>

$arrayHeaderTo = $parser->getAddresses('to');
// return [["display"=>"test", "address"=>"test@example.com", false]]

$rawHeaderFrom = $parser->getHeader('from');
// return "test" <test@example.com>

$arrayHeaderFrom = $parser->getAddresses('from');
// return [["display"=>"test", "address"=>"test@example.com", "is_group"=>false]]
$from=$arrayHeaderFrom[0]['address'];


//Get the subject:
$subject = $parser->getHeader('subject');

//Get other headers:
$stringHeaders = $parser->getHeadersRaw();
// return all headers as a string, no charset conversion

$arrayHeaders = $parser->getHeaders();
// return all headers as an array, with charset conversion


//Get the body of the message
$text = $parser->getMessageBody('text');
// return the text version

$html = $parser->getMessageBody('html');
// return the html version

$htmlEmbedded = $parser->getMessageBody('htmlEmbedded');
// return the html version with the embedded contents like images

//Get attachments
//Save all attachments in a directory
$parser->saveAttachments('/home/myusername/public_html/attachments');
```

And if I send a test email to it with an attachment, I get the following:

> PHP Warning:  fopen(https://www.myusername.com/attachments/5G.jpg): failed to open stream: HTTP wrapper does not support writeable connections in /home/myusername/public_html/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Attachment.php on line 222
> PHP Fatal error:  Uncaught PhpMimeMailParser\Exception: Could not write attachments. Your directory may be unwritable by PHP. in /home/myusername/public_html/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Attachment.php:229

NOTE:  I made sure the attachments folder has full permissions (0755), so I can't figure out what I'm doing wrong.  Any ideas?

Thanks,

**Comment by eXorus** [comment]
No I don't have any idea.
Is it working for another email with another attachment? because I don't understand how an attachment could be an URL https://www.myusername.com/attachments/5G.jpg...

Do you have the raw email?

**Comment by gsal8** [comment]
Ugh, I had a typo in my attachment path, so sorry I didn't catch that.  I now have it saving attachments properly.  This is such a great script, thanks so much for sharing/maintaining!
