### ISSUE TITLE
Class 'Parser' not found?

### ISSUE THREAD

**Issue by gsal8** [php-mime-mail-parser/php-mime-mail-parser#244]
I had everything working using this bit for my atttachments:

```
$parser->saveAttachments('/home/user/public_html/attachments');
// return all attachments saved in the directory (include inline attachments)
```
It correctly saved attachments in my directory.  And when I tried multiple attachments, it saved them as well.  The only issue I saw was that for inline images that had the same name, it would save the first one as "image.png" (and it was fine) but it saved the next one as "image.pnghUj6NH" (this image obviously didn't open and there are random characters after ".png")

So I then tried switching to this one, thinking it would solve the issue above by just adding a suffix BEFORE the file extension for duplicate attachments:

```
// Save all attachments with the strategy ATTACHMENT_DUPLICATE_SUFFIX (default)
$parser->saveAttachments('/home/user/public_html/attachments', false, Parser::ATTACHMENT_DUPLICATE_SUFFIX);
// return all attachments saved in the directory: logo.jpg, logo_1.jpg, ..., logo_100.jpg, YY34UFHBJ.jpg
```
However, when I tested this way, my email test got sent back with this error:

> PHP Fatal error:  Uncaught Error:  Class 'Parser' not found in /home/user/public_html/my-script.php:57

Any idea why class 'Parser' might not be found?

**Comment by eXorus** [comment]
Hello,

We changed something in the last version about attachments.

Take the last version 5.0.1 of the lib.

The first version should work as expected:
`$parser->saveAttachments('/home/user/public_html/attachments');`
- save all the inline attachments because the second parameter is by default include_inline=true
- save with a suffix before the file extension because the third parameter es by default fileNameStrategy=ATTACHMENT_DUPLICATE_SUFFIX

Your second version should also work, **it's just PHP**. You added  Parser::ATTACHMENT_DUPLICATE_SUFFIX so PHP need to know what is PHP so you need to import the class. 2 options:
```
$parser = $parser = new PhpMimeMailParser\Parser();
// .... import the email
$parser->saveAttachments('/home/user/public_html/attachments', false, PhpMimeMailParser\Parser::ATTACHMENT_DUPLICATE_SUFFIX);
```
or
```
use PhpMimeMailParser\Parser;
$parser = $parser = new Parser();
// .... import the email
$parser->saveAttachments('/home/user/public_html/attachments', false, Parser::ATTACHMENT_DUPLICATE_SUFFIX);
```

**Comment by gsal8** [comment]
Hi,
I updated the Attachment.phph file to the 5.0.1 version and it saves the attachment to my server folder, but it's still naming them funny, with the random characters AFTER the file extension.  Have you seen this before?

Example:  image.pngIGcQ63

**Comment by eXorus** [comment]
Hi,

It's not possible are you sure that you import the correct file?

You should use composer to import the lib.

**Comment by gsal8** [comment]
Hi,
I deleted everything and reinstalled by running:

`composer require php-mime-mail-parser/php-mime-mail-parser`

Everything installed again, but it's still saving my attachments with odd names, i.e. image.pngWeLIPL
NOTE:  This is just when it's an inline attachment.  If I attach a PDF of something, it saves that attachment with the filename it already had.

FYI, the date associated with the files composer just installed is March 19th.  Is that the newest stuff?  If not, how do I force composer to get the newest version?

Finally, I am on PHP version 7.0, in case that changes anything.

Any thoughts?

Thanks!

**Comment by eXorus** [comment]
Ok I understand.

`composer show -i | grep php-mime-mail-parser`
You should see your version: 3.0.4

The last version is 5.0.1 but it's not compatible from PHP 7.1.

No choice to upgrade the PHP version if you want to have the correct name or save all attachments in another directory to keep the good name and don't have duplicate name.

**Comment by gsal8** [comment]
Yes, it does show 3.0.4.  I will check with my host about upgrading my PHP version.  As long as I can upgrade to at least PHP 7.1, then composer would install 5.0.1, correct?

Just want to confirm before I upgrade anything.

Thanks for your help!

**Comment by eXorus** [comment]
Yes PHP 7.1 is fine.

**Comment by gsal8** [comment]
Hi, I was able to upgrade to 7.1 and the naming works properly now, thanks so much for helping me.

One more questions if you don't mind. When an email is sent to my piping/parsing script, inline attachments are now saving properly like image.png, image_1.png, image_2.png etc. and my script also sends an email to myself, in which I'd like to list out links to the attachments just submitted (so that I could click them to view the attachments easily).  I was trying it this way:
```

// Save all attachments
$parser->saveAttachments('/home/myusername/public_html/attachments');

$attachments = $parser->getAttachments();
// return an array of all attachments (include inline attachments)
$a=0;
foreach ($attachments as $attachment) {
	$attachmentlink="https://mydomain.com/attachments/".$attachment->getFilename()."";
	$linklist .= "<br><a href='".$attachmentlink."' target='_blank'>Attachment-".$a."</a><br>";
	$a++;
}
// in the email I send to myself I have:
Attachments=$linklist<br><br>

```
The problem is that the filenames returned for all inline attachments are all "image.png," not the newly renamed versions.  In other words, if someone sends three inline attachments to my script, they properly get saved as:

image.png
image_1.png
image_2.png

But in my email, the link for ALL THREE images is:
https://mydomain.com/attachments/image.png

Whereas I would like the 2nd link to be:
https://mydomain.com/attachments/image_1.png

And the 3rd link to be:
https://mydomain.com/attachments/image_2.png

Is there any way around this?  Maybe I have to use another approach entirely to call to a directory and take all the images that were just saved within the last minute or something and return their actual filenames.

Mainly just curious if your program can handle this or if it's just not an option?

Thanks!

**Comment by eXorus** [comment]
Could you send me an example because I don't understand how an inline attachment can have a duplicated name. If there is a duplicated name for an inline attachment it's impossible to choose between the 2 images.

**Comment by gsal8** [comment]
Sorry, I probably didn't explain it right. Just to be clear, your script is doing what it's supposed to as far as saving. If I email 3 inline attachments, it properly saves them to the server with 3 different names (image.png, image_1.png, image_2.png).

I'm just trying to figure out how I can retrieve those 3 different file names immediately after they are saved to my server, so I can email myself links to them.  It's very possible that your script doesn't handle that and I need to pursue another method, was just curious.

In other words, when I use this code below, it returns "image.png" as the filename for all three inline attachments, even though it saved the attachments to my server with different names (image.png, image_1.png, image_2.png).

```
foreach ($attachments as $attachment) {
    echo 'Filename : '.$attachment->getFilename().'<br />';
    // return logo.jpg
    
    echo 'Filesize : '.filesize($attach_dir.$attachment->getFilename()).'<br />';
    // return 1000
    
    echo 'Filetype : '.$attachment->getContentType().'<br />';
    // return image/jpeg
    
    echo 'MIME part string : '.$attachment->getMimePartStr().'<br />';
    // return the whole MIME part of the attachment

    $attachment->save('/path/to/save/myattachment/', Parser::ATTACHMENT_DUPLICATE_SUFFIX);
    // return the path and the filename saved (same strategy available than saveAttachments)
}
```

**Comment by eXorus** [comment]
$nameSaved ?

```php
foreach ($attachments as $attachment) {
    echo 'Filename : '.$attachment->getFilename().'<br />';
    // return logo.jpg
    
    echo 'Filesize : '.filesize($attach_dir.$attachment->getFilename()).'<br />';
    // return 1000
    
    echo 'Filetype : '.$attachment->getContentType().'<br />';
    // return image/jpeg
    
    echo 'MIME part string : '.$attachment->getMimePartStr().'<br />';
    // return the whole MIME part of the attachment

    $nameSaved = $attachment->save('/path/to/save/myattachment/', Parser::ATTACHMENT_DUPLICATE_SUFFIX);
    // return the path and the filename saved (same strategy available than saveAttachments)
}
```

**Comment by gsal8** [comment]
$nameSaved took care of it.  You are a smart man, thanks for your help!
