### ISSUE TITLE
Problème d'instanciation de la classe parser()

### ISSUE THREAD

**Issue by Emmaherve** [php-mime-mail-parser/php-mime-mail-parser#246]
Bonjour, lorsque j'essaye d'instancier la classer Parser() : $parser = new PhpMimeMailParser\Parser(); cela provoque une erreur 500... Je ne vois pas pourquoi, j'ai suivi le README et tout semble fonctionner mise à part ça. 
Avez-vous une idée d'où l'erreur pourrait provenir ? 
Merci d'avance

**Comment by eXorus** [comment]
Bonjour,

Quand on a une erreur 500 il faut regarder dans les logs pour avoir l'erreur exact.

As tu bien importé PhpMimeMailParser?

**Comment by eXorus** [comment]
Je clos le ticket mais si tu as plus d'information tu peux le rouvrir.
