### ISSUE TITLE
Content-Type: text/plain; (error)

### ISSUE THREAD

**Issue by stahe** [php-mime-mail-parser/php-mime-mail-parser#247]
Merci pour cet excellent programme. J'ai un message .eml qui a un attachement .eml qui lui-même a un attachement .eml, ... C'est le même message enroulé quatre fois sur lui-même. Le message [message/rfc822] le plus interne a un PDF attaché. Lorsque je récupère l'ensemble et que je parcours les attachements de façon récursive avec votre projet, j'obtiens un attachement inattendu de type [**Content-Type: text/plain; (error)**]. A quoi cela correspond-t-il ? J'obtiens bien les autres différents attachements .eml et le plus interne l'attachement .pdf.

Serge Tahé

**Comment by eXorus** [comment]
Bonjour,

Je veux bien regarder mais pour cela il me faudrait le fichier eml afin de comprendre le comportement. Peux tu me l'envoyer ou le glisse-déposer ici ?

J'ai l'impression qu'on est peut etre dans ce cas: https://github.com/php-mime-mail-parser/php-mime-mail-parser/issues/194

**Comment by stahe** [comment]
Bonjour Vincent,

Le fichier eml est joint. Avec ton code, il me donne la liste suivante 
des attachements :

--Content-Type=application/vnd.openxmlformats-officedocument.wordprocessingml.document
--Content-Type=application/pdf
--Content-Type=application/vnd.oasis.opendocument.text
--Content-Type=image/png
--Content-Type=message/rfc822
--Content-Type=application/vnd.openxmlformats-officedocument.wordprocessingml.document
--Content-Type=application/pdf
--Content-Type=application/vnd.oasis.opendocument.text
--Content-Type=image/png
--Content-Type=message/rfc822
--Content-Type=application/vnd.openxmlformats-officedocument.wordprocessingml.document
--Content-Type=application/pdf
--Content-Type=application/vnd.oasis.opendocument.text
--Content-Type=image/png
--Content-Type=text/plain; (error)

Le fichier eml consiste en un message enroulé trois fois sur lui-même. 
Tu peux voir que mon code trouve un attachement de type 
[Content-Type=text/plain; (error)]. Si le message est enroulé seulement 
deux fois sur lui-même, cet attachement n'apparaît pas. S'il est enroulé 
quatre fois sur lui-même, il apparaît dans chacun des deux enroulements 
les plus internes. Je n'exclus pas une erreur dans mon propre code.

Merci d'avance de ta réponse. Je n'ai pas d'urgence.

Serge Tahé
==
------ Message d'origine ------
De: "Vincent Dauce" <notifications@github.com>
À: "php-mime-mail-parser/php-mime-mail-parser" 
<php-mime-mail-parser@noreply.github.com>
Cc : "stahe" <serge.tahe@gmail.com>; "Author" 
<author@noreply.github.com>
Envoyé : 27/05/2019 06:31:04
Objet : Re: [php-mime-mail-parser/php-mime-mail-parser] Content-Type: 
text/plain; (error) (#247)

**Comment by stahe** [comment]
Bonjour Vincent,

Je joins un complément d'information à mon mail précédent. J'ai modifié 
légèrement mon code pour enregistrer les différents attachements trouvés 
dans le fichier eml de façon récursive et j'ai vérifié le fichier eml le 
plus interne. Il n'y a pas d'attachement de type [text/plain; (error)]. 
Donc apparemment, cette anomalie ne vient pas du code eml lui-même.

Serge Tahé
==

------ Message d'origine ------
De: "Vincent Dauce" <notifications@github.com>
À: "php-mime-mail-parser/php-mime-mail-parser" 
<php-mime-mail-parser@noreply.github.com>
Cc : "stahe" <serge.tahe@gmail.com>; "Author" 
<author@noreply.github.com>
Envoyé : 27/05/2019 06:31:04
Objet : Re: [php-mime-mail-parser/php-mime-mail-parser] Content-Type: 
text/plain; (error) (#247)

**Comment by stahe** [comment]
Bonjour Vincent,

J'ai regardé votre code et j'ai commenté une partie me semblant 
"suspecte" (par rapport au fichier eml qui présentait l'erreur) dans la 
classe [Parser] :


Cela a résolu mon problème : j'ai bien tous les attachements de chaque 
fichier [eml] encapsulé sans jamais rencontrer l'anomalie [Content-Type: 
text/plain; (error)].

Serge Tahé
====================================
------ Message d'origine ------
De: "Vincent Dauce" <notifications@github.com>
À: "php-mime-mail-parser/php-mime-mail-parser" 
<php-mime-mail-parser@noreply.github.com>
Cc : "stahe" <serge.tahe@gmail.com>; "Author" 
<author@noreply.github.com>
Envoyé : 27/05/2019 06:31:04
Objet : Re: [php-mime-mail-parser/php-mime-mail-parser] Content-Type: 
text/plain; (error) (#247)

**Comment by eXorus** [comment]
Bonjour,

Dans aucun des emails que tu me donnes je ne vois de fichiers attachés, est ce normal?

Dans ton dernier message tu dis que tu que tu as commenté mon code dans la class parser, mais tu n'indiques pas quoi et ou. Est ce un oubli?

Donc pour conclure je vais avoir du mal à t'aider et je ne sais même pas si tu as encore besoin d'aide ou si tu as réussi et je peux clore ce bug.

**Comment by stahe** [comment]
Bonjour Vincent,

Tout cela est bien bizarre. J'ai vérifié : je t'ai bien joint le fichier 
.eml que j'étais en train d'analyser et qui a produit le bug pour lequel 
je t'ai écrit. Dans mon dernier mail, j'avais inclus dans le mail une 
image qui montrait le code que j'avais commenté.

Je résume : dans le code de [Parser], à un moment tu considères que si 
le content-type est "multipart" alors tu as affaire à un attachement. Ce 
qui n'était pas le cas dans le mail que j'analysais. J'ai donc commenté 
ce code et l'erreur a disparu. Je te joins de nouveau la copie d'écran 
que j'avais faite. J'espère que cette fois-ci tu l'auras.

Comme je te l'ai dit dans mon dernier mail, grâce à cette modification, 
mon problème est résolu mais ça me semble quand même une anomalie que tu 
devrais regarder de plus près.

Merci pour ton code qui m'a bien servi.

Serge Tahé

Pièces jointes : un rar qui contient et la copie décran montrant le bug 
et le fichier .eml qui a montré le bug

Au cas où : le code qui me semble bogué (lignes 525-537 de la classe 
Parser) :

             } elseif (in_array($part['content-type'], 
$non_attachment_types, true)
                 && $disposition !== 'attachment') {
                 // it is a message body, no attachment
                 continue;
             }
             // correction Serge Tahé - mise en commentaires de la partie 
multipart
             //elseif (substr($part['content-type'], 0, 10) !== 
'multipart/') {
             // if we cannot get it by getMessageBody(), we assume it is 
an attachment
             //$disposition = 'attachment';
             //}
             if (in_array($disposition, ['attachment', 'inline']) === 
false && !empty($disposition)) {
                 $disposition = 'attachment';
             }
==


------ Message d'origine ------
De: "Vincent Dauce" <notifications@github.com>
À: "php-mime-mail-parser/php-mime-mail-parser" 
<php-mime-mail-parser@noreply.github.com>
Cc : "stahe" <serge.tahe@gmail.com>; "Author" 
<author@noreply.github.com>
Envoyé : 31/05/2019 06:24:35
Objet : Re: [php-mime-mail-parser/php-mime-mail-parser] Content-Type: 
text/plain; (error) (#247)

**Comment by eXorus** [comment]
@stahe Effectivement les pièces jointes ne passent pas par email.

Tu devrais plutôt répondre via github que par email. Car sur github tu peux mettre des blocs de codes, glisser/déposer des fichiers...
Car là ton dernière message par email qui apparait sur Github est pas très lisible.

**Comment by stahe** [comment]
OK, je recommence à partir de Github.

Je résume : dans le code de [Parser], à un moment tu considères que si le content-type est "multipart" alors tu as affaire à un attachement. Ce qui n'était pas le cas dans le mail que j'analysais. J'ai donc commenté ce code et l'erreur a disparu. Je te joins de nouveau la copie d'écran que j'avais faite. J'espère que cette fois-ci tu l'auras. Comme je te l'ai dit dans mon dernier mail, grâce à cette modification, mon problème est résolu mais ça me semble quand même une anomalie que tu devrais regarder de plus près. Merci pour ton code qui m'a bien servi.

Serge Tahé

Pièces jointes : un zip qui contient et la copie d'écran montrant le bug et le fichier .eml qui a montré le bug
[php-mime-mail-parser.zip](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/3241320/php-mime-mail-parser.zip)

**Comment by eXorus** [comment]
C'est préférable d'utiliser le système des pull request de github pour partager ton code et tes modifications au lieu d'utiliser une capture d'écran.
J'ai fait une pull request à ta place et tu peux voir que ton correctif casse 4 tests existants. Par example un email avec un fichier attaché de type calendrier ne sera pas reconnu.

J'ai aussi ajouté un test pour décoder ton email: testGetPdfInsideMultipleEmails et je ne constate pas de problème particulier enfin à toi de me dire le fichier pdf que tu souhaites récupérer.

Avec ton correctif
- un email de guest@localhost avec comme body 'ligne 1'
- puis 5 fichiers attachés
Hello from SwiftMailer.docx
Hello from SwiftMailer.pdf
Hello from SwiftMailer.odt
Cours-Tutoriels-Serge-Tahé-1568x268.png
test-localhost.eml

si je continue à décoder le dernier eml et le rajoute dans un nouveau parser j'ai un email toujours de guest@localhost avec comme body 'invité' puis 4 fichiers attachés:
- Hello from SwiftMailer.docx
- Hello from SwiftMailer.pdf
- Hello from SwiftMailer.odt
- Cours-Tutoriels-Serge-Tahé-1568x268.png


A l'inverse sans ton correctif j'obtiens exactement la meme chose sauf que j'ai pour le premier email 6 fichiers attachés au lieu de 5.
Le fichier attaché supplémentaire ne semble pas avoir de nom donc c'est noname1.

Si le pdf que tu essayes de récupérer est 'Hello from SwiftMailer.pdf' alors dans les deux cas j'arrive à le récupérer.

**Comment by stahe** [comment]
Bonjour Vincent,

Je ne suis pas étonné que ma correction ne passe pas certains tests. Ce 
n'était pas le but : je pensais bien que c'était une rustine propre à 
mon problème particulier et c'est pourquoi je t'ai conseillé d'y 
regarder de plus près. Avec le test [testGetPdfInsideMultipleEmails], tu 
es arrivé aux mêmes conclusions que moi : Il y a un attachement de trop 
[noname1] de type [text/plain (error)]. C'est ce qui avait motivé ma 
question initiale car cet attachement n'existe pas dans le mail analysé 
(tu ne le trouves nulle part dans les textes eml des différents mails 
imbriqués). Il n'a donc pas de nom et ton code le nomme [noname1]. C'est 
comme ça que j'ai repéré le code concerné dans [Parser]. Si tu 
poursuivais l'imbrication de mails (je l'ai fait), tu verrais que de 
nouveaux attachements [text/plain (error)] nommés (nonamex) apparaissent 
et ils n'existent toujours pas.

Sur le mail analysé il y a des parties [multipart/mixed], 
[multipart/alternative] et si j'ai bien compris ton code, il les 
assimile à des attachements. C'est pourquoi j'ai commenté cette partie 
de code, ce qui a effectivement supprimé l'erreur des attachements 
(nonamex). Mais je comprends bien que c'est une rustine locale.

Je voulais écrire un client de mail capable de parser des mails 
imbriqués et de sauvegarder tous les attachements qu'ils contenaient.

Merci pour l'information et le temps consacré à ma question.

Cordialement,

Serge
==

------ Message d'origine ------
De: "Vincent Dauce" <notifications@github.com>
À: "php-mime-mail-parser/php-mime-mail-parser" 
<php-mime-mail-parser@noreply.github.com>
Cc : "stahe" <serge.tahe@gmail.com>; "State change" 
<state_change@noreply.github.com>
Envoyé : 04/06/2019 08:40:24
Objet : Re: [php-mime-mail-parser/php-mime-mail-parser] Content-Type: 
text/plain; (error) (#247)

**Comment by eXorus** [comment]
Ok j'ai compris ton problème et je constate la même chose que toi.

Je vais corriger car d'après moi c'est pas normal. Je ne connais pas encore la cause de ce fichier attaché en plus mais je vais regarder.

Merci.
Pour info j'ai moi aussi créé un webmail qui permet de sauvegarder automatiquement les fichiers attachés. https://mailcare.io

**Comment by eXorus** [comment]
C'est corrigé dans la version 5.0.2.

Merci beaucoup pour ton rapport de bug.

**Comment by stahe** [comment]
Merci Vincent pour ton travail. Je vais tester la nouvelle version.

Serge Tahé
==

------ Message d'origine ------
De: "Vincent Dauce" <notifications@github.com>
À: "php-mime-mail-parser/php-mime-mail-parser" 
<php-mime-mail-parser@noreply.github.com>
Cc : "stahe" <serge.tahe@gmail.com>; "State change" 
<state_change@noreply.github.com>
Envoyé : 06/06/2019 07:17:20
Objet : Re: [php-mime-mail-parser/php-mime-mail-parser] Content-Type: 
text/plain; (error) (#247)

**Comment by stahe** [comment]
J'ai testé la nouvelle version avec le problème particulier qui avait 
soulevé ma question. Cette fois-ci c'est bon : pas d'attachements 
[nonamex] en trop. Merci et bonne continuation avec ce projet.

Serge Tahé
==
------ Message d'origine ------
De: "serge.tahe@gmail.com" <serge.tahe@gmail.com>
À: "php-mime-mail-parser/php-mime-mail-parser" 
<reply@reply.github.com>
Envoyé : 06/06/2019 08:16:59
Objet : Re[2]: [php-mime-mail-parser/php-mime-mail-parser] Content-Type: 
text/plain; (error) (#247)
