### ISSUE TITLE
Missing handling of unsafe characters for attachments

### ISSUE THREAD

**Issue by robinnydahl** [php-mime-mail-parser/php-mime-mail-parser#250]
When attachments are handled there is no sanitation done for new lines. This means that attachments can have filenames including linebreaks.

This causes an issue down the line when that file is served from the an application that has taken use of the filename. HTTP headers don't support linebreaks and this results in an exception. (Ref: `RFC2616`)

This can be solved by updating the regex that escapes all potentially unsafe characters from the filename in `Parser.php`.

Please see my PR for a purposed fix.

**Comment by robinnydahl** [comment]
Pull request made at #251

**Comment by eXorus** [comment]
Hello @robinnydahl 

Could you provide me the raw email because I can't reproduce.

As you said header doesn't accept line breaks so I can't have a raw email with a filename with a line break because it's in a header.

**Comment by robinnydahl** [comment]
Hey @eXorus,

Sure thing, I'll see if I manage to re-make an attachment as the original one includes some sensitive information.

I'll ping you.

**Comment by robinnydahl** [comment]
Hi again @eXorus!

Attached is a raw email that cause the issue, I've replaced the actual PDF with a small image instead. Let me know if you need anything else from me.

[grbgb25v704p3dv7veb75kt3dq7tvl580439da01.txt](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/3491360/grbgb25v704p3dv7veb75kt3dq7tvl580439da01.txt)

**Comment by eXorus** [comment]
Fix in 5.0.3
