### ISSUE TITLE
Charset errors introduced in 5.0.1

### ISSUE THREAD

**Issue by tpetry** [php-mime-mail-parser/php-mime-mail-parser#252]
Version 5.0.0 worked perfectly but with 5.0.1 i get charset decoding errors for the exact same mails which worked with the older version:

```
   ErrorException  : iconv(): Detected an illegal character in input string

  at /home/myproject/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Charset.php:334
    330|                 return mb_convert_encoding($encodedString, 'utf-8', $charset);
    331|             }
    332|         }
    333|
  > 334|         return iconv($charset, 'utf-8//translit//ignore', $encodedString);
    335|     }
    336|
    337|     /**
    338|      * {@inheritdoc}

  Exception trace:

  1   iconv("gb2312", "utf-8//translit//ignore", "�Τ������ߤޤ��ϥ���`�פؤ����Ť�ʧ�����ޤ���: [....]
")
      /home/myproject/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Charset.php:334

  2   PhpMimeMailParser\Charset::decodeCharset("�Τ������ߤޤ��ϥ���`�פؤ����Ť�ʧ�����ޤ���: [....]

", "gb2312")
      /home/myproject/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php:492
```

**Comment by eXorus** [comment]
Hello @tpetry 

Could you provide me the raw email? I'm going to take a look.

**Comment by tpetry** [comment]
Sorry I haven't reacted in a while, but there were other things I had to take care of.

The problem is difficult to reproduce as it does not occur with every PHP installation. I have tried the same mail on several servers with the same PHP minor version (7.2) with the result that it works on some and not on some. I guess it's the iconv version:

With version 1.11 (libiconv) it works, with version 2.17 (glibc iconv) it doesn't. I also [found someone on Stackoverflow](https://stackoverflow.com/questions/54988081/why-php-iconv-function-in-server-throw-exception) with the same problem.

I have attached a minimized mail which shows the charset problem. The mail is no longer valid, parsing it results in one of 2 errors:
* iconv decode error (the bug I reported)
* other PHP error (decoding works, mail is just too destroyed to be handled correctly)

[failure.eml.txt](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/3533558/failure.eml.txt)

**Comment by eXorus** [comment]
In local the PR #260 works but in the CI it's KO with `iconv(): Detected an illegal character in input string`

I used this cmd `php -i | grep "iconv impl"`:
local: libiconv
CI: glibc

I don't know the charset `gb2312` but it's not in the list of mb_list_encodings() that's why t doesn't work anymore with the 5.0.1
That's bad... because I think it can be decoded by mb_convert_encoding

**Comment by eXorus** [comment]
I think I have a good fix from https://www.php.net/manual/en/function.mb-list-encodings.php

mb_convert_encoding() doesn't return all the supported like `gb2312` we have to add the aliases to have it.

The PR works, I should be able to release it.

**Comment by eXorus** [comment]
The version 5.0.4 should fix this issue.
