### ISSUE TITLE
Load email with imap?

### ISSUE THREAD

**Issue by iwasherefirst2** [php-mime-mail-parser/php-mime-mail-parser#262]
In the [docs I found 4 ways](https://github.com/php-mime-mail-parser/php-mime-mail-parser#loading-an-email) how to load an email.

However, I don't quite understand how to use them, since I have no `.eml` file or something like that. 

Instead, I currently use something like this to access my emails:

    $inbox     = imap_open($hostname,$username,$password) or die('Cannot connect to mailbox: ' . imap_last_error());

Actually all I wanted was to get the body content of a mail. But then I realized that `imap_fetchbody` has some issues (https://www.php.net/manual/en/function.imap-fetchbody.php#89002).

Is it possible to parse the email with this package, when I have an imap_connection and the email number?

**Comment by lucasvdh** [comment]
The `php-mime-mail-parser` package requires a string, file or stream to parse an email. How you fetch the content of an email is up to you.

If you're using the `php-imap` extension you could do this:
```php
$parser = new PhpMimeMailParser\Parser();
$parser->setText(imap_fetchbody($connection, $uid, '', FT_UID));
```

**Comment by iwasherefirst2** [comment]
Allright, but I am looking for a package so I don't have to cope with `imap_fetchbody`. 

I found the package I was looking for here: https://github.com/tedious/Fetch

**Comment by eXorus** [comment]
Sorry I was in vacation but I'm very happy to see that @lucasvdh did the support for me :)
Thanks.
