### ISSUE TITLE
getHeader fail to get value on a newline

### ISSUE THREAD

**Issue by MrTasken** [php-mime-mail-parser/php-mime-mail-parser#264]
I received a message with the Message-IDs value on a new line like this:

Message-ID:
 &nbsp;&lt;xxx&gt;

The message id was on a new line because it was long. The RFC allows this(newline+space), but the `$parser->getHeader('Message-ID')` doesn't return the value.

Edit: Code tag failed to display newline correctly...

**Comment by eXorus** [comment]
Hello,

Could you give me the full raw email to check?
Because on my side it works.

```
Message-ID:
  <20050430192829.0489.name@company.com>
```

**Comment by MrTasken** [comment]
It is working in my raw tests as well (when copying the email to a file and parsing that). Guess it is not a fault with your library after all. Hard to debug, I'm parsing a mail directly from an IMAP stream, but somehow the message-id doesn't get parsed. The Message-ID on a newline was the only difference I could see from any other email from the stream (that is working fine).
