### ISSUE TITLE
add "composer install" in installation composer installation 

### ISSUE THREAD

**Issue by 0x25** [php-mime-mail-parser/php-mime-mail-parser#266]
Hello

Is it possible to update the composer install help, something more like this:

    apt install composer
    composer require php-mime-mail-parser/php-mime-mail-parser
    composer install

I lost time to found the last command :)

**Comment by eXorus** [comment]
Hello, 

I'm not sure it's useful composer is a common tool for PHP and there is already a nice explication if you follow the link.
https://getcomposer.org/doc/00-intro.md
