### ISSUE TITLE
Exception throwing failed to open stream: Too many open files

### ISSUE THREAD

**Issue by haydenyoung** [php-mime-mail-parser/php-mime-mail-parser#267]
For some reason, getAttachmentStream hits an error. I have narrowed the problem down to https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/master/src/Parser.php#L607 but I cannot work out why tmpfile() works fine then suddenly returns false.

The Exception is what is causing PHP Mail Parser to exit unexpectedly, https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/master/src/Parser.php#L626. Changing Exception to \Exception solves the problem.

Ideally, I would like to work out why tmpfile() suddenly starts to return false after successfully creating a number of tmp file pointers. I'm guessing the "Too many open files..." is the clue but does this mean that file pointers are not being closed by PHP Mail Parser?

```
PHP Warning:  include(/opt/importer/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Exception.php): failed to open stream: Too many open files in /opt/importer/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(): Failed opening '/opt/importer/vendor/composer/../php-mime-mail-parser/php-mime-mail-parser/src/Exception.php' for inclusion (include_path='.:/usr/share/php') in /opt/importer/vendor/composer/ClassLoader.php on line 444
PHP Fatal error:  Uncaught Error: Class 'PhpMimeMailParser\Exception' not found in /opt/importer/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php:626
Stack trace:
#0 /opt/importer/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php(547): PhpMimeMailParser\Parser->getAttachmentStream(Array)
#1 /opt/importer/index_mail.php(227): PhpMimeMailParser\Parser->getAttachments(false)
#2 /opt/importer/index_mail.php(97): getMailBox('macanh.huy@vnc....')
#3 {main}
  thrown in /opt/importer/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php on line 626
```

**Comment by lucasvdh** [comment]
It's not up to the package to close the streams which point to the temporary files. AFAIK tmpfiles are closed/removed when you unset the reference to that file or close them with `fclose($handle)`. Apparently your implementation still references the attachments somewhere in memory otherwise they'd be closed.

A simple fix would be to [increase your `ulimit`](https://easyengine.io/tutorials/linux/increase-open-files-limit/). You can check the current configured limit by running:
```shell script
ulimit -n
```

If you don't have control over your environment I'd suggest unsetting all references to the message object once you're done with it or if that doesn't work, manually closing all the attachment streams.

**Comment by haydenyoung** [comment]
Thanks for the suggestions.

So firstly, the Exception issue; https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/master/src/Parser.php#L626 is expecting PhpMimeMailParser\Exception rather than Exception. Does this need to be updated to be \Exception? E.g.

```
        } else {
            throw new \Exception(
                'Could not create temporary files for attachments. Your tmp directory may be unwritable by PHP.'
            );
        }
```

**Comment by eXorus** [comment]
Not necessary, as you can see in the test
https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/master/tests/ExceptionTest.php

We expect PhpMimeMailParser\Exception
that are defined and extend \Exception
https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/master/src/Exception.php

**Comment by lucasvdh** [comment]
Something is probably wrong with your autoload because the Exception can be found in the correct location and namespace.

**Comment by sanmai** [comment]
To throw an exception you need to load its class from a file, but if you're out of file handles, you can't open that file. Hence you have this bogus class not found error. I don't see how authors of this library can help in this case.

As a workaround, try preloading the exception before you load emails:
```php
class_exists(\PhpMimeMailParser\Exception::class);
```
You won't get rid of these errors, but at least you'll be getting a correct exception.
