### ISSUE TITLE
Class 'PhpMimeMailParser\Parser' not found

### ISSUE THREAD

**Issue by pericodes** [php-mime-mail-parser/php-mime-mail-parser#268]
Hi,

I've installed mailparse on Ubuntu 18.04 with this command: 
 `sudo apt-get install -y php-mailparse`

but when I try to create a new parser PHP give me the next error: 

`PHP Fatal error:  Uncaught Error: Class 'PhpMimeMailParser\Parser' not found in...`

In the begining I've tryed to create the parser on this way: 
`$parser = new PhpMimeMailParser\Parser();`

But as I saw [here](https://github.com/php-mime-mail-parser/php-mime-mail-parser/issues/244), I've tryed on this way: 
`$parser = $parser = new PhpMimeMailParser\Parser();`

Php -v guive me the next information: 

> php -v
PHP 7.2.24-0ubuntu0.18.04.1 (cli) (built: Oct 28 2019 12:07:07) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies`

However It still fails.

Thanks you to help.

**Comment by eXorus** [comment]
Hello,

php-mime-mail-parser has to be installed with a 
`composer require php-mime-mail-parser/php-mime-mail-parser`
Did you do that?

**Comment by pericodes** [comment]
Hello, 
Thanks for your fast reponse. 

I'm sorry, i didn't know that php-mime-mail-parser has to be installed with composer, so I didn't do it. You are right, when you install it with composer it works. 

But, what does this command do? 
`sudo apt install php-cli php-mailparse`

Because when I install it some functions worked. 

I don't know if I should close the issue, so If I should, tell me or maybe you can also to close it.

Thanks again :)
