### ISSUE TITLE
More sutable filename for EML-attachment

### ISSUE THREAD

**Issue by pyatnitsev** [php-mime-mail-parser/php-mime-mail-parser#269]
Hello!

I see, you try to get actual filename of attachment, or named it as noname{n}
I think, that in case of message imap_rfc822_parse_headers($attachment->getMimePartStr()) can be used, and after it - just decode to utf8 and save actual name of eml-attachment.

What do you think?

**Comment by eXorus** [comment]
Hello,

I don't understand, do you have an example?

With `imap_rfc822_parse_headers` you will have an array of headers that's all. So at the end you will have to take one header: disposition-filename, content-name, ...
and it's already what we did, except if we are not able to find a filename.

**Comment by pyatnitsev** [comment]
I mean thomething like this:

`
if (mb_strpos($attachment->getContentType(), 'message/') !== false) {
                if ($header = imap_rfc822_parse_headers($attachment->getMimePartStr())) {
                    $fileName = imap_utf8($header->subject) . '.eml';
                }
            }
`

**Comment by eXorus** [comment]
Ok I understand now.

You can submit a PR with a test for that.

**Comment by eXorus** [comment]
Issues fixed in the next version.

Thanks.

**Comment by pyatnitsev** [comment]
Sorry, I forget about PR for this.

Thanks to do it for me

**Comment by eXorus** [comment]
Don't use the master version right now.
I'm working on a big version with a lot of improvements and breaking changes.

**Comment by pyatnitsev** [comment]
I implemented this feature on client side (post-processing of attachments and so on) and actually use latest stable version for now. 

I looking forward next major version. Thanks again.
