### ISSUE TITLE
Extracting inline attachments

### ISSUE THREAD

**Issue by iamoskvin** [php-mime-mail-parser/php-mime-mail-parser#295]
We have html email with inline attachments. I want to save html body to database but before that to replace all inline attachments to some custom ids and save inline attachments separately from the body.   I can easy retrieve inline attachments like this https://github.com/php-mime-mail-parser/php-mime-mail-parser/issues/43
But how can I efficiently replace inline attachment from the body (getMessageBody('htmlEmbedded')).   Do I need just string replacement method or maybe there is more clear way?

**Comment by eXorus** [comment]
You should replicate the same code than my function:
https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/8da1d62f35782f156e66e2c3c06546bb0fddaab2/src/Parser.php#L395-L406
