### ISSUE TITLE
not parsing letter attachments

### ISSUE THREAD

**Issue by geo903** [php-mime-mail-parser/php-mime-mail-parser#296]
I received letters from the crm mail system, an attachment together with the text of the letter gives out functions getMessageBody(), function getAttachments() an empty array.

```
----022d081010a041b4b81b27e3fab3bf1c
Content-Type: text/plain; charset=windows-1251
Content-Transfer-Encoding: base64

zvLi5fIg7eAgwuD45SDu4fDg+eXt6OUguTA1LzAxwyDu8iAwOS4wMS4yMDIwDQoNCi0tIA0K0SDz
4uDm5e3o5ewsDQrK7vHy8Oj26uD/IM4uwi4=

----022d081010a041b4b81b27e3fab3bf1c
Content-Type: application/octet-stream; name="=?windows-1251?b?xO7q8+zl7fIucGRm?="
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="=?windows-1251?b?xO7q8+zl7fIucGRm?="

JVBERi0xLjQKJeLjz9MKNiAwIG9iago8PC9GaWx0ZXIvRmxhdGVEZWNvZGUvTGVuZ3RoIDcwPj5z
dHJlYW0KeJzTd8tMLy1KVbCx0fd19nRRMLCzU3ByceYq5DK1NFUwAEILEwM9C0sgw1DP0FAhOZdL
3zPXUMElnyuQy9XXmQsAAT4OpgplbmRzdHJlYW0KZW5kb2JqCjUgMCBvYmoKPDwvQ29udGVudHMg
NiAwIFIvTWVkaWFCb3hbMCAwIDU5NSA4NDJdL1BhcmVudCAyIDAgUi9SZXNvdXJjZXM8PC9YT2Jq
```

**Comment by eXorus** [comment]
Do you have the full email not only the 2 text part to investigate?

**Comment by geo903** [comment]
Yes, I have accumulated about 30 such letters from different recipients but using a single mail sending system. here I attach a few letters. http://cloud.xfrm.org.ru/s/bFTKKR7Wq86DNGz

**Comment by eXorus** [comment]
Hello,

It was difficult but I found the issue.

The header seems wrong:
`MIME-Version: 1.0;`
The correct version should be (without semicolon):
`MIME-Version: 1.0`

I'm not sure if it's correct or not
https://bugs.php.net/bug.php?id=73110

**Comment by geo903** [comment]
Thanks for the great work! Error was confirmed. Will you make changes?

**Comment by sanmai** [comment]
How about:
```php
$message str_replace('MIME-Version: 1.0;', 'MIME-Version: 1.0', $message);
```

I don't think this library should be doing anything like this, tbh.

**Comment by eXorus** [comment]
The fix is easy but I agree it's not the job of this wrapper to do that.

Or we should find somewhere in the MIME specifications: is it the correct way to declare the version?

If Yes I may include the fix in the wrapper or in mailparse extension (more difficult).
