### ISSUE TITLE
How to extract reply text only instead whole body text?

### ISSUE THREAD

**Issue by thasneem077** [php-mime-mail-parser/php-mime-mail-parser#297]
How to extract reply text only instead whole body text?

![image](https://user-images.githubusercontent.com/12522874/75116073-841a1980-568a-11ea-9bf8-a4721062639c.png)

**Comment by eXorus** [comment]
This is not the purpose of my library.

It's very difficult to detect reply in an email so you have to build it.

**Comment by sanmai** [comment]
You can try this: https://github.com/willdurand/EmailReplyParser

**Comment by thasneem077** [comment]
> This is not the purpose of my library.
> 
> It's very difficult to detect reply in an email so you have to build it.

Ah! thank @eXorus. anyway its very useful for me.
Cheers!

**Comment by thasneem077** [comment]
> You can try this: https://github.com/willdurand/EmailReplyParser

Thanks @sanmai. I'll check that.

**Comment by thasneem077** [comment]
> You can try this: https://github.com/willdurand/EmailReplyParser

@sanmai . Thank you very much for the link. it works well. Bravo....
