### ISSUE TITLE
Yandex mail body text empty

### ISSUE THREAD

**Issue by thasneem077** [php-mime-mail-parser/php-mime-mail-parser#298]
Yandex mail body text empty.
But html is visible.
Any solutions for this?

Thanks!

**Comment by eXorus** [comment]
Could you provide the raw email to investigate?

**Comment by thasneem077** [comment]
`Received: from mxback27o.mail.yandex.net (localhost [127.0.0.1])
	by mxback27o.mail.yandex.net with LMTP id jTUmWl7D42-Y7aH9cou
	for <thasneem@yandex.com>; Mon, 24 Feb 2020 20:36:30 +0300
Received: from mxback27o.mail.yandex.net (localhost [127.0.0.1])
	by mxback27o.mail.yandex.net (Yandex) with ESMTP id A00753259F6
	for <thasneem@yandex.com>; Mon, 24 Feb 2020 20:36:30 +0300 (MSK)
X-Yandex-Internal: 1
Received: from localhost (localhost [::1])
	by mxback27o.mail.yandex.net (mxback/Yandex) with ESMTP id NJ5BVg9ZXJ-aUjmi20A;
	Mon, 24 Feb 2020 20:36:30 +0300
X-Yandex-Front: mxback27o.mail.yandex.net
X-Yandex-TimeMark: 1582565790.316
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=yandex.com; s=mail; t=1582565790;
	bh=TZ1OXQrBQ2PsXMKe57GDxwJbAwD0oBZrdT2tdSA024k=;
	h=Message-Id:Date:Subject:To:From;
	b=bzB6u/DVXIAfjePWY2hwGEIaRfYkB1NtPtVQFdeTBPciWYUsCAZ1WsS7OfNzi/BEf
	 3RgaU2L1tDapr7NSxnFGT0Io8Rxn5jfYHYgfWRDba4cFus9RXkKNV/glHTRDMHpntq
	 UgdP5HwjsqfBGIhsHUekOHwGejEgcMgZU/lxdaoA=
Authentication-Results: mxback27o.mail.yandex.net; dkim=pass header.i=@yandex.com
X-Yandex-MXCode: GRE
X-Yandex-Suid-Status: 1 0,1 0
X-Yandex-Spam: 1
X-Yandex-Envelope: aGVsbz1teGJhY2syN28ubWFpbC55YW5kZXgubmV0Cm1haWxfZnJvbT10aGFzbmVlbUB5YW5kZXguY29tCnJjcHRfdG89dGVzdEBzdG9yeS5ibGlucXNvZnR3YXJlLmNvbQpyZW1vdGVfaG9zdD1sb2NhbGhvc3QKcmVtb3RlX2lwPTo6MQo=
X-Yandex-Sender-Uid: 790999334
Received: by sas1-17582c8cbad7.qloud-c.yandex.net with HTTP;
	Mon, 24 Feb 2020 20:36:30 +0300
From: Thasneem Mohamed <thasneem@yandex.com>
To: "test@story.xxxxxxxx.com" <test@story.xxxxxxxx.com>
Subject: from yandex
MIME-Version: 1.0
X-Mailer: Yamail [ http://yandex.ru ] 5.0
Date: Mon, 24 Feb 2020 23:06:30 +0530
Message-Id: <8373271582565790@sas1-17582c8cbad7.qloud-c.yandex.net>
Content-Transfer-Encoding: 7bit
Content-Type: text/html
Return-Path: thasneem@yandex.com

<div>test from yandex</div>`

**Comment by eXorus** [comment]
It's normal to have only HTML here, because there is no TXT version.

**Comment by thasneem077** [comment]
Thank you for your response 👍
