### ISSUE TITLE
segmentation fault at 2nd mail when parsing multiple emails

### ISSUE THREAD

**Issue by lostence** [php-mime-mail-parser/php-mime-mail-parser#299]
I'm having a problem parsing multiple emails, PHP crashes with a segmentation fault when parsing the 2nd one.

It makes me think of Issue 84, but this has apparently been fixed in mailparse 3.0.1 so i'm not sure why i have this problem.. i feel it could be my fault.

mailparse 3.0.3-dev
php 7.3.14-1~deb10u1

Failing simplified code :

```
function testparse($file) {
	require_once __DIR__.'/vendor/autoload.php';
	$parser = new PhpMimeMailParser\Parser();
	$parser->setPath($file); 
}

testparse('/path/to/file1.eml');
testparse('/path/to/file2.eml');
```
Any idea what i do wrong or what i could do to workaround the problem?
Thank you

**Comment by sanmai** [comment]
mailparse 3.0.3 is not compatible with PHP 7.3. You have to upgrade to 3.0.4.

**Comment by lostence** [comment]
Oh..
I'm running debian stable, and that's what gets installed by apt-get.. hm.
Guess i'm going to have to wait till 3.0.4 makes it out of testing, or find a way to install mailparse manually.

**Comment by lostence** [comment]
> mailparse 3.0.3 is not compatible with PHP 7.3. You have to upgrade to 3.0.4.

Manually installed mailparse 3.0.4 using pecl, works fine.
Thank you, issue resolved
