### ISSUE TITLE
Wrong parsing of attachment's filename

### ISSUE THREAD

**Issue by pyatnitsev** [php-mime-mail-parser/php-mime-mail-parser#300]
Hi!

I found a bug with parsing attacment header.
I have eml with "Aug 26 2019 9_16 PM - копия.csv" but parser represents it as Aug 26 2019 9 16 PM - копия.csv
it's going on becouse in the decodeSingleHeader() method on case q it replaces with space, but it's not needed in this case.

I can create a reproducer if you need it. 

wrong-parsed eml attached:

[eml.zip](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/4415213/eml.zip)

**Comment by eXorus** [comment]
Hello,

Thanks for your nice bug report.

Yes please create a PR.

**Comment by pyatnitsev** [comment]
So, I don't create PR, becouse I think, that code in the lib is need in some cases. 
WDYT?

**Comment by eXorus** [comment]
We should create a PR with your eml and try to fix it without breaking the others tests (except if there are wrong tests in my repository).

**Comment by pyatnitsev** [comment]
Ok, I will do PR ASAP.

Thanks!

**Comment by pyatnitsev** [comment]
I find out strange thing. 
On header decode all right. 
For my example 
disposition-filename returns as =?utf-8?Q?Aug=2026=202019=209_16=20PM=20-=20=D0=BA=D0=BE=D0=BF=D0=B8=D1=8F.csv?= by mailparse_msg_get_part_data() php function. 

I'm trying to decode it using [online tool](https://dogmamix.com/MimeHeadersDecoder/) and got this: **Aug 26 2019 9 16 PM - копия.csv** - wrong filename (without underscore)

**Comment by pyatnitsev** [comment]
#301 PR

**Comment by eXorus** [comment]
@pyatnitsev 
So are you sure it's still a bug if my lib and the online tool also decode the header the same?

Actual result is (my lib and online tool):
`Aug 26 2019 9_16 PM - копия.csv`

Expected result:
`Aug 26 2019 9 16 PM - копия.csv`

Why did you close your PR?

**Comment by pyatnitsev** [comment]
I closed PR, couse one of existed tests has been failed with this PR. 
if my example works well (decode content-name first), but testIlligalAttachmentFilenameForDispositionFilename will fail on my PR.

I wrote test for decodeHeader function and it's work well. 

So. Can you try to open my eml file and from test - issue133? You will see correct file names in both cases. If we try to get attachment's filename in issue133 it wii be ok, but not in my case :(

For now, I haven't any idea how to fix this issue.
