### ISSUE TITLE
Mail Parsing Incorrectly

### ISSUE THREAD

**Issue by swartjie** [php-mime-mail-parser/php-mime-mail-parser#316]
Hey Guys,

I first off want to say great job on the class thus far. Quite easy to work with...
I do have 1 issue which is a bit of a major issue for me...

So my Outlook 2019 is set to use HTML formatted emails.
But when I get the message body, I have to get the text format, the html does not give me any content, just returns blank.
That then means when I work with the email and save it, I lose everything from bold text, to UL's or OL's

What might cause this?
Do I need to change something on my side to have the email parsed correctly?

Code Snippet:
```
$parser->setStream(fopen("php://stdin", "r"));

$arrayHeaderTo = $parser->getAddresses('to');

$rawHeaderFrom = $parser->getHeader('from');
$arrayHeaderFrom = $parser->getAddresses('from');

$subject = $parser->getHeader('subject');

$text = $parser->getMessageBody('text');
$html = $parser->getMessageBody('html');
```

In the aboe example $html is empty and $text has the email's body, but unformatted.

Kind Regards

**Comment by eXorus** [comment]
Hello ,

Nothing might cause this.

Could you provide the raw email to check?

Thanks

**Comment by swartjie** [comment]
How can I provide the raw email? The email's being imported with $parser->setStream(fopen("php://stdin", "r")); so I am not sure how to provide you with the raw eml for it?

Or do you mean that you want the raw email being sent (before hitting postfix and then the script, i.e. from my outlook?)

**Comment by sanmai** [comment]
[As per manual](https://www.php.net/manual/en/function.fread.php):
```php
$handle = fopen("php://stdin", "r");
$contents = fread($handle, filesize($filename));
fclose($handle);
```

**Comment by eXorus** [comment]
You should be able to fopen the stream, loop on it, and save it in a new
file.

**Comment by swartjie** [comment]
Hey bud,

Ok so I have saved the contents in an eml file, When opened it fully shows the formatted content with attachments. But if I try and strip out the content and resend it, I'm getting an unformatted mail. no HTML... So somewhere the formatting is lost when using the mime mail parser class? Or I am maybe doing something wrong?

[savedmail.zip](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/4776550/savedmail.zip)


The code I am using is as follows:
```
$parser = new PhpMimeMailParser\Parser();

$parser->setStream(fopen("php://stdin", "r"));

//      Get Details From Mail Sent
$arrayHeaderTo = $parser->getAddresses('to');
$arrayHeaderCC = $parser->getAddresses('cc');

$rawHeaderFrom = $parser->getHeader('from');
$arrayHeaderFrom = $parser->getAddresses('from');

$subject = $parser->getHeader('subject');

$text = $parser->getMessageBody('text');
$html = $parser->getMessageBody('html');
```
and if I dump both the text and html variables, Only the text version has content, The HTML is NULL?

**Comment by eXorus** [comment]
I did a test and no issue on my side:

```php

    public function testRecursiveMessageThatReturnContentTypeError()
    {
        $Parser = new Parser();
        $Parser->setPath(__DIR__.'/mails/savedmail.eml');

        $this->assertEquals([[
            'display' => 'Marcel Swart',
            'address' => 'mpswart@infinitycds.co.za',
            'is_group' => false
        ]], $Parser->getAddresses('to'));
        $this->assertEquals([], $Parser->getAddresses('cc'));

        $this->assertEquals('"Wild Olive" <mpswart@infinitycds.co.za>', $Parser->getHeader('from'));
        $this->assertEquals([[
            'display' => 'Wild Olive',
            'address' => 'mpswart@infinitycds.co.za',
            'is_group' => false
        ]], $Parser->getAddresses('from'));

        $this->assertEquals('Test HTML Mail With Attachments', $Parser->getHeader('subject'));
        $this->assertStringContainsString('Second line, but bold', $Parser->getMessageBody('text'));
        $this->assertEquals('', $Parser->getMessageBody('html'));
    }

```

The test is OK.
Your email attached, is only:
- one part text/plain
- one attachment winmail.dat

There is no HTML, open the savedmail.eml in a text editor and search for "Second line, but bold" you will find only one reference.

**Comment by swartjie** [comment]
Bud, If I view the email's source, I am seeing the below code which shows it as being HTML?

`</head><body lang=EN-ZA link="#0563C1" vlink="#954F72"><div class=WordSection1><p class=MsoNormal>This is the first line<o:p></o:p></p><p class=MsoNormal><b>Second line, but bold<o:p></o:p></b></p><p class=MsoNormal><i>Third line, Only italic<o:p></o:p></i></p><p class=MsoNormal><b><o:p>&nbsp;</o:p></b></p><ul style='margin-top:0cm' type=disc><li class=MsoListParagraph style='margin-left:0cm;mso-list:l0 level1 lfo1'>UL item 1<b><o:p></o:p></b></li><li class=MsoListParagraph style='margin-left:0cm;mso-list:l0 level1 lfo1'>UL item 2<b><o:p></o:p></b></li><li class=MsoListParagraph style='margin-left:0cm;mso-list:l0 level1 lfo1'>UL item 3<b><o:p></o:p></b></li></ul><p class=MsoNormal><o:p>&nbsp;</o:p></p></div></body></html>`

**Comment by eXorus** [comment]
Where do you see that? in a Microsoft Tool?

**Comment by swartjie** [comment]
That's in outlook. In outlook you can view the source of the email which then shows the css and that html?

**Comment by eXorus** [comment]
Ok so normal, only Microsoft can decode your email.
Even the new "Courrier" app in Windows 10 are not able to show this type of email.

**Comment by swartjie** [comment]
Hey eXorus,

Ok... So what's a possible work-around?
There has to be some way to parse the outlook mailed emails with formatting?

**Comment by eXorus** [comment]
The email specifications are very flexible, you can send:
- text/plain : basic without formatting
- text/html : html version

This 2 types are the commonly used by everyone in the world. But in the email specifications you could create another format:
- text/my-custom-format-in-mardown

It's totally up to you, but you can't do it in my lib.
You have to parse the first time the email, detect the new format because:
- there is a text/my-custom-format-in-mardown
- there is a winmail.dat attachment

and use another lib to parse this specifique type.

**Comment by swartjie** [comment]
I'm not sure what you're suggesting for how to parse the emails?
b.t.w, Is there a way to get the email content as is? Even if it's not in a workable format for the class, since I only need to add to it, I don't need to change anything really

**Comment by eXorus** [comment]
It should be something like that.
You have to found the correct parser for your microsoft stuff.
I can't help you more it's not part of my lib.

```php
$Parser = new Parser();
$Parser->setPath(__DIR__.'/mails/savedmail.eml');
$attachments = $Parser->getAttachments();
foreach ($attachments as $attachment)
{
    if ($attachment->getFilename() == 'winmail.dat')
    {
        $Parser->save('./attachments/');
        $microsoftParser = new MicrosoftParser('./attachments/winmail.dat');
        // do what you want here
    }
}


```

**Comment by swartjie** [comment]
I think you're conflaiting the 2 open issues I had.

the other one was about the winmail.dat file.

This one is about the HTML not rendering properly?
When calling the getHTML function, I am receiving nothing, even though the email is HTML in outlook as quoted above :)

**Comment by eXorus** [comment]
No I don't, it's the same email there is no HTML on it.

Or send back the raw email but the last one was still without html.

**Comment by swartjie** [comment]
I don't understand how there's no HTML when this is in the mail?
https://github.com/php-mime-mail-parser/php-mime-mail-parser/issues/316#issuecomment-644049514

**Comment by eXorus** [comment]
The HTML in your comment is not in the email.
It's an HTML that Outlook is able to produce by parsing the winmail.dat that is a file that only Microsoft can understand.

**Comment by eXorus** [comment]
> The HTML in your comment is not in the email.
is in the email but inside the winmail.dat that are a binary file not parsable.

**Comment by swartjie** [comment]
> > The HTML in your comment is not in the email.
> > is in the email but inside the winmail.dat that are a binary file not parsable.

Is there a parsing tool that can actualy parse this then? I'm having trouble finding one...

**Comment by sanmai** [comment]
[There are several.](https://github.com/php-mime-mail-parser/php-mime-mail-parser/issues/317#issuecomment-644511127)

**Comment by swartjie** [comment]
Hey Sanmai,

Correct me if I am wrong, but that link references the winmail.dat file, not the actual outlook html parsing?

The attachment part of it I get, I need a way to properly parse the html from outlook sent mail?
