### ISSUE TITLE
Loading Attachments Not Working

### ISSUE THREAD

**Issue by swartjie** [php-mime-mail-parser/php-mime-mail-parser#317]
Hey Guys,

I am having trouble loading attachments.
Mail's are being piped to the php file from postfix, so we're using $parser->setStream(fopen("php://stdin", "r")); to read the email.

Only issue is, if I run $parser->saveAttachments(__DIR.'/tmp/'); on that email, it only saves a winmail.dat file.

Why is it not saving the actual data? And what should I do to correct?

**Comment by sanmai** [comment]
Would you care to provide an example for us to have a look?

**Comment by swartjie** [comment]
> Would you care to provide an example for us to have a look?

What example? Example of the winmail.dat or what can I provide to assist?

**Comment by sanmai** [comment]
Example of an email where you see a problem with attachments.

**Comment by swartjie** [comment]
How can I provide that?
Sorry I am unsure what would assist best?

Basically what I am doing, is I am sending an email through a postfix smtp server, That email I am sending has an attachment (photo, pdf of word, does not matter what it is, or how many there are).

That email is then piped to a php script which reads the mail's contents to prepare it, and then sends it out.

But when I try to save attachments, It's giving me nothing... Just the winmail.dat file being saved.
Not sure if I need to change the postfix pipe or what may be the problem in getting the attachments

```
mailhandler   unix  -       n       n       -       -       pipe
  flags=FR user=mailhandler argv=/home/mailhandler/postfix.php ${sender} ${size} ${recipient}
  ${nexthop} ${user}
```

**Comment by eXorus** [comment]
It should work, if the only attachment saved is winmail.dat  it means there
is no attachments.
We need the raw email to investigate.

**Comment by swartjie** [comment]
The raw email that is sent from my outlook? Or when it hits postfix?

**Comment by eXorus** [comment]
Should be the same, but maybe I prefer the one you received in posfix.

**Comment by swartjie** [comment]
Hey eXorus,

Ok so I have saved the contents in an eml file, When opened it fully shows the formatted content with attachments. But I can't save the attachments using the code below?
It's only saving the winmail.dat file? Not the attachments I actually attached.

[savedmail.zip](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/4776562/savedmail.zip)

The code I am using is as follows:
```
$parser = new PhpMimeMailParser\Parser();

$parser->setStream(fopen("php://stdin", "r"));

//      Get Details From Mail Sent
$arrayHeaderTo = $parser->getAddresses('to');
$arrayHeaderCC = $parser->getAddresses('cc');

$rawHeaderFrom = $parser->getHeader('from');
$arrayHeaderFrom = $parser->getAddresses('from');

$subject = $parser->getHeader('subject');

$text = $parser->getMessageBody('text');
$html = $parser->getMessageBody('html');

$FileArray = $parser->saveAttachments(__DIR__.'/tmp/');
```
The only item in the $FileArray though is the winmail.dat file. The other files aren't included in the returned list?

**Comment by sanmai** [comment]
My email client tells me there's indeed only one attachment.

**Comment by swartjie** [comment]
Hey bud,

The email has 2 attachments. Please see the image below. I opened the zip file and took a screenshot
![Untitled](https://user-images.githubusercontent.com/25154330/84625505-afe43800-aee3-11ea-8dfd-3f05410be27a.png)

**Comment by sanmai** [comment]
In the email you have attached above there only one attachment. You can verify this fact like so:
```
grep -A5 NextPart_ savedmail.eml
```

**Comment by swartjie** [comment]
Hey Sanmai,

I get what you're saying, but the photo above is that exact email opened in outlook, showing 2 attachments?
It's not the email in my sent box, it's the one saved on the postfix server just before handing it over to the mail parser?

I will say this, it was dragged into outlook, so most likely attached in line, since if you look at the body it's quite a large body for the email content size?

**Comment by sanmai** [comment]
If the email was modified before it was passed Postfix, then there's nothing we can do. It is your job to make sure Postfix receives a complete non-modified email.

**Comment by swartjie** [comment]
no that's the point. The screenshot above showing the 2 attachment, is the email that is received and I am trying to process... That's the email postfix received and saved to a file for me so I can give it to you...

If you open that file in Outook, it shows 2 attachments as per the screenshot of that file.
But if I read it with the mail parser, it's only showing me the winmail.dat file?
So it's not parsing it correctly?

**Comment by sanmai** [comment]
In the file you've [attached to the message above](https://github.com/php-mime-mail-parser/php-mime-mail-parser/issues/317#issuecomment-643773197) there's only one attachment. Are you sure you're opening the very file on Outlook, not some other message?

**Comment by swartjie** [comment]
Yes, I can take a video for you if need be. I am downloading that file linked above. Unzipping it, And double clicking on the savedmail.eml which then opens it in outlook, where I then see the formatted email, with the 2 attachments, a blank docx file and a image file...

**Comment by eXorus** [comment]
Yes do it because same for me only one attachment.
<img width="1391" alt="Capture d’écran 2020-06-15 à 12 13 15" src="https://user-images.githubusercontent.com/1255561/84645936-a7025f00-af01-11ea-84c7-04f46356dca7.png">

**Comment by swartjie** [comment]
I have done so for you... Makes no sense to me D:
[video.zip](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/4779609/video.zip)

**Comment by eXorus** [comment]
I don't understand, it doesn't make sense to me also.

I think your mail editor is smart enough to understand the winmail.dat.

But from an email parser point of view it doesn't mean anything. winmail.dat is only an attachment. It can't be parsed as 2 others attachments and one html version.

...

Ok so after some investigation I found the issue. If you look at winmail.dat is Microsoft's proprietary file. So only Microsoft tool can decode it. So you should never send an email with this type.
https://support.mozilla.org/en-US/kb/what-winmaildat-attachment

**Comment by swartjie** [comment]
Hey eXorus,

Ok so first off thanks for that, Was quite interesting to read through.
But I don't think that's the issue... I'll explain why...

If I check in outlook it is an HTML email (not RTF), and even if I format the email as plain text, The winmail.dat file is still there and the attachments aren't?

**Comment by swartjie** [comment]
Hey eXorus,

Ok so I want to help bring some closure to this issue...
I had a look and found a link https://blog.gimm.io/how-to-fix-winmail-dat-attachments-in-outlook/

The bottom part of the page explains how to turn off tnef in the registry. When doing that, It immediately resolved my issue.

My only issue though, Is outlook was set to use both html and txt and both did not work for disabling it. So not sure if it's my PC, outlook or where the issue was...

But thank you guys a lot :)!

**Comment by eXorus** [comment]
Great article, thanks for your comment.

Email is always surprising, even after 10 years in this domain. ;)

**Comment by sanmai** [comment]
Thanks for the video. Here's what I found:
- Outlook may have attached files embedded in a `winmail.dat`, which is a TNEF file.
- These files require their own parser, and there are several. For example, we have [a dedicated package](https://packages.debian.org/search?keywords=tnef), aptly named too, and there's [this library](https://github.com/QualityUnit/TNEFDecoder).

Otherwise put, there's no problem in the library. MIME package really does contain only one attachment, and that is winmail.dat. To move forward with this problem you have to use a different dedicated tool or a package.
