### ISSUE TITLE
Parse error: syntax error, unexpected '?' in /volume1/web/test/mail/src/Parser.php on line 329

### ISSUE THREAD

**Issue by mosea3** [php-mime-mail-parser/php-mime-mail-parser#322]
Hi guys
I get this syntax error cloning from current version.
`Parse error: syntax error, unexpected '?' in /volume1/web/test/mail/src/Parser.php on line 329`
However, (correct me if wrong), current native PHP version does not support ternary operators directly in method declaration like seen here:

https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/9e5f777bfaffb4504e10f377b39afd0fb4738814/src/Parser.php#L329

https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/9e5f777bfaffb4504e10f377b39afd0fb4738814/src/Parser.php#L342

https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/9e5f777bfaffb4504e10f377b39afd0fb4738814/src/Parser.php#L592

Maybe add Rector to dependencies?

**Comment by eXorus** [comment]
Hello,

Thanks I used Rector manually a few days ago but good idea to add the dependencies.

You should not use the master version, it is dev in progress for the next big version, and a lot of BC is coming.

**Comment by sanmai** [comment]
Rector is not at fault here. Master branch requires PHP 7.2, and that's the bottom of it.

**Comment by eXorus** [comment]
@mosea3 What is your PHP version?
with PHP 7.2, you should not have any issues.

https://www.php.net/manual/en/functions.returning-values.php
Example #7 Nullable return type declaration (as of PHP 7.1.0)
```php
<?php
function get_item(): ?string {
    if (isset($_GET['item'])) {
        return $_GET['item'];
    } else {
        return null;
    }
}
?>

```
