### ISSUE TITLE
Trim trailing "\n" from message body

### ISSUE THREAD

**Issue by ThomasLandauer** [php-mime-mail-parser/php-mime-mail-parser#332]
With this
```php
$raw = <<<EOD
Date: Sat, 8 Aug 2020 18:36:05 +0100
From: <foo@example.com>

foobar
EOD;

$parser = new \PhpMimeMailParser\Parser();
$parser->setText($raw);
var_dump($parser->getMessageBody('text'));
```
... I'm getting:
```
string(7) "foobar
"
```
zbateson/mail-mime-parser's [`$message->getTextContent()`](https://github.com/zbateson/mail-mime-parser/blob/master/src/Message.php#L234) is returning:
```
string(6) "foobar"
```
Since you cannot "terminate" an email body in the same line, there's always a line break after the last word. So I think it's correcter to remove this trailing `\n`.

If the sender did add a line break deliberately after the last line, the email would look like this:
```php
$raw = <<<EOD
Date: Sat, 8 Aug 2020 18:36:05 +0100
From: <foo@example.com>

foobar

EOD;
```

**Comment by eXorus** [comment]
You're right.
The issue was that an email without a line break after the last word was in error in mailparse;
So I always add a line break if I don't found one


```php
        if (substr($data, -1) != "\n") {
            $data .= PHP_EOL;
        }

```

**Comment by ThomasLandauer** [comment]
You're talking about this line in [`Parser::fromText()`](https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/master/src/Parser.php#L96)?

Here's the PHP bug for mailparse: https://bugs.php.net/bug.php?id=75923

Since it looks like they cannot solve this anytime soon, I see two options to fix it on your side:

1. Is it possible to pass an information from `fromText()` to `getMessageBody()`? If yes, set a flag that you did add a line break, then remove it again in `getMessageBody()`.
2. Repeat the exact same `if` in `getMessageBody()`. If the *raw* message did not have this line break, `fromText()` added one, so `getMessageBody()` needs to remove it.

**Comment by eXorus** [comment]
Yes the solution should solve the issue.
