### ISSUE TITLE
Segmentation fault when using PhpMimeMailParser in a while loop

### ISSUE THREAD

**Issue by yasirugw** [php-mime-mail-parser/php-mime-mail-parser#344]
Hi,

I'm using PhpMimeMailParser object to decode emails and I'm doing this for several emails at once using while loop.

OS: Debian GNU/Linux 10 (buster) (in AWS)
PHP: PHP 7.3.19
PhpMimeMailParser: Latest atm 6.0.0

The first email in the loop decodes perfectly but I'm getting "Segmentation fault" in 2nd loop. Mainly at below line.

`$parser = new PhpMimeMailParser\Parser();`

I do below at the end of the while loop but still experiencing the issue.

`unset($parser); `

I get below logs in syslog,
`kernel: [1749288.540129] traps: php[22325] general protection ip:55ef3c35350d sp:7fff83129948 error:0 in php7.3[55ef3c1aa000+261000]`

Any idea why this is happening. Am I missing something?

Let me know if you need more information.

**Comment by eXorus** [comment]
Hello,

Sorry I don't know how to fix your issue.

Is it always the same email that have an error?
Did you try to decode first the second email?

Could you create a PR that reproduce the error?

**Comment by yasirugw** [comment]
Hi Vincent,

Thanks for reply.

It is not the same email that failed. I have an Exim4 server that insert the emails in to a database. Then I have setup cronjob runs every minute and get new emails from the database and decode using PhpMimeMailParser in a loop. 

The cronjob always fails at second email. 

For example lets say I have emails called A,B and C.

In first minute the script decode A successful and then failed at email B. But in the next run the failed email B get decode, and then again failed to decode email C. Then email C get decode in next run.

I tried this with 2 sample .eml files and it decodes the emails in a loop without any issue. 

so I wonder whether there is a issue in our emails, but also confuse why it decodes if it is the first object.

I'm still digging...

**Comment by eXorus** [comment]
It's very weird.

In my project the process is different, the mail server send the data directly to php-mime-mail-parser to be parsed. I don't need to insert them in the database and after a cron to loop over the emails inserted.

https://github.com/mailcare/mailcare/blob/master/app/Console/Commands/ReceiveEmail.php
This is the command that receive the emails from the mail server.

Maybe you could change the way your system works.

**Comment by yasirugw** [comment]
Sure, I'll try that. I have created PR Create issue-344.eml #346 and added .eml file which can reproduce the issue.
May be I need to fix something in this emails before "setText".

**Comment by zsogolow** [comment]
I am experiencing a similar issue. There appears to be a memory leak when using setText().

I am using the parser in a loop as well, parsing many email files. The memory usage is steadily climbing after each iteration, and I have tracked it down to the call to setText. I have also tried to explicitly call unset($parser) at the end of each iteration and its having no effect. 

A simple script to reproduce the issue (replace download.eml with any .eml):
```php
$i = 0;
while ($i++ < 100000) {
    $parser = new PhpMimeMailParser\Parser();
    $parser->setText(file_get_contents("download.eml"));

    echo "Memory Consumption is ";
    echo round(memory_get_usage() / 1048576, 2) . '' . ' MB' . PHP_EOL;
    unset($parser);
}
```

**Comment by yasirugw** [comment]
I tried adding below function into `src/Parser.php` and call it like `$parser->freeResource();` at end of the loop, but still no luck. :(

```
    /**
     * Frees the MIME resource
     *
     * @return mailparse_msg_free bool
     */
    public function freeResource()
    {
        return mailparse_msg_free($this->resource);
    }
```

**Comment by zsogolow** [comment]
This might be related to the bug I found in the [mailparse pecl package](https://pecl.php.net/package/mailparse). There appears to be a memory leak where resources are not actually freed when calling `mailparse_msg_free` See https://bugs.php.net/bug.php?id=80086

**Comment by eXorus** [comment]
I don't think it's related because I can't reproduce the segmentation fault and I can reproduce the memomy leak.

**Comment by sebastianhelbig** [comment]
Same problem here. It is a bug in the mailparse extension. You need to use current version, 3.1.1, then it will work.
