### ISSUE TITLE
Can't install in Amazon Linux AMI 2018.03

### ISSUE THREAD

**Issue by faisalraihan** [php-mime-mail-parser/php-mime-mail-parser#350]
can't install it with yum command... also i tried yum update & yum search ... "php-mailparse" not found...

**Comment by eXorus** [comment]
Did you find the solution? Could you provide a the error?

Did you try this https://ma.ttias.be/installing-the-pecl-pear-mailparse-module-for-php-on-centos/

**Comment by faisalraihan** [comment]
Thanks. Your solution worked perfectly. However, I had to install PEAR first but that's a different story. After installing PEAR the command "pear install pecl/mailparse" worked. Thank you very much.
