### ISSUE TITLE
Please add support for PHP 8

### ISSUE THREAD

**Issue by elijahchancey** [php-mime-mail-parser/php-mime-mail-parser#355]

**Comment by eXorus** [comment]
Already in progress here but my main concern is that master is a very big branch with a lot of refactoring and I didn't finish yet so I can't publish a new release.
https://github.com/php-mime-mail-parser/php-mime-mail-parser/pull/354

**Comment by mbretter** [comment]
Is there any update on this issue?
It is currently blocking our migration to PHP8 :(

cheers

**Comment by eXorus** [comment]
I'm really sorry, I don't have a lot of time at the moment to finish this big refacto (fulltime job and 🍼 👶 )

I'm going to adopt another strategy, I will release a new version of the last version with the support of PHP8 without my big refacto.

**Comment by eXorus** [comment]
I hope it works.

I did a new version php-mime-mail-parser 7.0 that support PHP8.

**Comment by eXorus** [comment]
You can also sponsor me if you like my work 😉

https://github.com/sponsors/eXorus
