### ISSUE TITLE
Address display name utf8 space issue

### ISSUE THREAD

**Issue by 0xb4lint** [php-mime-mail-parser/php-mime-mail-parser#357]
**Describe the bug**
If I use an address name with special characters (e.g. `Bálint`) it will be converted to an escaped version (`=?utf-8?Q?B=C3=A1lint?=`) by most email clients. If this address name also contains a space then it will be lost after calling `getAddresses()`.

**To Reproduce**
```eml
To: =?utf-8?Q?B=C3=A1lint?= Szekeres <szekeres@b4lint.hu>
```

```php
$this->assertEquals('Bálint Szekeres', $Parser->getAddressesTo()[0]['display']);
```
```diff
--- Expected
+++ Actual
@@ @@
-'Bálint Szekeres'
+'BálintSzekeres'
```

**Expected behavior**
Keep the space after decoding header.

**Version (please complete the following information):**
 - Version of mailparse: [3.1.1]
 - Version of PHP [PHP 8.0]
 - Version of php-mime-mail-parser [6.0.0]

**Additional context**
I understand the library uses `mailparse_rfc822_parse_addresses` under the hood.

And if I test with:
```php
mailparse_rfc822_parse_addresses('=?utf-8?Q?B=C3=A1lint?= Szekeres <szekeres@b4lint.hu>')
```

It gaves me (note the lost space):
```
array(1) {
  [0]=>
  array(3) {
    ["display"]=>
    string(31) "=?utf-8?Q?B=C3=A1lint?=Szekeres"
    ["address"]=>
    string(18) "szekeres@b4lint.hu"
    ["is_group"]=>
    bool(false)
  }
}
```

So I know it's a lower level issue but maybe it can be solved within the library.
What do you think?

**Comment by eXorus** [comment]
Thanks for your nice report.
I know there are a lot of issues with the function `mailparse_rfc822_parse_addresses` but I didn't found another solution for now.

See for example this long discussion
https://github.com/php-mime-mail-parser/php-mime-mail-parser/issues/176

If you know another composer package or a regex that works better than the current function I will be very happy to change the current implementation.

**Comment by 0xb4lint** [comment]
Thanks for the answer, unfortunately, I needed this feature to work reliably, so I've switched to [zbateson/mail-mime-parser](https://github.com/zbateson/mail-mime-parser).

**Comment by eXorus** [comment]
Very good choice. It's reliable and you don't need this annoying mailparse extension.
The only disadvantage is the performance.
