### ISSUE TITLE
html parser feature not working, displaying raw, bungled text

### ISSUE THREAD

**Issue by husaindevelop** [php-mime-mail-parser/php-mime-mail-parser#358]
**Describe the bug**'
Simple, parsing html body is not working. This code: $text = $parser->getMessageBody('html'); is not getting us the desired output. The whole raw mail instead of converting into html format remains as full text. 

The mail's raw contents is from a txt document through s3 bucket. The text parsing is fine, but when there is html code in the mail, using getmessagebody html does not seem to working.  It is displayed bungled up raw code content.

**To Reproduce**
Provide your php file and upload the raw email.

[93409100100000000039.txt](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/5793889/93409100100000000039.txt)

**Expected behavior**
It should display the html version of the mail instead of bungled up raw content

**Screenshots**

**Version (please complete the following information):**
 - Version of mailparse: [e.g. 3.1.1]
 - Latest one
 - Version of PHP [e.g. PHP 7.4]
 - php 7.4
 - Version of php-mime-mail-parser [e.g. 6.1]
latest one. Just pulled out lib 15 days back.
**Additional context**

Need you help in solving the problem

**Comment by eXorus** [comment]
Hello,

I don't understand your issue, I have a string with HTML:
```php
require_once __DIR__.'/vendor/autoload.php';

$parser = new PhpMimeMailParser\Parser();
$parser->setPath('93409100100000000039.txt'); 
echo $parser->getMessageBody('html');
```

And the output his something like that:
<img width="660" alt="Capture d’écran 2021-01-11 à 17 40 58" src="https://user-images.githubusercontent.com/1255561/104211364-4655e900-5434-11eb-9a2a-1fdb567ca6fa.png">

If your issue is about the embedded images, you only need to use: `$parser->getMessageBody('htmlEmbedded');`

<img width="637" alt="Capture d’écran 2021-01-11 à 17 43 20" src="https://user-images.githubusercontent.com/1255561/104211582-84530d00-5434-11eb-870a-6a121390864c.png">

**Comment by husaindevelop** [comment]
Okay, my bad. Instead of using this "$parser->setPath($path);", i used this code $parser->setText(file_get_contents($path)); to extract the content out. Now it's working fine. But i got another problem that is little off-topic, nevertheless still asking you. This same mail has inline css and it is influencing my overall page structure.  For example the company logo that i planted on this page gets two times bigger once i click this mail open. Is there any way we can suppress the mail's css styles ?

**Comment by eXorus** [comment]
The same code with setText works also perfectly fine.

```php
require_once __DIR__.'/vendor/autoload.php';

$parser = new PhpMimeMailParser\Parser();
$parser->setText(file_get_contents('93409100100000000039.txt'));
echo $parser->getMessageBody('htmlEmbedded');
```

My lib is focusing on parsing emails not parsing html. You will find other lib to parse html, but removing the CSS will not produce a good results.
The best way to show an HTML version of the email without any impact on your current HTML is to use iframe. It's the solution I use for my project mailcare:
Website: https://mailcare.io/
Example: https://mailo.xyz/emails/3baee42f-21c2-4683-be04-554be6aa836b
Repository: https://github.com/mailcare/mailcare

**Comment by husaindevelop** [comment]
Thanks eXorus. Its working even with setText now, somewhere i feel, i bungled up the code. Its okay now. Regarding using iframe to suppress the styles, is a good idea though it has been almost years since i last used iframe. Anyway thanks for the opinion and excellent lib !!!
