### ISSUE TITLE
Call to undefined function PhpMimeMailParser\mailparse_msg_create()

### ISSUE THREAD

**Issue by faisalraihan** [php-mime-mail-parser/php-mime-mail-parser#360]
I am using CakePHP 3.8
I installed everything as written in the README.md section here. 
php -m | grep mailparse returns "mailparse" in red text.
also installed this library in my cakephp project using the following command
composer require php-mime-mail-parser/php-mime-mail-parser
everything installed successfully. but i always get the following error when calling the `$parser->setStream(fopen($path, "r"));`
Error: Call to undefined function PhpMimeMailParser\mailparse_msg_create()
Error in: ROOT/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php, line 168

my code is as following >>>
```
namespace App\Controller;
use \PhpMimeMailParser\Parser;
class UsersController extends AppController {
    public function test() {
        $path = 'path/to/email.eml';  
        // used original location in the code
        $parser = new Parser;
        $parser->setStream(fopen($path, "r"));
    }
}
```

**Comment by eXorus** [comment]
Hello,

Sorry I don't know CakePHP but did you try (without \ after the use):
```
namespace App\Controller;
use PhpMimeMailParser\Parser;
class UsersController extends AppController {
    public function test() {
        $path = 'path/to/email.eml';  
        // used original location in the code
        $parser = new Parser;
        $parser->setStream(fopen($path, "r"));
    }
}
```

**Comment by faisalraihan** [comment]
yes, I've also tried without \ after the use. the error is still the same.

I've also tried RAW PHP (without any framework). it worked though. but in the framework, I think the import process is not working properly.

now that it is not working with my framework, I'm creating a raw PHP script and run it in the cron job. but my models are inside my framework so it would've been easier if I could just use it inside the framework's controller file.

**Comment by eXorus** [comment]
Maybe it's related to you php.ini.

If it works with a raw php, it means the php.ini from CLI is ok.
But if it doesn't work with the framework (through the web), it means the php.ini from web don't have mailparse activated?

**Comment by eXorus** [comment]
@faisalraihan did you find the solution?

**Comment by faisalraihan** [comment]
No, I couldn't find any solution for the framework so I decided to use the raw PHP version.
I checked inside the server, there is a "/etc/php.d/mailparse.ini" file and "extension=mailparse.so" inside it.

I could not find a different php.ini for my framework.

**Comment by eXorus** [comment]
To be sure it's not an issue on my lib could you try this:

```php
namespace App\Controller;

class UsersController extends AppController {
    public function test() {
        $path = 'path/to/email.eml';  
        mailparse_msg_parse_file($path);
    }
}
```

**Comment by faisalraihan** [comment]
sorry for the late reply. yes i've tried this. it still shows an error.
`Call to undefined function App\Controller\mailparse_msg_parse_file()`

**Comment by eXorus** [comment]
Ok so it's confirmed that the issue is not in my library.
The issue is about the php-mailparse extension and maybe how your project is configured because it's doesn't look good to check the function mailparse_msg_parse_file() in the namespace App\Controller.
