### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by Stajor** [php-mime-mail-parser/php-mime-mail-parser#363]
- Root composer.json requires php-mime-mail-parser/php-mime-mail-parser ^6.0 -> satisfiable by php-mime-mail-parser/php-mime-mail-parser[6.0.0].
    - php-mime-mail-parser/php-mime-mail-parser 6.0.0 requires php ^7.2 -> your php version (8.0.1) does not satisfy that requirement.

**Comment by eXorus** [comment]
php-mime-mail-parser/php-mime-mail-parser 6.0 doesn't support PHP8.
Please use php-mime-mail-parser/php-mime-mail-parser 7.0
