### ISSUE TITLE
Loosly coupled attachment class

### ISSUE THREAD

**Issue by thierryve** [php-mime-mail-parser/php-mime-mail-parser#37]
Hi,

I would to extend the attachment with some specific logic. The attachments are tightly coupled atm.
I would be awesome if I could extend the attachment class in some kind of way

Thanx in advance

**Comment by eXorus** [comment]
Why you can't do it ? it's


<?php
class MyAttachment extends Attachment {
...
}
?>

**Comment by thierryve** [comment]
Yeah that is possible but Attachment is directly initiated in https://github.com/eXorus/php-mime-mail-parser/blob/master/src/Parser.php#L550

**Comment by eXorus** [comment]
Ok I will do it.
Something like this ?
// Using SES Notifier
$sesNotifier = new SesNotifier(...);
$someClass = new SomeClass($sesNotifier);

// Or we can use MandrillNotifier

$mandrillNotifier = new MandrillNotifier(...);
$someClass = new SomeClass($mandrillNotifier);

// This will work no matter which implementation we use
$someClass->doStuff();

http://fideloper.com/hexagonal-architecture

**Comment by thierryve** [comment]
Great idea, I would love to see something with a Attachment Collection that is passed into the Parser. If no a default collection is used.

**Comment by fijiwebdesign** [comment]
I think all you need here is to dependency inject the Attachment class. 

In `Parser`

```
protected  $attachmentClass = 'PhpMimeMailParser\Attachment';

public function setAttachmentClass($className) {
    $this->attachmentClass = $className;
}
```

To use a different `Attachment` class

```
$Parser = new PhpMimeMailParser\Parser();
$Parser->setAttachmentClass('SomeOtherNamespace\Attachment');
```

Then to instantiate attachments

```
public function getAttachment() {
    $params = func_get_args();
    $refl = new ReflectionClass($className);
    return $refl->newInstanceArgs($params);
}

// instead of using new Attachment()
$attachment = $this->getAttachment(
                    $filename,
                    $this->getPart('content-type', $part),
                    $this->getAttachmentStream($part),
                    $disposition,
                    $contentidAttachments,
                    $headersAttachments
                );


```
