### ISSUE TITLE
can php-mime-mail-parser also send emails? it's not in the docs.. :(

### ISSUE THREAD

**Issue by nicerapp** [php-mime-mail-parser/php-mime-mail-parser#370]
**Version (please complete the following information):**
all versions : latest, downloaded today (2021-07-26)

**Additional context**
i'm just wondering if your component can send emails with the proper character encoding, and wonder if you could write some documentation for that if it already exists.

**Comment by eXorus** [comment]
No the lib is only used for parsing emails, so not receiving them or not sending them.
