### ISSUE TITLE
Does not recognize ext-mailparse

### ISSUE THREAD

**Issue by kriit24** [php-mime-mail-parser/php-mime-mail-parser#377]
Problem 1
    - Root composer.json requires php-mime-mail-parser/php-mime-mail-parser ^7.0 -> satisfiable by php-mime-mail-parser/php-mime-mail-parser[7.0.0].
    - php-mime-mail-parser/php-mime-mail-parser 7.0.0 requires ext-mailparse * -> it is missing from your system. Install or enable PHP's mailparse extension.

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/cli-php7.4/php.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

PHPINFO

mailparse
mailparse support	enabled
Extension Version	3.1.1
Directive	Local Value	Master Value
mailparse.def_charset	us-ascii	us-ascii

**Comment by eXorus** [comment]
Are you sure you don't have multiple version of PHP.
Because composer say your mailparse extension is not installed.
