### ISSUE TITLE
composer install fails

### ISSUE THREAD

**Issue by alanbqs** [php-mime-mail-parser/php-mime-mail-parser#378]
When running the composer install command on a WAMP PHP7.3 environment I get the following error message:

     >composer require php-mime-mail-parser/php-mime-mail-parser
     Using version ^7.0 for php-mime-mail-parser/php-mime-mail-parser
     ./composer.json has been updated
     Running composer update php-mime-mail-parser/php-mime-mail-parser
     Loading composer repositories with package information
     Updating dependencies
     Your requirements could not be resolved to an installable set of packages.

     Problem 1
       - Root composer.json requires php-mime-mail-parser/php-mime-mail-parser ^7.0 -> satisfiable by php-mime-mail-parser/php-mime-mail-parser[7.0.0].
      - php-mime-mail-parser/php-mime-mail-parser 7.0.0 requires ext-mailparse * -> it is missing from your system. Install or enable PHP's mailparse extension.

     To enable extensions, verify that they are enabled in your .ini files:
        - C:\wamp64\bin\php\php7.3.12\php.ini
     You can also run `php --ini` inside terminal to see which files are used by PHP in CLI 
     mode.

     Installation failed, reverting ./composer.json and ./composer.lock to their original content.`

**Comment by eXorus** [comment]
So did you check the installation of mailparse?
see the readme if you don't know how.
