### ISSUE TITLE
Segmentation faults when using embedded images and attachments

### ISSUE THREAD

**Issue by kalleswe** [php-mime-mail-parser/php-mime-mail-parser#379]
**Describe the bug**
Crashes out with segmentation fault if a mail with a small image in the body and also an image attached as a file.
Does not happen without image/attachments.

**To Reproduce**
Just use the try.php file from the git repo on Debian 11 with php 7.3 and the php-mailparse package.

**Expected behavior**
Did not expect it to segfault. Rather just display info about all the parts.

**Screenshots**
# php try.php ../mail4.txt 
PHP Notice:  Undefined offset: 2 in try.php on line 19
PHP Notice:  Undefined index: showpart in try.php on line 22
resource(5) of type (mailparse_mail_structure) refcount(2)
<table>
<tr>
PHP Notice:  Undefined variable: PHP_SELF in try.php on line 37
<td><a href="?showpart=1">1</a></td>
Array
(
    [headers] => Array
        (
            [return-path] => <REDACTED>
            [x-original-to] => REDACTED
            [delivered-to] => REDACTED
            [from] => REDACTED
            [to] => REDACTED
            [subject] => =?iso-8859-1?Q?test_=E5=E4=F6?=
            [thread-topic] => =?iso-8859-1?Q?test_=E5=E4=F6?=
            [thread-index] => Adf9YPHDtrOdqMjwQNOPjzxcdg67Iw==
            [date] => Thu, 30 Dec 2021 09:39:33 +0000
            [message-id] => REDACTED
            [accept-language] => sv-SE, en-US
            [content-language] => en-US
            [x-ms-has-attach] => yes
            [x-ms-tnef-correlator] => 
            [content-type] => multipart/mixed; boundary="REDACTED"
            [mime-version] => 1.0
        )

    [starting-pos] => 0
    [starting-pos-body] => 1604
    [ending-pos] => 24457
    [ending-pos-body] => 24457
    [line-count] => 409
    [body-line-count] => 373
    [charset] => us-ascii
    [transfer-encoding] => 8bit
    [content-boundary] => REDACTED
    [content-type] => multipart/mixed
    [content-base] => /
    [content-language] => en-US
)

<td>multipart/mixed</td>
PHP Notice:  Undefined index: content-disposition in try.php on line 45
<td></td>
PHP Notice:  Undefined index: disposition-filename in try.php on line 46
<td></td>
<td>us-ascii</td>
</tr><tr>
PHP Notice:  Undefined variable: PHP_SELF in try.php on line 37
<td><a href="?showpart=1.1">1.1</a></td>
Array
(
    [headers] => Array
        (
            [content-type] => multipart/related; boundary="REDACTED"; type="multipart/alternative"
        )

    [starting-pos] => 1650
    [starting-pos-body] => 1771
    [ending-pos] => 11115
    [ending-pos-body] => 11115
    [line-count] => 192
    [body-line-count] => 188
    [charset] => us-ascii
    [transfer-encoding] => 8bit
    [content-boundary] => REDACTED
    [content-type] => multipart/related
    [content-base] => /
)

<td>multipart/related</td>
PHP Notice:  Undefined index: content-disposition in try.php on line 45
<td></td>
PHP Notice:  Undefined index: disposition-filename in try.php on line 46
<td></td>
<td>us-ascii</td>
</tr><tr>
PHP Notice:  Undefined variable: PHP_SELF in try.php on line 37
<td><a href="?showpart=1.1.1">1.1.1</a></td>
Array
(
    [headers] => Array
        (
            [content-type] => multipart/alternative; boundary="REDACTED"
        )

    [starting-pos] => 1817
    [starting-pos-body] => 1911
    [ending-pos] => 5098
    [ending-pos-body] => 5098
    [line-count] => 102
    [body-line-count] => 99
    [charset] => us-ascii
    [transfer-encoding] => 8bit
    [content-boundary] => REDACTED
    [content-type] => multipart/alternative
    [content-base] => /
)

<td>multipart/alternative</td>
PHP Notice:  Undefined index: content-disposition in try.php on line 45
<td></td>
PHP Notice:  Undefined index: disposition-filename in try.php on line 46
<td></td>
<td>us-ascii</td>
</tr><tr>
PHP Notice:  Undefined variable: PHP_SELF in try.php on line 37
<td><a href="?showpart=1.1.1.1">1.1.1.1</a></td>
Array
(
    [headers] => Array
        (
            [content-type] => text/plain; charset="iso-8859-1"
            [content-transfer-encoding] => quoted-printable
        )

    [starting-pos] => 1957
    [starting-pos-body] => 2049
    [ending-pos] => 2210
    [ending-pos-body] => 2210
    [line-count] => 13
    [body-line-count] => 10
    [charset] => iso-8859-1
    [transfer-encoding] => quoted-printable
    [content-charset] => iso-8859-1
    [content-type] => text/plain
    [content-base] => /
)

<td>text/plain</td>
PHP Notice:  Undefined index: content-disposition in try.php on line 45
<td></td>
PHP Notice:  Undefined index: disposition-filename in try.php on line 46
<td></td>
<td>iso-8859-1</td>
</tr><tr>
PHP Notice:  Undefined variable: PHP_SELF in try.php on line 37
<td><a href="?showpart=1.1.1.2">1.1.1.2</a></td>
Array
(
    [headers] => Array
        (
            [content-type] => text/html; charset="iso-8859-1"
            [content-transfer-encoding] => quoted-printable
        )

    [starting-pos] => 2257
    [starting-pos-body] => 2348
    [ending-pos] => 5048
    [ending-pos-body] => 5048
    [line-count] => 81
    [body-line-count] => 78
    [charset] => iso-8859-1
    [transfer-encoding] => quoted-printable
    [content-charset] => iso-8859-1
    [content-type] => text/html
    [content-base] => /
)

<td>text/html</td>
PHP Notice:  Undefined index: content-disposition in try.php on line 45
<td></td>
PHP Notice:  Undefined index: disposition-filename in try.php on line 46
<td></td>
<td>iso-8859-1</td>
</tr><tr>
PHP Notice:  Undefined variable: PHP_SELF in try.php on line 37
<td><a href="?showpart=1.1.2">1.1.2</a></td>
Segmentation fault

**Version (please complete the following information):**
 - Version of mailparse: 3.0.3~dev20181093+2.1.7~dev20160128-1
 - Version of PHP: PHP 7.3
 - Version of php-mime-mail-parser: latest git version as of 2021-12-30 10:58 CET.

**Additional context**

**Comment by eXorus** [comment]
I'm sorry I don't see the try.php file and the mail4.txt.
Could you share it with us?

But most of the time if we have a segmentation fault it's more related to mailparse extension than php-mime-mail-parser.
