### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'PhpMimeMailParser\Parser' not found

### ISSUE THREAD

**Issue by Debuggingyourcode** [php-mime-mail-parser/php-mime-mail-parser#395]
**I have download the library by using composer & add this code in php file:**
```
require_once __DIR__.'/vendor/autoload.php';
$parser = new PhpMimeMailParser\Parser();
```

**But it return the error in log file:**
PHP Fatal error:  Uncaught Error: Class 'PhpMimeMailParser\Parser' not found

mailparse extension already installed on my server

**Comment by brapp0111** [comment]
I had the same problem.  I was able to get it working by using

`$parser = new eXorus\PhpMimeMailParser\Parser();`

to initialize it

**Comment by brapp0111** [comment]
A little follow-up to this issue.  When I installed `composer require php-mime-mail-parser/php-mime-mail-parser` composer installed version 1.0.  I'm not exactly sure why, but after I updated it to the current version (7.1.2 at this time) it worked properly. 

Hopefully this helps someone in the future.

**Comment by eXorus** [comment]
Hello

Be sure to use the last release version and not the master version that is the dev version.
So 7.1.2 right now.

And after to init the lib (example):
```php
require_once __DIR__.'/vendor/autoload.php';
$parser = new PhpMimeMailParser\Parser();
```

Here is my test:

**Create a folder**
```
mkdir bug395
cd bug395
```

**Download the lib (last release 7.1.2)**
```
composer require php-mime-mail-parser/php-mime-mail-parser
```

**Create a php file to test it and fill up with the example above:**
```
vi index.php
```

**Run the php script and no eror is displayed:**
```
php index.php
```

**Comment by vrgblzs** [comment]
It might help others, I had the same problem.  The _composer require php-mime-mail-parser/php-mime-mail-parser_ installed version 1.0 for me too - because I had not installed the mailparse php modul beforehand. The versions above 1.0 require this extension to be installed, so if the extension is missing, composer installs the version 1.0!

**Comment by eXorus** [comment]
Thanks! I deleted version 1.0 from Packagist. Hopefully, this will fix the issue.
