### ISSUE TITLE
Attachment class __construct arg need tweak

### ISSUE THREAD

**Issue by boisebuster** [php-mime-mail-parser/php-mime-mail-parser#397]
When calling $parser->saveAttachments(), this error gets thrown:

_A PHP Error was encountered
Severity: 8192

**Message: Required parameter $contentId follows optional parameter $contentDisposition**

Filename: PhpMimeMailParser/Attachment.php_

I was able to correct it by adding a default value to line 42 of Attachment.php:
FROM THIS:
public function __construct($filename, $contentType, $stream, $contentDisposition = 'attachment', $contentId, $headers = array())

TO THIS (adding =0 into $contentID argument)
public function __construct($filename, $contentType, $stream, $contentDisposition = 'attachment', $contentId=0, $headers = array())

**Comment by eXorus** [comment]
I guess it's only for a specific email.

Could you provide the raw version of the email to investigate because it's weird to have no contentId for an attachment?
