### ISSUE TITLE
mailparse returns false and gives warning if not able to parse file or string

### ISSUE THREAD

**Issue by mta59066** [php-mime-mail-parser/php-mime-mail-parser#408]
`mailparse_msg_parse()` used in `Parser::setText()` and `mailparse_msg_parse_file()` used in `Parser::setPath()` returns `false` and gives `E_WARNING` if it is not able to parse the content.

This results in code in `parse()` to throw `must be of type resource, bool given` here https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/8.0.0/src/Parser.php#L211 as `$this->resource` contains `false`.

This was a somewhat silent nuisance before php8 but now causes a `TypeError` and it is not possible to catch the specific reason or prevent the `E_WARNING` from outside.

**Comment by mta59066** [comment]
Test code is
```php
$file = __DIR__ .'/mails/issue408.eml';
$Parser = new Parser();
$Parser->setPath($file);
$Parser->getHeaders();
```
```
PHP Warning:  mailparse_msg_parse_file(): MIME message too complex
TypeError: mailparse_msg_get_structure(): Argument #1 ($fp) must be of type resource, bool given
```
[issue408.eml.zip](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/10360857/issue408.eml.zip)

**Comment by eXorus** [comment]
Thanks for the nice report, I will checkout.
