### ISSUE TITLE
Usage of `mb_encoding_aliases()` in `PhpMimeMailParser\Charset` raises PHP 8.2 deprecation notices 

### ISSUE THREAD

**Issue by LeSuisse** [php-mime-mail-parser/php-mime-mail-parser#413]
Trace:
```
PHP Deprecated:  mb_encoding_aliases(): Handling Base64 via mbstring is deprecated; use base64_encode/base64_decode instead in /vendor/php-mime-mail-parser/php-mime-mail-parser/src/Charset.php on line 361
PHP Deprecated:  mb_encoding_aliases(): Handling Uuencode via mbstring is deprecated; use convert_uuencode/convert_uudecode instead in /vendor/php-mime-mail-parser/php-mime-mail-parser/src/Charset.php on line 361
PHP Deprecated:  mb_encoding_aliases(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead in /vendor/php-mime-mail-parser/php-mime-mail-parser/src/Charset.php on line 361
PHP Deprecated:  mb_encoding_aliases(): Handling QPrint via mbstring is deprecated; use quoted_printable_encode/quoted_printable_decode instead in /vendor/php-mime-mail-parser/php-mime-mail-parser/src/Charset.php on line 361
```

I were going to open a PR but I'm not sure how to best handling it.

Maybe removing `base64`, `uuencode`, `html-entities` and `quoted-printable` from the output of `mb_list_encodings()` would be good enough?

https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/4c69f5888a1b483c44efe4bd6c46fe295a7db2f1/src/Charset.php#L358

**Comment by iquito** [comment]
This is also the main deprecation message in one of my applications since switching to PHP 8.2, would be great to adjust it!

**Comment by eXorus** [comment]
Thanks for the report, not sure to understand the issue yet.

Maybe we should move to another method like [convert_uuencode](https://www.php.net/manual/en/function.convert-uuencode.php).

Do you know why I don't see any deprecation notices on the last test run on PHP 8.2:
https://github.com/php-mime-mail-parser/php-mime-mail-parser/actions/runs/4324420290/jobs/7549225816

**Comment by LeSuisse** [comment]
> Maybe we should move to another method like [convert_uuencode](https://www.php.net/manual/en/function.convert-uuencode.php).

I'm not sure this is needed, since `$charset` will never be `base64`, `uuencode`, `html-entities` or `quoted-printable`.

Something like does not seem to trigger any regressions:
```diff
--- a/src/Charset.php
+++ b/src/Charset.php
@@ -355,7 +355,7 @@ class Charset implements CharsetManager
             'strtolower',
             array_unique(
                 array_merge(
-                    $enc = mb_list_encodings(),
+                    $enc = array_diff(mb_list_encodings(), ['BASE64', 'UUENCODE', 'HTML-ENTITIES', 'Quoted-Printable']),
                     call_user_func_array(
                         'array_merge',
                         array_map(
```

> Do you know why I don't see any deprecation notices on the last test run on PHP 8.2:
> https://github.com/php-mime-mail-parser/php-mime-mail-parser/actions/runs/4324420290/jobs/7549225816

Yes, it depends on the value you have set for `error_reporting`, see #415

**Comment by daniesy** [comment]
This issue throws a 502 error in Laravel Valet configuration: `upstream prematurely closed connection while reading response header from upstream, client...`

@LeSuisse suggestion seems to fix it.

**Comment by eXorus** [comment]
Sorry, I don't have much time at the moment to dedicate to php-mime-mail-parser (a new baby for those who know). If someone would like to make a clean PR with tests, I would be very happy to review and merge it. Thank you in advance.

**Comment by eXorus** [comment]
I wanted to express my gratitude for your assistance in addressing the bug, and I apologize for the delay in getting back to you on the PR. Your input was truly valuable. I'd like to inform you that the release is now available.
https://github.com/php-mime-mail-parser/php-mime-mail-parser/releases/tag/8.0.2
