### ISSUE TITLE
Call to undefined function PhpMimeMailParser\mailparse_msg_create() on PHP 8.2

### ISSUE THREAD

**Issue by ahsan-official82** [php-mime-mail-parser/php-mime-mail-parser#423]

**Comment by danrhodes** [comment]
I have the same issue on PHP 8.1 as well.

**Comment by eXorus** [comment]
Are you sure you have installed mailparse? The php-mime-mail-parser library requires mailparse to function properly. To verify, you can run the following command `php -m | grep mailparse`, which should return "mailparse".
