### ISSUE TITLE
Class 'PhpMimeMailParser\Charset' not found

### ISSUE THREAD

**Issue by rohittb** [php-mime-mail-parser/php-mime-mail-parser#432]
Hello we are using 7.1 version of PhpMimeMailParser and while setting text

if(count($result_email)>0)
		{
			$result = $this->Amazon->s3->getObject([
			'Bucket' => bucketname,
			'Key' => "correspondence/email/".$result_email[0]['message_id'],
			
		]);
		
		 $emailContent = $result['Body']->getContents();
		 $parser = new Parser();
		
     $parser->setText($emailContent);
    
    // // Get the plain text message
    $messageText = $parser->getMessageBody('text');

**Comment by eXorus** [comment]
It means you didn't install the project correctly. Please review your installation

`composer require php-mime-mail-parser/php-mime-mail-parser`

AND

`require_once __DIR__.'/vendor/autoload.php';`
