### ISSUE TITLE
Mailparse.so not available  while installing 

### ISSUE THREAD

**Issue by MaharshiGopisetti** [php-mime-mail-parser/php-mime-mail-parser#438]
its does not installing 'sudo pecl install mailparse' command unable to load library properly tried many different patterns to loading 'sudo apt install php-dev' command even though its been diffcult to load it
![Screenshot from 2024-05-28 13-11-21](https://github.com/php-mime-mail-parser/php-mime-mail-parser/assets/134258005/d2cd96fb-5845-4f69-94e4-89282034f605)
![Screenshot from 2024-05-28 13-13-57](https://github.com/php-mime-mail-parser/php-mime-mail-parser/assets/134258005/553b8882-3a62-4b6b-b35b-5b7883fbcddf)
![Screenshot from 2024-05-28 13-18-07](https://github.com/php-mime-mail-parser/php-mime-mail-parser/assets/134258005/07301f84-1e89-4aef-bc65-4eb51f38da73)
![Screenshot from 2024-05-28 15-01-12](https://github.com/php-mime-mail-parser/php-mime-mail-parser/assets/134258005/884c58f4-494a-4c99-8afb-272b2406c4f1)
![Screenshot from 2024-05-28 15-07-26](https://github.com/php-mime-mail-parser/php-mime-mail-parser/assets/134258005/7dc424e3-ecea-45a8-b38d-5517bea251d9)
![Screenshot from 2024-05-28 16-34-52](https://github.com/php-mime-mail-parser/php-mime-mail-parser/assets/134258005/837cfe1a-1580-41c4-b5e3-0ed5f02d766e)

**Comment by MaharshiGopisetti** [comment]
I tried other libraries to use parser still its been showing the same  issue provide a proper suggestion to resolve these issue direct method is working even though we need to view properly so **its been a week working on this need the solution to work solicit**
![Screenshot from 2024-05-28 18-34-01](https://github.com/php-mime-mail-parser/php-mime-mail-parser/assets/134258005/0d75ec7a-04ad-4aa7-8719-b0e75b4e3587)

**Comment by eXorus** [comment]
Install mbstring as the error message says.
I don't have Ubuntu, but you can find support on your favorite search engine by typing "install mailparse ubuntu."

Have you tried this as indicated in my readme? It's the solution I used several years ago on Ubuntu.
```
git clone https://github.com/php/pecl-mail-mailparse.git
cd pecl-mail-mailparse
phpize
./configure
sed -i 's/#if\s!HAVE_MBSTRING/#ifndef MBFL_MBFILTER_H/' ./mailparse.c
make
sudo mv modules/mailparse.so /usr/lib/php/AAAAMMDD/
echo "extension=mailparse.so" | sudo tee /etc/php/7.1/mods-available/mailparse.ini
sudo phpenmod mailparse
```

**Comment by eXorus** [comment]
Or use my hosted solution mailcare.io and you don't have to manage a mail server, install mailparse ou php-mime-mail-parser.

**Comment by MaharshiGopisetti** [comment]
thanks for th

> Install mbstring as the error message says. I don't have Ubuntu, but you can find support on your favorite search engine by typing "install mailparse ubuntu."
> 
> Have you tried this as indicated in my readme? It's the solution I used several years ago on Ubuntu.
> 
> ```
> git clone https://github.com/php/pecl-mail-mailparse.git
> cd pecl-mail-mailparse
> phpize
> ./configure
> sed -i 's/#if\s!HAVE_MBSTRING/#ifndef MBFL_MBFILTER_H/' ./mailparse.c
> make
> sudo mv modules/mailparse.so /usr/lib/php/AAAAMMDD/
> echo "extension=mailparse.so" | sudo tee /etc/php/7.1/mods-available/mailparse.ini
> sudo phpenmod mailparse
> ```

its worked well with this
