### ISSUE TITLE
Possibility for longer random attachment names when using ATTACHMENT_RANDOM_FILENAME?

### ISSUE THREAD

**Issue by wrongecho** [php-mime-mail-parser/php-mime-mail-parser#439]
Hey there,
I love this project, it's very useful - THANK YOU for devoting your time to it.

I was hoping there was a way we could influence the way email attachments are named when we use the `Parser::ATTACHMENT_RANDOM_FILENAME` case? Currently I can see it generates names like `666606b58b9e2` which aren't very long or secure. I looked into the Attachment class and it seems you use the `uniqid` function & this doesn't appear to be configurable.

As my project (presumably like many others) uses your default filenames when saving attachments, it's _possible_ that these could be guessed by a third party (e.g. someone brute forcing the /uploads/ directory). I know we can individually choose file names, but I'd rather not!

Would you please consider moving to a more secure way of these random generating file names & making them longer (at least 16 characters - [here's](https://pastebin.com/7LXLKkGh) a function we use a lot)?

Many thanks in advance :)

**Comment by eXorus** [comment]
Thank you for your feedback. Yes, it is possible to provide a method more secure than uniqid, but we need to determine which one to use as there are many options. Security, uniqueness, readability, and ease of use are all important considerations...

**Comment by eXorus** [comment]
Maybe we could use `hash('xxh128', $value)`
https://securinglaravel.com/security-tip-stop-using-md5-and-sha-1/?ref=securing-laravel-newsletter
