### ISSUE TITLE
Can't install with Composer

### ISSUE THREAD

**Issue by wp4nuv** [php-mime-mail-parser/php-mime-mail-parser#44]
Bonjour, 
I currently work with a server that does not allow execution of phar files, so even after installing Composer I can't make it install your parser. I have attempted to call the parser directly from my script but it fails when attempting to create an instance of Charset.
I have tried adding a new 'use' line on Parser.php pointing to Charset, but still I get back a 'class not found' error.

Desole de vous ennuiyer avec ce probleme. (Excusez-moi aussi pour la manque d'accents.. ce clavier est Americain).

Merci

Pedro Maldonado

**Comment by wp4nuv** [comment]
Sorry to bother.. I figured it out by trial and error.. sorry for the trouble. 

P.

**Comment by clementhk** [comment]
I've all done that @wp4nuv, just make sure you close it. :)
