### ISSUE TITLE
cannot parse msg form MS outlook 

### ISSUE THREAD

**Issue by satis-m** [php-mime-mail-parser/php-mime-mail-parser#440]
i have create script that simply just parse email and display html for preview (using laravel framework)
.eml file works fine with script but doesnot work with .msg file

it shows false on these
$rawHeaderTo = $parser->getHeader('to');
$rawHeaderFrom = $parser->getHeader('from');
$subject = $parser->getHeader('subject');

and empty on 
$parser->getMessageBody('html')

i have attached .msg 
[test email parser.zip](https://github.com/user-attachments/files/15952285/test.email.parser.zip)
sample file that i have tested

**Comment by eXorus** [comment]
It's normal that the .msg format is a binary format. You need to use another service to convert it into .txt and be able to parse it with php-mime-mail-parser.

https://github.com/php-mime-mail-parser/php-mime-mail-parser/issues/226
