### ISSUE TITLE
Undefined array key "eof" when calling Parser::setStream()

### ISSUE THREAD

**Issue by hubipe** [php-mime-mail-parser/php-mime-mail-parser#444]
Hi,
I've encountered an undefined array key eof warning when calling method Parser::setStream():
![image](https://github.com/user-attachments/assets/407c4633-fae1-4794-8179-94e1c2d905c7)

I've noticed, this problem has been addressed here - https://github.com/php-mime-mail-parser/php-mime-mail-parser/pull/315 and merged, but it seems it is not in the newest version (8.0.3).

Shouldn't the pull request #315 be merged to the 8 releases?

**Comment by eXorus** [comment]
Good catch! The fix was actually made for a big release that never got published, and I totally missed porting it to the current production version. I’ll make sure it’s included in the next release. Thanks for pointing it out!
