### ISSUE TITLE
Can't read $parser->getHeader('from') properly

### ISSUE THREAD

**Issue by mitebu** [php-mime-mail-parser/php-mime-mail-parser#448]
Hi, I'm having this issue.

I have the .eml file extracted with the following information:

> From: "Amazon.es" <shipment-tracking@amazon.es>

When I'm executing the code:

`require_once __DIR__.'/vendor/autoload.php';`
`$path = 'path/to/email.eml';`
`$parser = new eXorus\PhpMimeMailParser\Parser();`
`$parser->setPath($path);`
`$rawHeaderFrom = $parser->getHeader('from');`

Expected output:

> "Amazon.es" <shipment-tracking@amazon.es>

Real output:

> Amazon.es

Also tried to use $arrayHeaderFrom = $parser->getAddresses('from'); but the array was empty.

Please help me to solve this issue, and be able to extract the email from the header.

Thanks in advance.

EDIT: I have discovered when I try to open the file with file_get_contents($path); after echo the "From:" header doesn't contain the email between <>, but using htmlentities(file_get_contents($path)); after echo the "From:" header contains the email between <>. Maybe is possible to modify the library to make this change or make it work?

**Comment by eXorus** [comment]
Sorry, I am unable to reproduce the issue with the following code:

```php
$parser = new Parser();
$parser->setText(<<<MIME
From: "Amazon.es" shipment-tracking@amazon.es
To: destinataire@example.com
Subject: Exemple d'e-mail MIME avec en-tête Received
Received: from first line
Received: from second line

Content-Type: text/plain

hello world!
MIME
);
$from = $parser->getHeader('from');
$this->assertEquals('"Amazon.es" shipment-tracking@amazon.es', $from);
```

You should ensure that you are using at least version 8.0.3. You can check this by running: `composer show php-mime-mail-parser/php-mime-mail-parser`
