### ISSUE TITLE
Readme is outdated

### ISSUE THREAD

**Issue by alr888rav** [php-mime-mail-parser/php-mime-mail-parser#451]
Please update info "How do I use it?" to real information: vendor/php-mime-mail-parser/php-mime-mail-parser/README.md

**Comment by eXorus** [comment]
What do you mean by "real information" ? it's already real information.

**Comment by alr888rav** [comment]
on 'Code' page:

```
require_once __DIR__.'/vendor/autoload.php';
 
$path = 'path/to/email.eml';
$parser = new PhpMimeMailParser\Parser();   -- class not found  miss eXorus
$arrayHeaderTo = $parser->getAddresses('to');
// return [["display"=>"test", "address"=>"test@example.com", false]]  -- non exist function...
...
```

But this got error not found class, non exist function....
Internal readme  has:
```
require_once __DIR__.'/vendor/autoload.php';

$path = 'path/to/mail.txt';
$Parser = new eXorus\PhpMimeMailParser\Parser();

//There are three input methods of the mime mail to be parsed
//specify a file path to the mime mail :
$Parser->setPath($path); 

// Or specify a php file resource (stream) to the mime mail :
$Parser->setStream(fopen($path, "r"));

...
```

**Comment by eXorus** [comment]
I think you don't have the right package installed and not the last version you should check. Do you have the 8.0.4 ?

**Comment by alr888rav** [comment]
You are right, but how it happened, I don`t know. I always use composer.
Any way thank you so much.
