### ISSUE TITLE
Splitting email address

### ISSUE THREAD

**Issue by piernik** [php-mime-mail-parser/php-mime-mail-parser#51]
From Your code you get `from` or `to`  like `name <email>`. I think You can split it to array like 
```
array(
    'name'=>'name',
    'email'=>'email'
);
```

Here is code to do that (from http://stackoverflow.com/questions/16685416/split-full-email-addresses-into-name-and-email)
```
private function email_split($str) {
        $str .=" ";
        $sPattern = '/([\w\s\'\"]+[\s]+)?(<)?(([\w-\.]+)@((?:[\w]+\.)+)([a-zA-Z]{2,4}))?(>)?/';
        preg_match($sPattern, $str, $aMatch);
        $name = (isset($aMatch[1])) ? $aMatch[1] : '';
        $email = (isset($aMatch[3])) ? $aMatch[3] : '';
        return array('name' => trim($name), 'email' => trim($email));
    }
```

**Comment by eXorus** [comment]
Or we can used http://php.net/manual/en/function.imap-rfc822-parse-adrlist.php

**Comment by piernik** [comment]
It's much better - have to test it. Thanks

**Comment by michaelkay** [comment]
I added the routine above and the following code to parser.php to get the desired result. When I need the to: or from: address I call getHeaderAddress() instead ot getHeader().
`    /**

     * Retrieve a specific Email Header and split into the two email parts

     * @return String

     * @param $name String Header name

     */

    public function getHeaderAddress($name)

    {

        $rawHeader = $this->getRawHeader($name);

        if ($rawHeader === false) {

            return false;

        }

        return $this->email_split($this->decodeHeader($rawHeader));

    }`

**Comment by patie** [comment]
@eXorus why not http://php.net/manual/en/function.mailparse-rfc822-parse-addresses.php from mailparse lib? :)

**Comment by eXorus** [comment]
Sure, It will be better :)
Someone to do a pull request ?

**Comment by patie** [comment]
maybe next week

**Comment by eXorus** [comment]
So I will do it tomorrow

getAddressesFrom / getAddressesTo ?
or
getFromAddresses / getToAddresses ?
