### ISSUE TITLE
PECL mailparse package not available

### ISSUE THREAD

**Issue by RokSiEu** [php-mime-mail-parser/php-mime-mail-parser#52]
Hi,

mailparse can not be installed from PECL because of this error:

```
No releases available for package "pecl.php.net/mailparse"
```
Running on:
Windows 8
XAMPP 
PHP 5.6.8 (cli) (built: Apr 15 2015 15:07:09)

**Comment by eXorus** [comment]
It's true http://php.net/manual/en/mailparse.installation.php

Mailparse doesn't exist for Windows. Sorry I can't help you and mailparse is mandatory for php-mime-mail-parser
