### ISSUE TITLE
Meeting request not recognised

### ISSUE THREAD

**Issue by pdegruijter** [php-mime-mail-parser/php-mime-mail-parser#53]
![schermafbeelding 2015-05-08 om 17 03 13](https://cloud.githubusercontent.com/assets/12344883/7538979/2509afb0-f5a4-11e4-87aa-2b3927ae2dab.png)

When I receive an invitation from an exchange server, this sometimes is embedded in the text as content-type "text/calendar" and this is not recognized as an attachment.

How can I handle these?

**Comment by clementhk** [comment]
This is from my own meeting handling program.

```
			$headers = imap_fetchheader($mailbox, $uid, FT_UID);
			$body = imap_body($mailbox, $uid, FT_UID);
			$Parser = new PhpMimeMailParser\Parser();
			$Parser->setText($headers."\n".$body);

			$attachments = $Parser->getAttachments();
			foreach($attachments as $attachment) {
				if($attachment->contentType == 'text/calendar') {
					try {
						$cal = VObject\Reader::read($attachment->getContent());
						if(!method_exists($cal->METHOD, "getValue") || ($cal->METHOD->getValue() !== 'REQUEST' && $cal->METHOD->getValue() !== 'CANCEL')) {
							unset($cal);
						} else {
							break;
						}
					} catch(\Exception $e) {
						unset($cal);
					}
				}
			}
```

**Comment by eXorus** [comment]
It could be a good idea to parse text/calendar.

I'm waiting your code ? :)

**Comment by pdegruijter** [comment]
For now I have used the following, but it sometimes delivers the meeting request twice.

	public function getInvitation($type = 'text') {
		$body = false;
		$mime_types = array(
			'text'=> 'text/calendar',

		);
		if (in_array($type, array_keys($mime_types))) {
			foreach($this->parts as $part) {
				if ($this->getPart('content-type', $part) == $mime_types[$type]) {
					$body    = $this->getPartBody($part);
					//$body    = $this->decode($this->getPartBody($part), array_key_exists('content-transfer-encoding', $headers) ? $headers['content-transfer-encoding'] : '');
					break;
				}
			}
		} else {
			throw new Exception('Invalid type specified for MimeMailParser::getMessageBody. "type" can either be text or html.');
		}
		return $body;
	}

**Comment by eXorus** [comment]
I'm closing this issue because it has been fixed.

Test: m0020 with ParserTest.php
