### ISSUE TITLE
Parser::getPartCharset else condition

### ISSUE THREAD

**Issue by cyof** [php-mime-mail-parser/php-mime-mail-parser#58]
The else condition Parser::getPartCharset seems odd. The else is only reached if $part['charset'] is not set. But it is still used in the getCharsetAlias call.

**Comment by clementhk** [comment]
Confirmed, @eXorus

**Comment by eXorus** [comment]
It's stupid :)
Thanks

**Comment by clementhk** [comment]
Shouldn't it be something like this?

```
if (isset($part['charset'])) {
    $charset = $this->charset->getCharsetAlias($part['charset']);
}
```

**Comment by eXorus** [comment]
It's better. Thanks
