### ISSUE TITLE
Support for PHP 5.3

### ISSUE THREAD

**Issue by mcrbids** [php-mime-mail-parser/php-mime-mail-parser#59]
I'm using CentOS 6 based server with stock php 5.3. Seems to work fine, and better than the original google code project from which this was forked. 

Is there a specific reason 5.4 and up only are mentioned?

**Comment by eXorus** [comment]
The only reason is that PHP 5.3 is officially supported until 14 August 2014. So it's time for you to upgrade to 5.4.
