### ISSUE TITLE
forward parsed mail

### ISSUE THREAD

**Issue by Remo** [php-mime-mail-parser/php-mime-mail-parser#62]
I know this isn't exactly the purpose of a mime-mail-parser library, but did anyone ever tried to forward a parsed mail? I'm basically just trying to fetch a mail by POP3/IMAP and then forward it to another account.

Any pointers appreciated! I know that I could parse each part but I'm looking for a more raw solution to ensure that I don't break the mail or miss a part.

**Comment by noobiwan** [comment]
Without getting into specifics, you can just get the raw body of the
message and resend it using new headers. You could use *imap_body* from the
IMAP library.

**Comment by Remo** [comment]
I guess I could but I'm fairly confident that I'll have to modify some parts as point and I wanted to be on the side where I can tell everyone that everything is possible ;-)

**Comment by noobiwan** [comment]
The you would need a library to create a mime message, like SwiftMailer and
reassemble the parts.

**Comment by Remo** [comment]
I think I'll give zend framework a try, from what I can see they use the same classes to fetch and send mails which would make things quite a bit easier as I wouldn't have to convert mime-mail-parser classes to swift mailer classes.. thanks
