### ISSUE TITLE
Attachment content in constructor?

### ISSUE THREAD

**Issue by noniagriconomie** [php-mime-mail-parser/php-mime-mail-parser#64]
Hello, 

Just a question, why does the attachment content is not set (https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/master/src/Attachment.php#L57) when ```getAttachments()``` is called?

Many thanks,

**Comment by eXorus** [comment]
Hello,

Good question, maybe because de attachment is always created by stream and never by content.

Maybe we can delete it :)

**Comment by noniagriconomie** [comment]
Ok I see, 

Thank you for your fast answer :)
