### ISSUE TITLE
utf-8 convert

### ISSUE THREAD

**Issue by webicdesign** [php-mime-mail-parser/php-mime-mail-parser#66]
problem in utf-8 language ( like persian )
subject is 'عنوان'
but return '=?UTF-8?B?2LnZhtmI2KfZhg==?='
how can i convert that?

**Comment by eXorus** [comment]
Hello,

Could you reply with the full raw email and the expected result ?

**Comment by webicdesign** [comment]
solved!
i must use imap_utf8($subject)
thanks eXorus
