### ISSUE TITLE
I can't install mailparse

### ISSUE THREAD

**Issue by L0rD59** [php-mime-mail-parser/php-mime-mail-parser#70]
Hi all,

Sorry for this issue, but i'm trying to install mailparse extension without success : 

See below my test : 

`docker run -it --rm php:5.6-cli bash`

`root@3cbcf6168f3e:/# docker-php-ext-configure mbstring`

`root@3cbcf6168f3e:/# docker-php-ext-install mbstring`

mbstring is enabled : 
```
root@3cbcf6168f3e:/# php -m | grep 'mbstring'
mbstring
```
But : 

``` 
root@3cbcf6168f3e:/# pecl install mailparse
pecl/mailparse requires PHP extension "mbstring"
No valid packages found
install failed
``` 

trying too without success : 
``` 
root@3cbcf6168f3e:/# pear install pecl/mailparse
downloading mailparse-2.1.6.tgz ...
Starting to download mailparse-2.1.6.tgz (36,538 bytes)
..........done: 36,538 bytes
9 source files, building
running: phpize

[......]

running: make
/bin/bash /tmp/pear/temp/pear-build-defaultuser9zXP1p/mailparse-2.1.6/libtool --mode=compile cc  -I. -I/tmp/pear/temp/mailparse -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuser9zXP1p/mailparse-2.1.6/include -I/tmp/pear/temp/pear-build-defaultuser9zXP1p/mailparse-2.1.6/main -I/tmp/pear/temp/mailparse -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/mailparse/mailparse.c -o mailparse.lo
mkdir .libs
 cc -I. -I/tmp/pear/temp/mailparse -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuser9zXP1p/mailparse-2.1.6/include -I/tmp/pear/temp/pear-build-defaultuser9zXP1p/mailparse-2.1.6/main -I/tmp/pear/temp/mailparse -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/mailparse/mailparse.c  -fPIC -DPIC -o .libs/mailparse.o
/tmp/pear/temp/mailparse/mailparse.c:34:2: error: #error The mailparse extension requires the mbstring extension!
 #error The mailparse extension requires the mbstring extension!
  ^
Makefile:187: recipe for target 'mailparse.lo' failed
make: *** [mailparse.lo] Error 1
ERROR: `make' failed
```

I've seen a issue about that but i dont know if is always active : https://support.zend.com/hc/en-us/articles/203408233-Compile-mailparse-extension-with-mbstring-dependency-

Thx for replies,
Best regards,

**Comment by eXorus** [comment]
Sorry I don't know why.
Disable safe_mode maybe ?
https://ma.ttias.be/installing-the-pecl-pear-mailparse-module-for-php-on-centos/

**Comment by L0rD59** [comment]
Hi,

Thx for reply,

I dont think so, safe_mode has been removed since 5.4

http://php.net/manual/en/ini.sect.safe-mode.php#ini.safe-mode

**Comment by eXorus** [comment]
what is your version et OS ?

**Comment by L0rD59** [comment]
OS : `Linux 3.16.0-55-generic #74~14.04.1-Ubuntu SMP Tue Nov 17 10:15:59 UTC 2015 x86_64 GNU/Linux` 

PHP : `PHP 5.6.14 (cli) (built: Oct 23 2015 20:53:27)`

**Comment by eXorus** [comment]
Some tips :
The difference between the "pear" and "pecl" commands is that "pecl"
disables php.ini so that you can overwrite extension .so or .dll files
that would otherwise be in use and locked for write. So, unless
mbstring is built into PHP (not a loaded module in php.ini), you won't
be able to install mailparse.

On my Ubuntu system, I had the same problem a couple days ago. I think
I finally figured out that I was missing the php5-dev package - did an
"apt-get install php5-dev", and suddenly PEAR and PECL worked much
better.

**Comment by ianchadwick** [comment]
Following this worked for me: https://support.zend.com/hc/en-us/articles/203408233-Compile-mailparse-extension-with-mbstring-dependency

**Comment by mapesa** [comment]
This worked for me: https://bugs.php.net/bug.php?id=71813

PHP 7.0 on Ubuntu 16.04

**Comment by checkphi** [comment]
Why is there no new version fixing this?

**Comment by eXorus** [comment]
This issue is not related to php-mime-mail-parser but to mailparse.

And the workaround (https://bugs.php.net/bug.php?id=71813 last comment) is working very well.
