### ISSUE TITLE
Namespace and class "Exception" not found

### ISSUE THREAD

**Issue by matcho** [php-mime-mail-parser/php-mime-mail-parser#71]
Hi,
When reaching a line throwing an exception, the following error occurs :
```
Fatal error: Class 'eXorus\PhpMimeMailParser\Exception' not found in (...)
```

Some quick research on the Web tends to show that calling class "Exception" along with "namespace eXorus\PhpMimeMailParser;" will make PHP search for class "eXorus\PhpMimeMailParser\Exception"; which seems pretty logical.

Adding a backslash before class name makes PHP search in default namespace, and solves the problem :
```
throw new \Exception (...)
```

I suppose the code you wrote works for you, but then... what am I missing ?
I'm using PHP v5.6.16 on Ubuntu

Thanks in advance,
Mathias

**Comment by eXorus** [comment]
Hello,

This package (eXorus/php-mime-mail-parser) is abandoned 
https://packagist.org/packages/exorus/php-mime-mail-parser

You need to use (php-mime-mail-parser/php-mime-mail-parser)
https://packagist.org/packages/php-mime-mail-parser/php-mime-mail-parser

You juste need to edit your composer.json to change eXorus to php-mime-mail-parser.

**Comment by matcho** [comment]
Thanks a lot and apologies for my mistake !
