### ISSUE TITLE
PHP Mail Parse + PHP 7

### ISSUE THREAD

**Issue by noniagriconomie** [php-mime-mail-parser/php-mime-mail-parser#73]
Hi

Just to know if any plan are made for support by the version 7 of php

Many thanks !

**Comment by eXorus** [comment]
Yes of course, php-mime-mail-parser is working on PHP7 I think but mailparse that we are using not.

So I'm waiting the availability of mailparse on PHP 7 :
https://github.com/php/pecl-mail-mailparse/pull/1#issuecomment-156637987

**Comment by sancospi** [comment]
malparse now has support for PHP 7

**Comment by eXorus** [comment]
doesn't work I don't know why for the moment. I need time :)

**Comment by sancospi** [comment]
It works for me

**Comment by eXorus** [comment]
Great it's almost done I need to add "Whitelisting Files for Code Coverage" to PhpUnit to fix the last error in Travis CI

**Comment by akorinek** [comment]
I'm using PhpMailParser 3.0.0 with PHP 7.0.1. I can see the extension being enabled in the phpinfo.php page. However, this code causes a PHP segmentation fault:

$Parser = new \eXorus\PhpMimeMailParser\Parser();
$Parser->setText($this->raw_input);

$this->raw_input can be empty or contain a string, doesn't make a difference. The same code works with 2.1.6 and PHP 5.6.

**Comment by eXorus** [comment]
First things I don't understand why are you using eXorus/php-mime-mail-parser instead of php-mime-mail-parser ?

PhpMimeMailParser doesn't exist in version 3.0.0, the last release is 2.1.4.

**Comment by akorinek** [comment]
I tried the following now:

added "php-mime-mail-parser/php-mime-mail-parser": "3.0.0" to composer.json. Ran composer update. It installed a few extra dependencies.

Then changed in the php code to 
$Parser = new \PhpMimeMailParser\Parser();
$Parser->setText($this->raw_input);

Same segmentation fault happens when I call the php code.

**Comment by akorinek** [comment]
This is my mailparse test suite result, 1 test fails, don't know if that's connected with this issue:

=====================================================================
PHP         : /usr/lib64/php7.0/bin/php
PHP_SAPI    : cli
PHP_VERSION : 7.0.1-pl0-gentoo
ZEND_VERSION: 3.0.0
PHP_OS      : Linux - Linux ccemserver 4.0.5-gentoo #1 SMP Tue Jul 14 08:36:48 EDT 2015 x86_64
INI actual  : /var/tmp/portage/dev-php/pecl-mailparse-3.0.0/work/php7.0/tmp-php.ini
More .INIs  :
CWD         : /var/tmp/portage/dev-php/pecl-mailparse-3.0.0/work/php7.0
Extra dirs  :
VALGRIND    : Not used
=====================================================================
TIME START 2016-01-06 21:53:27
=====================================================================
PASS Check for mailparse presence [tests/001.phpt]
PASS Check stream encoding [tests/002.phpt]
PASS Check handling of multiple To headers [tests/003.phpt]
PASS Check uudecode_all [tests/004.phpt]
PASS Check quoted-printable encoding generates S/MIME safe content [tests/005.phpt]
PASS Check extract_part_file [tests/006.phpt]
PASS Check RFC822 Conformance [tests/007.phpt]
PASS OO API Segfault when opening a file is not possible [tests/008.phpt]
PASS Multiple UUE attachments not recognized [tests/009.phpt]
PASS Multiple headers not parsed into arra bug #6862 [tests/010.phpt]
FAIL Check mailparse_determine_best_xfer_encoding [tests/011.phpt]
PASS Check mailparse_mimemessage_extract_uue [tests/012.phpt]
PASS Parse messages in testdata dir [tests/parse_test_messages.phpt]
=====================================================================
TIME END 2016-01-06 21:53:27

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   42
---------------------------------------------------------------------

Number of tests :   13                13
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    1 (  7.7%) (  7.7%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   12 ( 92.3%) ( 92.3%)
---------------------------------------------------------------------
Time taken      :    0 seconds
=====================================================================

**Comment by akorinek** [comment]
I tried this simple script directly, seems to work without segfaulting. This is basically what the parser setText function does:

<?php
$r = mailparse_msg_create();
mailparse_msg_parse($r, "test");
$st = mailparse_msg_get_structure($r);
var_dump($st);
$part = mailparse_msg_get_part($r,1);
$part2 = mailparse_msg_get_part_data($part);
var_dump($part2);

**Comment by t202wes** [comment]
Who uses PHP 7+?

**Comment by eXorus** [comment]
Not me I try to understand the issue "segmentation fault", is it PhpUnit, MailParse, or php-mime-mail-parser ... ?

**Comment by eXorus** [comment]
So

Segmentation fault for that :
```php
<?php
require_once __DIR__.'/vendor/autoload.php';

$path = 'tests/mails/m0001';
$Parser = new PhpMimeMailParser\Parser();
$Parser->setPath($path);
```

The same code without mimemailparser, I have also a segmentation fault :
```php
$path = 'tests/mails/m0001';

$resource = mailparse_msg_parse_file($path);
$stream = fopen($path, 'r');

$structure = mailparse_msg_get_structure($resource);
$parts = array();
foreach ($structure as $part_id) {
            $part = mailparse_msg_get_part($resource, $part_id);
            $parts[$part_id] = mailparse_msg_get_part_data($part);
}

if (is_resource($stream)) {
	fclose($stream);
}
if (is_resource($resource)) {
    mailparse_msg_free($resource);
}
```

So the issue is related to mailparse_msg_free($resource);

**Comment by mauriziomarini** [comment]
I have stille this error

make test

Build complete.
Don't forget to run 'make test'.


=====================================================================
PHP         : /opt/php-7.1/bin/php 
PHP_SAPI    : cli
PHP_VERSION : 7.1.14
ZEND_VERSION: 3.1.0
PHP_OS      : Linux - Linux xxx.xxx.xxx 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64
INI actual  : /usr/local/src/mailparse-3.0.2/tmp-php.ini
More .INIs  :   
---------------------------------------------------------------------
PHP         : /opt/php-7.1/bin/phpdbg 
PHP_SAPI    : phpdbg
PHP_VERSION : 7.1.14
ZEND_VERSION: 3.1.0
PHP_OS      : Linux - Linux xxx.x.x.x.x. 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64
INI actual  : /usr/local/src/mailparse-3.0.2/tmp-php.ini
More .INIs  : 
---------------------------------------------------------------------
CWD         : /usr/local/src/mailparse-3.0.2
Extra dirs  : 
VALGRIND    : Not used
=====================================================================
TIME START 2018-04-12 11:25:03
=====================================================================
PASS Check for mailparse presence [tests/001.phpt] 
PASS Check stream encoding [tests/002.phpt] 
PASS Check handling of multiple To headers [tests/003.phpt] 
PASS Check uudecode_all [tests/004.phpt] 
PASS Check quoted-printable encoding generates S/MIME safe content [tests/005.phpt] 
PASS Check extract_part_file [tests/006.phpt] 
PASS Check RFC822 Conformance [tests/007.phpt] 
PASS OO API Segfault when opening a file is not possible [tests/008.phpt] 
PASS Multiple UUE attachments not recognized [tests/009.phpt] 
PASS Multiple headers not parsed into arra bug #6862 [tests/010.phpt] 
FAIL Check mailparse_determine_best_xfer_encoding [tests/011.phpt] 
PASS Check mailparse_mimemessage_extract_uue [tests/012.phpt] 
PASS Check mailparse_mimemessage_extract_uue [tests/013.phpt] 
FAIL mailparse_msg_free causes double free segfault [tests/bug001.phpt] 
PASS Parse messages in testdata dir [tests/parse_test_messages.phpt] 
=====================================================================
TIME END 2018-04-12 11:25:04

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   52
---------------------------------------------------------------------

Number of tests :   15                15
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    2 ( 13.3%) ( 13.3%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   13 ( 86.7%) ( 86.7%)
---------------------------------------------------------------------
Time taken      :    1 seconds
=====================================================================

=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
Check mailparse_determine_best_xfer_encoding [tests/011.phpt]
mailparse_msg_free causes double free segfault [tests/bug001.phpt]
=====================================================================

**Comment by eXorus** [comment]
Why do you want to build and test mailparse ?

Use pecl install

**Comment by benjamw** [comment]
Some people have to build. `pecl install` doesn't work for custom PHP packages in custom OSs.
So would you mind terribly either updating the tests that need to be updated, or updating the package to pass the tests?

**Comment by benjamw** [comment]
It looks like in the `011.phpt` test, the expected output is 6 values, but there are only 4 `.txt` files in the `testdata` directory.

In the `bug001.phpt` test, the file it's looking for `testdata/m0001.txt` is non-existent.
