### ISSUE TITLE
Install not easy contrary to advertised

### ISSUE THREAD

**Issue by unamedplayer** [php-mime-mail-parser/php-mime-mail-parser#75]
requires 3 package managers, composer, pecl and apt. Kind of a rant but I'm flabbergasted by this emerging trend. "Composer will install dependencies! Oops it doesn't really there are other requirements, PECL will! Oops, just kidding."

Why not simply use the lowest common denominator that is apt?

Anyways, would love to use but installing 2 and using 3 package managers to parse emails is beyond my will and I'm opposed to it in principle.

It should also be noted that all 3 package managers are independent from one another, if php5-imap changes, the other 2 will be none the wiser. So the great problem of dependencies that package managers solve is out the window with such an approach.

Sorry for the rant.

**Comment by eXorus** [comment]
You are right but I have no other solution.
The goal of PhpMimeMailParser was to facilitate email parsing and it's work very well. I'm PHP man and I don't know how to create PECL or APT package, if you have the time to do that go to it

It's 15 seconds to install everything : apt-get install php5-imap, pecl install mailparse et composer require php-mime-mail-parser/php-mime-mail-parser

I would like to replace pecl mailparse but I didn't know a php package to do that and I think the solution will be more slow.

I agree with you but I can't do anything to solve this issue so I'm closing it.

Best wishes for the New Year
