### ISSUE TITLE
Combining split messages

### ISSUE THREAD

**Issue by pdegruijter** [php-mime-mail-parser/php-mime-mail-parser#76]
Hi, some scanners split messages at a certain amount of Mb. Usually you can influence this, but not always. In the mail header I can see Content-Type: message/partial; number=1; total=2; id="<20160114.095021233.0012@smtp.heldenvan.nu>"

The other part contains of course number=2; total=2

is there functionality to recognise this and combine the two messages?

Regs,
Peter

**Comment by eXorus** [comment]
I'm not sure that "message/partial" is standard according to RFC.
There is no functionality to recognise this and combine the two message for the moment.

**Comment by pdegruijter** [comment]
It's also two messages, which make it very difficult to handle within the mail parser. I will go towards recognising it being a split message and separating them from the rest for further processing.

Close the issue please.
