### ISSUE TITLE
Reply-to header

### ISSUE THREAD

**Issue by patie** [php-mime-mail-parser/php-mime-mail-parser#80]
Hi,

when i use php imap 
`imap_fetchheader($imapStream, $mailId, FT_UID);`
there is no reply-to header (like in php-mime-mail-parser mailparse wrapper)

but, when i use
`imap_rfc822_parse_headers(imap_fetchheader($imapStream, $mailId, FT_UID));`
there is reply-to header (created from other headers??)

so what is right way?
1. reply-to header must be in raw email
2. imap_rfc822_parse_headers do it right. if yes, how can i get reply-to from php-mime-mail-parser

i hope its clear whats going on :)

**Comment by eXorus** [comment]
Do you have the raw email ?

**Comment by patie** [comment]
all emails without reply-to header

**Comment by eXorus** [comment]
If your email doesn't have reply-to header in the raw email this is normal that PhpMimeMailParser return empty string for reply-to header.

PhpMimeMailParser is a parser so it just a reader of the raw email.

If you use imap you don't need to use PhpMimeMailParser, imap can give you all the information you want.

**Comment by patie** [comment]
you dont understand what is problem :) 

imap_rfc822_parse_headers(imap_fetchheader($imapStream, $mailId, FT_UID)); return reply-to even if the email does not contain such a header.. so my question is - its ok or its bug?

**Comment by eXorus** [comment]
There is no bug in php-mime-mail-parser because I don't create fields, I just show exactly what the message contains.

imap_rfc822_parse_headers create fields like Reply-To and Sender that's their choice.

> This function is marked as internal function by the c-client library and should not be used by php directly.
> 
> Please be aware that the result will always contain fields that have not been set in the message. For example reply_to and sender will always be set even if there is no Reply-To and Sender header fields are defined in the message.

**Comment by patie** [comment]
ok
