### ISSUE TITLE
filenames not equal

### ISSUE THREAD

**Issue by patie** [php-mime-mail-parser/php-mime-mail-parser#81]
# Hi,

im testing emails in our application, we have array with emails, and attachments in array...

== and assertEqual return false

var_dumps:
`string(21) "testovací súbor.txt"` filename string from array
`string(23) "testovací súbor.txt"` $attachment->->getFilename()

when i try mb_detect_encoding both return UTF-8 (probably its not true)

in hex
`string(42) "746573746f766163c3ad2073c3ba626f722e747874"` filename string from array
`string(46) "746573746f76616369cc81207375cc81626f722e747874"` $attachment->->getFilename()

any idea? :)

**Comment by patie** [comment]
i think its because some clients encode filename accented one character as two..

http://php.net/manual/en/normalizer.normalize.php solve problem

im interested if somebody know about cleaner solution

**Comment by eXorus** [comment]
Hi,
I don't understrand what are you trying to do. Do you want to add another email test ?

The array is just the expected result I want for emails tests. So if the expected result is "testovací súbor.txt" you need to put this in a array. That's all.
If the result is not what you expect so maybe there is another issue with encoding.

**Comment by patie** [comment]
@eXorus nope, we writing test in our applications.

problem is filename - string from php file "testovací súbor.txt" is length 21 and parsed from raw mail is 23 (should be 21, i think problem is accented char is treated as 2)

**Comment by eXorus** [comment]
So it's an issue about filename encoding. Do you try this string in another field like subject ?
Subject field has better decoding I think.
If it's working well for subject maybe I need to check the encoding chain between subject and filename attachment to found the issue.

**Comment by etmind** [comment]
I'm also have problems with file names, that have UTF8 chars. getting something like this :=?UTF-8?B?VXrMjHNha3ltYXNfNjAyNTAwMjE1XzIwMTYtMTAtMTIucGRm?=
From subject field decoding works fine.

**Comment by eXorus** [comment]
Could you provide an example of the email ?

**Comment by etmind** [comment]
i found that need cut from string start =?UTF-8?B?, and from end ?=, then base64_decode() returns nice file name.

**Comment by eXorus** [comment]
FileName are already decode by decodeSingleHeader() so I don't understand how it's possible, see new Attachment() in Parser.php
`
var_dump(decodeSingleHeader("=?UTF-8?B?VXrMjHNha3ltYXNfNjAyNTAwMjE1XzIwMTYtMTAtMTIucGRm?="));`

will return:
`string(36) "Užsakymas_602500215_2016-10-12.pdf"`

**Comment by etmind** [comment]
Hmm, $attachment->getFilename();
should return decoded file name ?

**Comment by eXorus** [comment]
Yes getFilename() of attachment object return decoded filename or it's a bug :)

**Comment by etmind** [comment]
getFilename() works fine if in filename no some spec. language chars.

**Comment by eXorus** [comment]
Sorry I didn't understand. Your email with the filename 
`=?UTF-8?B?VXrMjHNha3ltYXNfNjAyNTAwMjE1XzIwMTYtMTAtMTIucGRm?=`

Need to be decoded when you read $attachment->filename or $attachment->getFilename().

The decoded method manage all spec. language chars if it's not the case please provide me the full email to understand the issue.
