### ISSUE TITLE
Header content in message body

### ISSUE THREAD

**Issue by jItendrasingh5911** [php-mime-mail-parser/php-mime-mail-parser#85]
Hi,

I am trying to parse the following attached email, but some header information is also including in the email message body.

And in another email i had the same issue, i found that mailparse_msg_get_structure() function returing single valued array because of extra newline in the email header and i removed that new line and email message extracted properly.

But in the following attached email i could not make it work.Can you please look into the issue.
[email.txt](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/202004/email.txt)

Thanks

**Comment by eXorus** [comment]
Hi,

Witch header information do you need in your email.txt ?

**Comment by jItendrasingh5911** [comment]
Hi,

$this->parser->getMessageBody('html');

This function returns the following text from above attached email raw data.As you can see that header information and attachment base64 data is attached in message body. It should not be include in message body.


Date: Mon, 4 Apr 2016 06:43:35 +0200
Message-ID:
MIME-Version: 1.0
Content-Type: multipart/related;
boundary="----=_NextPart_000_000D_01D18E3D.503E6270"
X-Mailer: Microsoft Outlook 15.0
Thread-Index: AQEAZDiXMbwHSWq8UGwtFRh7ZbEjAwIgU965oQqNywA=
Content-Language: fr

This is a multipart message in MIME format.

------=_NextPart_000_000D_01D18E3D.503E6270
Content-Type: multipart/alternative;
boundary="----=_NextPart_001_000E_01D18E3D.503E6270"


------=_NextPart_001_000E_01D18E3D.503E6270
Content-Type: text/plain;
charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

Dear,

=20

I was in business travel, i send you access tomorrow.

=20

Best regards.

Freddy

=20

De : Webkul Software Pvt Ltd [mailto:support@webkul.com]=20
Envoy=C3=A9 : lundi 28 mars 2016 09:10
=C3=80 : info@saro-nautic.com
Objet : New Reply Added on ticket #2396=20

=20



_____ =20

You can click on this link #2396 =
to view your =
ticket.

Agent Reply:

Hello,

=20

Please send me your FTP details and Admin Details.

=20

I will check the issues.

=20

Best regards,

Dheeraj




------=_NextPart_001_000E_01D18E3D.503E6270
Content-Type: text/html;
charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

Dear,

 =

I was in business =
travel, i send you access tomorrow.

 =

Best =
regards.

Freddy=

 =

De : Webkul =
Software Pvt Ltd [mailto:support@webkul.com] =

Envoy=C3=A9 : lundi 28 mars 2016 =
09:10
=C3=80 : =
info@saro-nautic.com
Objet : New Reply Added on ticket =
#2396

 

You can click on this link #2396=
to view your ticket.

Agent Reply:

Hello,

 

Please send me your FTP details and Admin =
Details.

 

I will check the issues.

 

Best regards,

Dheeraj


------=_NextPart_001_000E_01D18E3D.503E6270--

------=_NextPart_000_000D_01D18E3D.503E6270
Content-Type: image/jpeg;
name="~WRD000.jpg"
Content-Transfer-Encoding: base64
Content-ID:

/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0a
HBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIy
MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCABkAGQDASIA
AhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQA
AAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3
ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWm
p6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEA
AwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSEx
BhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElK
U1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3
uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3+iii
gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA
CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK
KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo
ooAKKKKACiiigAooooAKKKKACiiigD//2Q==

------=_NextPart_000_000D_01D18E3D.503E6270
Content-Type: image/jpeg;
name="image001.jpg"
Content-Transfer-Encoding: base64
Content-ID:

/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAoHBwkHBgoJCAkLCwoMDxkQDw4ODx4WFxIZJCAmJSMg
IyIoLTkwKCo2KyIjMkQyNjs9QEBAJjBGS0U+Sjk/QD3/wAALCAABAAEBAREA/8QAHwAAAQUBAQEB
AQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1Fh
ByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZ
WmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXG
x8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/9oACAEBAAA/APZq/9k=

------=_NextPart_000_000D_01D18E3D.503E6270--


---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by eXorus** [comment]
I'm sorry but I can't do anything your email is not correctly formated like RFC822 said the first null line = the end of the header : 

 A message consists of header fields and, optionally, a body.
     The  body  is simply a sequence of lines containing ASCII charac-
     ters.  It is separated from the headers by a null line  (i.e.,  a
     line with nothing preceding the CRLF).

http://tools.ietf.org/html/rfc822#section-3

**Comment by jItendrasingh5911** [comment]
Hi,

I agree with you,it is not formated correctly.

By the way , it's a greate extension.

Thanks

**Comment by eXorus** [comment]
Thanks
