### ISSUE TITLE
Warning: input is not rfc822 compliant

### ISSUE THREAD

**Issue by Monyer** [php-mime-mail-parser/php-mime-mail-parser#87]
in eml
`To: news <<news@bank.com>>`
(this can recognize in thunderbird)
in code
`$to = $Parser->getAddresses('to');`

the warning
`Warning: input is not rfc822 compliant: already in < bracket in D:\PhpMimeMailParser\Parser.php on line 278`

error happend in
```
    public function getAddresses($name)
    {
        $value = $this->getHeader($name);
        return mailparse_rfc822_parse_addresses($value);
    }
```
my solution temporary
```
    public function getAddresses($name)
    {
        $value = $this->getHeader($name);
        return @mailparse_rfc822_parse_addresses($value);
    }
```

**Comment by eXorus** [comment]
Sorry I can't use @ to hide error, this is not a good practice

3 solutions for you :

- Working with rfc822 compliant email (I know it's difficult)
- Create a bug in mailparse extension : https://github.com/php/pecl-mail-mailparse
- Use getHeader('to') to construct your own implementation (with regex for example)
