### ISSUE TITLE
bug in getAddresses

### ISSUE THREAD

**Issue by Monyer** [php-mime-mail-parser/php-mime-mail-parser#88]
in eml
`From: =?utf-8?Q?John=20Green=2C=20NA?= <editor@domain.com>`

when decode
`From:John Green, NA<editor@domain.com>`

in code
```
$from = $Parser->getAddresses('from');
var_dump($from);
```

the wrong result is
```
array(2) {
  [0]=>
  array(3) {
    ["display"]=>
    string(15) "John Green"
    ["address"]=>
    string(15) "John Green"
    ["is_group"]=>
    bool(false)
  }
  [1]=>
  array(3) {
    ["display"]=>
    string(3) "NA"
    ["address"]=>
    string(24) "editor@domain.com"
    ["is_group"]=>
    bool(false)
  }
}
```
the right one is
```
array(1) {
  [0]=>
  array(3) {
    ["display"]=>
    string(15) "John Green, NA"
    ["address"]=>
    string(15) "editor@domain.com"
    ["is_group"]=>
    bool(false)
  }
}
```

**Comment by eXorus** [comment]
I'm not sure it's an error according to the specification "," is a delimiter for different emails.

php-mime-mail-parser use mailparse_rfc822_parse_addresses() so you can open a bug here : https://github.com/php/pecl-mail-mailparse if you want.
