### ISSUE TITLE
Mail OSx body not parsed

### ISSUE THREAD

**Issue by matteomartinelli** [php-mime-mail-parser/php-mime-mail-parser#89]
I received this email from Mail OSx but it doesn't have been parsed properly since I get and empty string as email's body.

>
From: xxx <xxx@xxx.it>
Content-Type: text/plain;
 charset=us-ascii
Content-Transfer-Encoding: 7bit
X-Smtp-Server: 7D32F3B7-7417-4CAF-9223-6D8BE2CB6456
Subject: cia
Message-Id: <F98474F3-256B-454A-BBAD-FC2BFCE05891@xxx.xxx>
X-Universally-Unique-Identifier: 13D513E8-07D0-45B5-887C-496AB3672C4C
Date: Wed, 27 Apr 2016 23:45:33 +0200
To: xxxxx <message@xxx.xxx>
Mime-Version: 1.0 (Mac OS X Mail 9.3 \(3124\))
>
>hello

**Comment by matteomartinelli** [comment]
I would say that it doesn't work with any email provider in "text/plain" mode. (tested with gmail)

>                                                                                                                                                                                                                                                                
MIME-Version: 1.0
Received: by 10.25.151.76 with HTTP; Fri, 29 Apr 2016 12:10:19 -0700 (PDT)
Date: Fri, 29 Apr 2016 21:10:19 +0200
Delivered-To: matteomartinelli1992@gmail.com
Message-ID: <CABbkapcmM2joOijxdS9wB47VYCv9FS4kpa-ts-oSDrvmvz+u9g@mail.gmail.com>
Subject: asd
From: Matteo Martinelli <matteomartinelli1992@gmail.com>
To: Matteo Martinelli <message@fe992342.crmhero.io>
Content-Type: text/plain; charset=UTF-8

asd

**Comment by eXorus** [comment]
No issue for me on PHP5. This case is already tested with m0021.

$Parser->getMessageBody('text'); ==> Return Hello
$Parser->getMessageBody('html'); ==> Return ''

Are you on PHP7 ?

**Comment by matteomartinelli** [comment]
I tried both php5.6 and php7.0. It seems the starting-pos-body and endind-pos-body have same value.
I'm trying to figure out why it doesn't work for me.

**Comment by matteomartinelli** [comment]
If I add a "[enter]" at the end of the mail it works. Could you spot the reason?
Thank you.

**Comment by eXorus** [comment]
:)
Sorry for that it's already an issue #49 I'm waiting someone to automatically add a new line at the end of the file if there is not.
