### ISSUE TITLE
Getters for protected variables

### ISSUE THREAD

**Issue by andreaskas** [php-mime-mail-parser/php-mime-mail-parser#93]
After releasing version 2.4.0 there is no access to protected variables for any reason. You should introduce getters to allow access to the variable contents. Eg. at Parser.php create getParts that will return $this->parts. Do not introduce setters for security reasons (since you downgraded the access level to protected)

This change has break almost everything.

**Comment by eXorus** [comment]
I'm so sorry for that I will fix it tomorrow morning in 2.4.1
