### ISSUE TITLE
UID

### ISSUE THREAD

**Issue by matiux** [php-mime-mail-parser/php-mime-mail-parser#95]
How can I get the UID of a message?

**Comment by mstaack** [comment]
the uid is not part of the mime message. it will be available via the imap protocoll  via imap_* functions or raw imap

**Comment by matiux** [comment]
it's a shame,
I'm creating a php imap client and the UID is a important information. But I will create some workaround..

**Comment by eXorus** [comment]
If you are talking about :
Message-ID: <CAH_ZkVmUSM8t2JxgqcuLCQ8d+R_hkKpNHTubJOQK07y=36+d4Q@mail.gmail.com>

It's possible to get it : $this->getHeader('message-id')

**Comment by matiux** [comment]
No, UID is a unique ID assigned to each message

https://tools.ietf.org/html/rfc3501#page-8

**Comment by eXorus** [comment]
I think it's the same.
If it's not the same could you send me an example ?

**Comment by matiux** [comment]
This is a good explanation:
http://stackoverflow.com/questions/37162681/what-is-the-difference-between-imapmessage-getuid-and-message-id-header/37163120#37163120

**Comment by eXorus** [comment]
Ok I understand so UID is ID of Imap.

Php-mime-mail-parser doesn't use imap so it's impossible.

What is your usecase ? If you use imap you don't need php-mime-mail-parser

**Comment by matiux** [comment]
I'm using Php-mime-mail-parser to parse easily the mails (get headers, body, attachment etc), but since i'm developping a webmail client php-based, I need also of some imap details like UID, UIDnext etc. I have solved taking the imap informations, opening a socket directly to imap server and using IMAP command. For example I can get the UIDnext of a folder with the "EXAMINE" imap command that returns this output:

a1 examine INBOX
* FLAGS (\Answered \Flagged \Deleted \Seen \Draft NonJunk $Forwarded Junk)
* OK [PERMANENTFLAGS ()] Read-only mailbox.
* 73 EXISTS
* 1 RECENT
* OK [UNSEEN 73] First unseen.
* OK [UIDVALIDITY 1414137089] UIDs valid
* OK [UIDNEXT 5049] Predicted next UID
* OK [HIGHESTMODSEQ 11137] Highest
2 OK [READ-ONLY] Select completed.

As you can see, in the list there is a UIDnext that is the next imap uid of the INBOX folder. Then I use regular expression to get datas I need.

Another example. With this command:

UID FETCH 1:4 body[]

I get the full raw body from UID 1 to UID 4. Then I can pass the output to your library:

$message = new Parser();
$message->setText(implode("\n", $this->imapLastResponse));

**Comment by eXorus** [comment]
So you don't need php-mime-mail-parser and mailparse. Php-mime-mail-parser don't need to stock mail in imap.

You only need to use imap function from PHP Core :
http://php.net/manual/en/book.imap.php
