### ISSUE TITLE
missing vendor/autoload.php

### ISSUE THREAD

**Issue by vampirismtrueblood** [php-mime-mail-parser/php-mime-mail-parser#97]
I did composer installation, yum installation of mail parser, cloned your repo, and vendor autoload.ph just is NOT there ...

I'm on Centos 7 , php 5.6.22 ...
I badly need this parser, any help is appreciated.

Thank you.

**Comment by eXorus** [comment]
Sorry I don't understand your issue.
You don't need to clone repo, just do:
`composer require php-mime-mail-parser/php-mime-mail-parser`

The autoload is generated when you did composer require or composer update or composer install.
